USE [master]
GO
IF DB_ID (N'MobileTech') IS NOT NULL ALTER DATABASE [MobileTech] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
USE master
GO 
IF DB_ID (N'MobileTech') IS NOT NULL DROP DATABASE MobileTech 
GO 
