//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileTech.Windows.UI.Inventory.Menu {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobileTech.Windows.UI.Inventory.Menu.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Request.
        /// </summary>
        internal static string LoadRequest {
            get {
                return ResourceManager.GetString("LoadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Transfer.
        /// </summary>
        internal static string LoadTransfer {
            get {
                return ResourceManager.GetString("LoadTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Report.
        /// </summary>
        internal static string PrintReport {
            get {
                return ResourceManager.GetString("PrintReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return To Stock.
        /// </summary>
        internal static string ReturnToStock {
            get {
                return ResourceManager.GetString("ReturnToStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000 - Inventory Menu.
        /// </summary>
        internal static string Title2000 {
            get {
                return ResourceManager.GetString("Title2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck Stock.
        /// </summary>
        internal static string TruckStock {
            get {
                return ResourceManager.GetString("TruckStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unload.
        /// </summary>
        internal static string Unload {
            get {
                return ResourceManager.GetString("Unload", resourceCulture);
            }
        }
    }
}
