/*
   5 ÿםגאנÿ 2007 ד. 18:55:21
   User: furmanbo
   Server: SQLDBSDEV
   Database: YONIXDPITST
   Application: MS SQLEM - Data Tools
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
ALTER TABLE dbo.CreditCard_Payment ADD
	BankAccountNumber varchar(20) NULL,
	BankRoutingNumber varchar(20) NULL,
	DriverLicenseNumber varchar(20) NULL,
	DriverLicenseState varchar(20) NULL
GO
COMMIT
