//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileTech.Windows.UI.Inventory.Load {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobileTech.Windows.UI.Inventory.Load.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustments.
        /// </summary>
        internal static string Adjustments {
            get {
                return ResourceManager.GetString("Adjustments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Load.
        /// </summary>
        internal static string CurrentLoad {
            get {
                return ResourceManager.GetString("CurrentLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable to save load.
        /// </summary>
        internal static string ExEnableToSaveLoad {
            get {
                return ResourceManager.GetString("ExEnableToSaveLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num:{0}.
        /// </summary>
        internal static string LbItemNumber {
            get {
                return ResourceManager.GetString("LbItemNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck:{0}.
        /// </summary>
        internal static string LbTruckQty {
            get {
                return ResourceManager.GetString("LbTruckQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return To Stock.
        /// </summary>
        internal static string ReturnToStock {
            get {
                return ResourceManager.GetString("ReturnToStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Load.
        /// </summary>
        internal static string TotalLoad {
            get {
                return ResourceManager.GetString("TotalLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck Stock.
        /// </summary>
        internal static string TruckStock {
            get {
                return ResourceManager.GetString("TruckStock", resourceCulture);
            }
        }
    }
}
