package com.themidnightcoders;

/**
 * 
 */
public class ColumnKeyType {


    public static final ColumnKeyType FULLTEXT = new ColumnKeyType("FULLTEXT", 0);
    public static final int DISC_FULLTEXT = 0;

    public static final ColumnKeyType NONE = new ColumnKeyType("NONE", 1);
    public static final int DISC_NONE = 1;

    public static final ColumnKeyType PRIMARY = new ColumnKeyType("PRIMARY", 2);
    public static final int DISC_PRIMARY = 2;

    public static final ColumnKeyType UNIQUE = new ColumnKeyType("UNIQUE", 3);
    public static final int DISC_UNIQUE = 3;

    private ColumnKeyType(String value, int discriminator) {
        this.value = value;
        this.discriminator = discriminator;
    }

    public String getValue() {return value;}
    public int getDiscriminator() {return discriminator;}
    public String toString() { return "enum:" + value + "[" + discriminator + "]"; }
    private String value;
    protected int discriminator;
}

/*
 * Generated by Systinet WSDL2Java
 * http://www.systinet.com
 */

