DROP TABLE IF EXISTS `techmast`;
CREATE TABLE `techmast` (
  `TECH_ID` varchar(3) DEFAULT NULL,
  `TECH_NAME` varchar(40) DEFAULT NULL,
  `EMAILADDR` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `techmast` (`TECH_ID`,`TECH_NAME`,`EMAILADDR`) VALUES 
 ('023','DELGADO, RUBEN','rubendelgado7@yahoo.com'),
 ('065','CURBY, T.J.','davey876432th@msn.com'),
 ('067','TROJAN, DWAYNE','hgrimes21@verizon.net'),
 ('068','MORRIS, DANNY','damford@access4less.net'),
 ('071','BROOKS, LEE','craigskirk@yahoo.com'),
 ('084','HOLT, CORY','craigskirk@yahoo.com'),
 ('087','WATSON, JOHNNY','alloutcarpetcleaning@hotmail.com'),
 ('089','RAMIREZ, VICTOR','juniorscarpetcleaning@yahoo.com'),
 ('092','ALFORD, JARED','jaredwesley@yahoo.com'),
 ('094','MARTIN, MATT','amazingairinc@aol.com'),
 ('096','TAYLOR, GARRY','nortay@airmail.net'),
 ('102','JOHNSON,randy','craigskirk@yahoo.com'),
 ('103','OGANA, JAMES','dlloydds@aol.com'),
 ('114','GARRETT, DON','2GARRETT4@ATT.NET'),
 ('123','WHITEHEAD, JOHN','collincreeksvcs@verizon.net'),
 ('125','COOK, JEFF','thecooksx1@yahoo.com'),
 ('133','ANDERTON, CHRIS','alloutcarpetcleaning@hotmail.com'),
 ('134','LEWIS, DUSTY','DUSTY70_6@MSN.COM'),
 ('151','NJAKA, EDWIN','ENJAKA@YMAIL.COM'),
 ('159','MCLAUCHLIN, JOEL','joelmclauchlin@yahoo.com'),
 ('163','NOACK, TIM','craigskirk@yahoo.com'),
 ('166','HARRIS, CHAD','craigskirk@yahoo.com'),
 ('168','LEITNER, CHRIS','eliteservices@1scom.net'),
 ('172','HEDGER, DWIGHT','terryhedger@verizon.net'),
 ('173','DREW, MICHAEL','dlloydds@aol.com'),
 ('175','TAYLOR (FR), JEFF','jeffgtaylor@yahoo.com'),
 ('176','ALLEN, SHAWN','alloutcarpetcleaning@hotmail.com'),
 ('178','KINNEY, KINN','kinneyflooring@yahoo.com'),
 ('179','MORGAN(LD), MARK','dlloydds@aol.com'),
 ('183','MORGAN(CM), MARK','cleanmaster1@sbcglobal.net'),
 ('184','COOPER, JERRY','alloutcarpetcleaning@hotmail.com'),
 ('186','CUNNY, JOHNNY','lms@neto.com'),
 ('187','MCGOVERN, LEE','kljmc@sbcglobal.net'),
 ('188','DOSHER, TERRY','t_d22@hotmail.com'),
 ('194','BAKER, TJ','tjbakerjr@yahoo.com'),
 ('195','WAGONER, JUSTIN','rudy4702@verizon.net'),
 ('196','EARL, TOM','tomearl47@yahoo.com'),
 ('197','LOCKEY, ED','elockeyiii@verizon.net'),
 ('202','HARPER, DUSTIN','GHBH1983@YAHOO.COM'),
 ('207','JOHNSON, JASON','craigskirk@yahoo.com'),
 ('220','CORNER, STEVE','collincreeksvcs@verizon.net'),
 ('224','GARNER, STEVE','alloutcarpetcleaning@hotmail.com'),
 ('230','CHAVEZ, LOUIS','amazingairinc@aol.com'),
 ('231','ANDERSON, WILLIAM','dlloydds@aol.com'),
 ('236','TANDARICH, RON','craigskirk@yahoo.com'),
 ('242','WILLINGHAM, BRIAN','alloutcarpetcleaning@hotmail.com'),
 ('258','TILTON, CHRIS','craigskirk@yahoo.com'),
 ('262','FLORES, LEONEL','leonel_flores@majesticcarpetcare.com'),
 ('263','ELENBAAS, DAVE','moonlightcarpet@yahoo.com'),
 ('265','HOUSTON, CORY','houston.fam@sbcglobal.net'),
 ('266','TURNER, RODNEY','xcarpets@aol.com'),
 ('267','CHICO, CARLOS','rubendelgado7@yahoo.com'),
 ('269','LANTOS, KRIS','craigskirk@yahoo.com'),
 ('272','HARRISON, LOUIS','ultimatecarpetcare@sbcglobal.net'),
 ('273','DELGADO, GILBERT','superiorcarpet93@aol.com'),
 ('275','PEOPLES, JAMES','alloutcarpetcleaning@hotmail.com'),
 ('276','RYAN, MARK','apluscarpet1@yahoo.com'),
 ('277','CERVANTES, ADRIAN','dlloydds@aol.com'),
 ('279','TOTEN, JERRY','jerryscarpetservice@comcast.net'),
 ('283','VIDALES, ARTURO(PC)','procarpetsolutions@compucluro.com'),
 ('290','BORRAS, JOSE','excellencecarpetclean@hotmail.com'),
 ('291','MARTINEZ, RUDY','rudy4702@verizon.net'),
 ('292','MCCOY, STEVE','mccoybnd@aol.com'),
 ('293','RANSOM(RES), STEVE','sransom@sbcglobal.net'),
 ('295','TESSER, JOHN','moonlightcarpet@yahoo.com'),
 ('296','MAGANA, GERARDO','cleanmaster1@sbcglobal.net'),
 ('298','BEARDSLEY, JOHN','crystalkleen@sbcglobal.net'),
 ('299','CHAMBERLAIN, JAMES','craigskirk@yahoo.com'),
 ('300','GREENHILL, STEVE','stevegreenhill@lycos.com'),
 ('304','ANDERSON, MARCUS','marcmari_corp@msn.com'),
 ('306','MILLER, JASON','moonlightcarpet@yahoo.com'),
 ('311','SALAZAR, JUSTIN','mastercarpetservice@prodigy.net'),
 ('325','MATHEWS, JASON','tomearl47@yahoo.com'),
 ('327','FULMER, HARLIN','amazingairinc@aol.com'),
 ('328','FREEMAN, TRUCK2','mikes05hemi@yahoo.com'),
 ('334','GONZALES, SERGIO','rubendelgado7@yahoo.com'),
 ('335','HARGROVE, GREG','craigskirk@yahoo.com'),
 ('336','SWISTAK(HIM), FRANK','lovezhogz@aol.com'),
 ('340','WHITE, KIRBY','cleaningkirby@aol.com'),
 ('342','DAVIS, BRIAN','craigskirk@yahoo.com'),
 ('344','SMITH, TERRY','alloutcarpetcleaning@hotmail.com'),
 ('345','CHARLESTON, JEREMY','craigskirk@yahoo.com'),
 ('346','RAMIREZ, VICTOR','rudy4702@verizon.net'),
 ('347','RAMIREZ, RAUL','rudy4702@verizon.net'),
 ('348','CAPETILLO, GERALDO','rudy4702@verizon.net'),
 ('350','HEDGER(F),TERRY','twhedger@hotmail.com'),
 ('351','HEDGER(F), DWIGHT','twhedger@hotmail.com'),
 ('352','WILLIAMS(KIR), TRACY','craigskirk@yahoo.com'),
 ('353','BREWER, DAVID','twhedger@hotmail.com'),
 ('355','SAVOY, PERCY (SS)','savoyservices@sbcglobal.net'),
 ('362','SWISTAK(FR), FRANK','lovezhogz@sbcglobal.net'),
 ('364','CHANDLER, BECKET','moonlightcarpet@yahoo.com'),
 ('365','NYSTROM, JOE','jmnlcn@hotmail.com'),
 ('366','BEVARS(IN), BRUCE','brucethebev@aol.com'),
 ('369','OZANNE, PHIL','jerryscarpetservice@comcast.net'),
 ('370','BEVARS(FRCH), BRUCE','brucethebev@aol.com'),
 ('371','ANDERSON(FRCH), MARCUS','mndrsnrlwc@aol.com'),
 ('374','GRIMES, HAROLD','hgrimes21@verizon.net'),
 ('375','COCHRAN, (HWD) STEVE','hollywoodcarpetsystems@msn.com'),
 ('376','CUMMINGS, JOHN','craigskirk@yahoo.com'),
 ('380','HILDAGO (WY), WALLY','wallyhtx1@aol.com'),
 ('381','HUGHES(LM), MARK','lumarkinc@sbcglobal.net'),
 ('382','BARNES, MARSHALL','MWB33@SBCGLOBAL.NET'),
 ('388','GRESHAM, JOEL','wes@dalworth.com'),
 ('389','LINDSAY, JODI','cleanmaster1@sbcglobal.net'),
 ('390','CURBY (CM), TJ','cleanmaster1@sbcglobal.net'),
 ('391','LINZALONE(TEAM), PAT','rjteamcarpet@aol.com'),
 ('392','PAREDES, STEVE','superiorcarpet93@aol.com'),
 ('397','ALEXANDER, TERREL','craigskirk@yahoo.com'),
 ('398','CHANDLER,(TX) BECKETT','texashomecleaninginc@msn.com'),
 ('400','FLORES(CC), JAMES','jaflores96@hotmail.com'),
 ('403','STEGALL, DANNY','daron70@sbcglobal.net'),
 ('405','DEMORAES, NELSON','kjtuck@comcast.net'),
 ('406','PYLE, JOE BILL','davey876432th@msn.com'),
 ('411','COCHET, DAVID','craigskirk@yahoo.com'),
 ('414','CERVANTES, ADRIAN','alloutcarpetcleaning@hotmail.com'),
 ('417','LASTER, BROOK','craigskirk@yahoo.com'),
 ('419','FERGUSON, THOMAS','amazingairinc@aol.com'),
 ('421','COLEMAN(FRAN), JAMES','yellowkids68@yahoo.com'),
 ('422','WILLIAMS(WES), TRACY','wes@dalworth.com'),
 ('423','STEGALL, DARON','daron70@sbcglobal.net'),
 ('424','JAZZAR, OMAR','davey876432th@msn.com'),
 ('425','BURT(FR), MARK','mdburt1@yahoo.com'),
 ('428','WILLIAMS(JERR), TRACY','jerryscarpetservice@comcast.net'),
 ('429','HIDALGO(FRAN), WALLY','wally_h02@sbcglobal.net'),
 ('430','FARLOW, GREGG','gafarlow@yahoo.com'),
 ('431','SANCHEZ, JUAN','rudy4702@verizon.net'),
 ('432','POOLE, KYLE','Rewrite02@aol.com'),
 ('433','SCOTT, JACK','craigskirk@yahoo.com'),
 ('434','COMPTON, JOSH','moonlightcarpet@yahoo.com'),
 ('435','CRUZ, CARLOS','carloscruz@sbcglobal.net'),
 ('441','BLOOD, MARK','don@lmsrestoration.com'),
 ('448','PERKINS, DALE','davey876432th@msn.com'),
 ('449','JEFFREYS, MARCUS','dlloydds@aol.com'),
 ('457','CASTENADA, JASON','mastercarpetsvc@att.net'),
 ('458','COLLINS, MIKE','alloutcarpetcleaning@hotmail.com'),
 ('460','YOAS, CURT','craigskirk@yahoo.com'),
 ('463','MARTINEZ, JOE','craigskirk@yahoo.com'),
 ('468','HAWKINS, ELI','moonlightcarpet@yahoo.com'),
 ('469','GRANT, PAT','liv2rydepatgrant@earthlink.net'),
 ('470','HEARN, RICHARD','rhearn11@verizon.net'),
 ('471','LEACH, THOMAS','tleach@rmbb.net'),
 ('476','GUZMAN,EDWIN','dguzman222@aol.com'),
 ('481','DONAGHY, (FRAN) KEN','franchiseowner@sbcglobal.net'),
 ('483','DUKE, STEVE','amazingairinc@aol.com'),
 ('484','CRUZ, BRANDON','amazingairinc@aol.com'),
 ('488','ALEXANDER(HE), TERRELL','terrelalexander@aol.com'),
 ('491','DRISKILL, DOUG','dougdriskill@yahoo.com'),
 ('492','FLORES, JAMES','jaflores96@hotmail.com'),
 ('493','ANDERSON, KYLE','alloutcarpetcleaning@hotmail.com'),
 ('494','GRESHAM, WES','wes@dalworth.com'),
 ('504','HOLLENSHEAD, JASON','keten75@yahoo.com'),
 ('508','TENNISON, KRIS','svcworx@yahoo.com'),
 ('510','SANTOS, LARRY','alloutcarpetcleaning@hotmail.com'),
 ('511','WIDMAN(DC), JASON','jkswidman@aol.com'),
 ('513','WOOLDRIDGE, SCOTT','davey876432th@msn.com'),
 ('517','LEWIS, DONALD','craigskirk@yahoo.com'),
 ('518','HURST, FLENTA','bigg_hurst1977@yahoo.com'),
 ('520','VALDEZ, JUAN','davey876432th@msn.com'),
 ('522','CASTENADA (MCARE), GABRIEL','mastercarpetsvc@att.net'),
 ('533','ENGELS, FRANK','collincreeksvcs@verizon.net'),
 ('535','MORENO(FRAN), FABIAN','lovesue0319msmi@hotmail.com'),
 ('537','EWING, DOUG','collincreeksvcs@verizon.net'),
 ('539','HOWARD, JAMES','davey876432th@msn.com'),
 ('541','HIDALGO, WALLY','wallyhtx@aol.com'),
 ('544','STEVENS, RONNIE','alloutcarpetcleaning@hotmail.com'),
 ('545','OZANNE, PHILLIP','philipwozanne@msn.com'),
 ('547','THOMAS, RONNIE','davey876432th@msn.com'),
 ('560','HARTZOG, STEVE','moonlightcarpet@yahoo.com'),
 ('561','THOMAS, RONNIE(CM)','cleanmaster1@sbcglobal.net'),
 ('562','SHEVCHIK, JOHN','shevchik@sbcglobal.net'),
 ('570','LONON, JERE','craigskirk@yahoo.com'),
 ('575','BROOKS, TOM','tbjbnb@sbcglobal.net'),
 ('576','HARRISON(FR), LOUIS','ultimatecarpetcare@sbcglobal.net'),
 ('585','JORDAN, JOE','CARPETMAN103@SBCGLOBAL.NET'),
 ('587','ALFORD(FRAN), JARED','jaredwesley@yahoo.com'),
 ('589','WILSON, BOBBY','bobwilson1999@aol.com'),
 ('029','CURBY (DC), TJ','jkswidman@aol.com'),
 ('030','MELENDEZ, RICHARD','craigskirk@yahoo.com'),
 ('031','LOATMAN, KEITH','chingwe2@aol.com'),
 ('032','BALAK, KEITH','collincreeksvcs@verizon.net'),
 ('033','WILSON, BOBBY (BOBS)','bobwilson1999@aol.com'),
 ('035','SALAS(ST), RICHARD','richsalas@sbcglobal.net'),
 ('015','GRIMES, JUSTIN','wes@dalworth.com'),
 ('043','PATTON, ALAN','dlloydds@aol.com'),
 ('047','MUNOZ, JOSE','rjteamcarpet@aol.com'),
 ('048','RANSOM, STEVE','sransom@sbcglobal.net'),
 ('052','LINZALONE, PAT','marriedtorl@aol.com'),
 ('162','MAYS, RICHARD','maze05@comcast.net'),
 ('593','MCINTYRE, TYLER','davey876432th@msn.com'),
 ('594','KINDEL, TIPTON','franchiseowner@hotmail.com'),
 ('599','SALAZAR, MICHAEL','dlloydds@aol.com'),
 ('610','RAINS, CHRIS','ALYJOE@HOTMAIL.COM'),
 ('617','FLORES, ALAN','mastercarpetservice@prodigy.net'),
 ('618','WALKER, BOBBY','bgclean@aol.com'),
 ('619','SHIELDS, CHRIS','alloutcarpetcleaning@hotmail.com'),
 ('620','JACKSON, SHAWN','craigskirk@yahoo.com'),
 ('622','DELGADO, CASEY','superiorcarpet93@aol.com'),
 ('635','WELDON(ES), AARON','jrhaw418@hotmail.com'),
 ('640','MITCHELL, MIKE','m_mitchell1963@yahoo.com'),
 ('647','FRANKLIN, STEVE','steve.franklin@tx.rr.com'),
 ('649','LEITNER (FR), CHRIS','cleitner.dalworth@sbcglobal.net'),
 ('651','LEACH, ROBERT','tleach@rmbb.net'),
 ('654','WAHL, KEVIN','ice33@netscape.com'),
 ('664','FREEMAN, TOM','kjfreeman1@verizon.net'),
 ('665','BULLARD, DANA','alloutcarpetcleaning@hotmail.com'),
 ('670','RIBERIO, RONALDO','grpservicesdfw@yahoo.com'),
 ('680','DUONG, STEVE','STEVEDUONG@YAHOO.COM'),
 ('682','WESLEY(NA), BRANDON','STEVEDOUNG@YAHOO.COM'),
 ('690','FARRIS, JONATHAN','alloutcarpetcleaning@hotmail.com'),
 ('692','RONNING, JASON','craigskirk@yahoo.com'),
 ('693','KEITH, (FR) ERIK','erikskeith@gmail.com'),
 ('700','WESLEY, BRANDON','hgrimes21@verizon.net'),
 ('702','HALE, JIM','jameshhale@sbcglobal.net'),
 ('709','ROBERTS (LCS), DAVID','dlloydds@aol.com'),
 ('711','GUEDES, VINNY','VINNYBGUEDES@HOTMAIL.COM'),
 ('712','FREEMAN, MIKE','mikes05hemi@yahoo.com'),
 ('716','GOLDBERG, RICK','rbg0871@yahoo.com'),
 ('720','PAREDES, JOSH','superiorcarpet93@aol.com'),
 ('724','STEPHENS, TIM','y98251@netscape.net'),
 ('726','TIMMONS, CHRIS','proclean4you@yahoo.com'),
 ('730','ROSS, GARY','alloutcarpetcleaning@hotmail.com'),
 ('731','BENNETT, CHRIS','HOLLYB_26@NETZERO.NET'),
 ('733','BLACKERBY, ALLEN','alloutcarpetcleaning@hotmail.com'),
 ('737','BOSWELL, SHIRLEY','amazingairinc@aol.com'),
 ('740','PAREDES, ANTHONY','superiorcarpet93@aol.com'),
 ('744','BELEZ, CHASE','rjteamcarpet@aol.com'),
 ('749','STEWART, ALLEN','elementflooring@yahoo.com'),
 ('751','BURT, MARK','mdburt1@yahoo.com'),
 ('754','JIMENEZ, RAUL','rjteamcarpet@aol.com'),
 ('757','HEDGER, TERRY','terryhedger@verizon.net'),
 ('763','NATOLI, DARON','cleanmaster1@sbcglobal.net'),
 ('769','SINCLAIR, RICHARD','craigskirk@yahoo.com'),
 ('770','BERGDORF, MARK','craigskirk@yahoo.com'),
 ('783','OGANA(DT), JAMES','dalltexsteam@yahoo.com'),
 ('787','LEATH, DONNIE','moonlightcarpet@yahoo.com'),
 ('801','SCULLIN, MIKE','divine_2001@charter.net'),
 ('802','FREI, COREY','collincreeksvcs@verizon.net'),
 ('818','RETELLE, CHRIS','collincreeksvcs@verizon.net'),
 ('819','MOLINA, JUAN','hgrimes21@verizon.net'),
 ('822','LONG, GAREN','collincreeksvcs@verizon.net'),
 ('832','HARTZOG, (XT) STEVE','zogman1@comcast.net'),
 ('833','THACKER, DAVID','davey876432th@msn.com'),
 ('834','PUTMAN, MICHAEL','putt2151@excite.com'),
 ('844','WELDON(FR), AARON','aaron_weldon@att.net'),
 ('846','LYNN, ARNOLD','amazingairinc@charter.net'),
 ('851','SULLIVAN, DANIEL','cleanmaster1@sbcglobal.net'),
 ('858','BOSWELL, LEONARD','amazingairinc@aol.com'),
 ('863','ALLEN, VICTOR','alloutcarpetcleaning@hotmail.com'),
 ('865','BURTON, RICK','r24burton@msn.com'),
 ('869','THACKER SR., DAVID','davey876432th@msn.com'),
 ('870','MESECHER, DAVID','davey876432th@msn.com'),
 ('873','LEWIS, LACHRISTON','LACHRISTONLEWIS@YAHOO.COM'),
 ('878','KEARNY, DAVID(MASTERTECH)','contact@mastertechcarpet.com'),
 ('881','SALDANA, JESSE','collincreeksvcs@verizon.net'),
 ('883','TIPPETT, BILL','tiptop@charter.net'),
 ('885','DRESSEN, HOWARD','AMSHRD@YAHOO.COM'),
 ('886','PIERCE(CM), JASON','cleanmaster1@sbcglobal.net'),
 ('890','MEDINA, SERGIO','medinaser@aol.com'),
 ('892','VIDALES, ARTURO','guelanotguel@msn.com'),
 ('893','ARREOLA, JUAN','jma1112@aol.com'),
 ('903','PINA, GABE(HORIZON)','horizon_carpet@yahoo.com'),
 ('908','WIDMAN, JASON','jkswidman@aol.com'),
 ('917','HADLEY, LARRY','amazingairinc@aol.com'),
 ('918','MONTEL, DEREK','hgrimes21@verizon.net'),
 ('922','RAWLS, DEREK','deorka@yahoo.com'),
 ('925','MORENO, FABIAN','lovesue0319@yahoo.com'),
 ('926','ADAMS, MIKE(PC)','proclean4you@yahoo.com'),
 ('930','HASTY, TED','kendasplace@hotmail.com'),
 ('933','HAYNES, ROBERT','burleson985@aol.com'),
 ('935','PERKINS, DALE(PRO CLEAN)','proclean4you@yahoo.com'),
 ('940','LINZALONE JR, PAT','craigskirk@yahoo.com'),
 ('943','BRYANT, CHUCK','m_mitchell1963@yahoo.com'),
 ('946','MORGAN, MARK','markchevy3@aol.com'),
 ('947','WHITLEY, JASON','sput_76@yahoo.com'),
 ('948','PIERCE, JASON','davey876432th@msn.com'),
 ('949','COLEMAN, BRIAN','collincreeksvcs@verizon.net'),
 ('950','DRAPER, GREG(DIVINE)','divine_2001@charter.net'),
 ('951','CRENSHAW, JOEL','eyeluv2hoop@yahoo.com'),
 ('955','TRIBBLE, MARK','user260602@aol.com'),
 ('958','UTZMAN, MIKE','cleanmaster1@sbcglobal.net'),
 ('959','CHAUNCEY(LD), DAVID','dlloydds@aol.com'),
 ('961','CAFFEY, JASON','collincreeksvcs@verizon.net'),
 ('963','MAGEMBE, COSMOS','cmokua@juno.com'),
 ('965','HARPER, GERALD','GHBH1983@YAHOO.COM'),
 ('967','TORREZ, ADRIAN','rubendelgado7@yahoo.com'),
 ('968','PIERCE, DAVID','alloutcarpetcleaning@hotmail.com'),
 ('970','WEATHERREAD, CHARLES','CHARLESWEATHERREAD@HUGHES.NET'),
 ('975','FINLEY, JAMES','alloutcarpetcleaning@hotmail.com'),
 ('976','KEPHART, KIRK','RACERKIRK@YAHOO.COM'),
 ('978','BROWN, SHAWN','davey876432th@msn.com'),
 ('979','ADKINS, CHRIS','cadkins101@verizon.net'),
 ('980','GODWIN, BOBBY(AS)','BGODWIN1964@YAHOO.COM'),
 ('989','ELLIS, KEITH','kellis9876@mail.com'),
 ('994','DOKO, TEKI','dokodaddy@hotmail.com'),
 ('998','HIGGINS(cm),JASON','cleanmaster1@sbcglobal.net'),
 ('999','BRAZ(BT), BRUNO','brunobraz@sbcglobal.net'),
 ('091','GROFF, DAVID','rubendelgado7@yahoo.com'),
 ('216','SANDERS, CLIFF','craigskirk@yahoo.com'),
 ('217','FANT, DEREK','derfa7@aol.com'),
 ('409','CONCEPCION, JOSE','FAMILYFCC@AOL.COM'),
 ('563','WAITE, CHARLIE','waitecw@aol.com'),
 ('564','DANLEY(REJ), MONTY','monty_danley@hotmail.com'),
 ('565','CARRIZALES, GUS','gtcthird@aol.com'),
 ('568','NAJJAR, SHADI(ROYALTY)','najjar12@hotmail.com'),
 ('569','MILLER, BROOKS','skoorbrellim@hotmail.com'),
 ('085','DRAPER, RANDY(DIVINE)','divine_2001@charter.net'),
 ('475','KECK, DENNIS','rlrbrothers@verizon.net'),
 ('315','ROBERTSON, VINCENT','craigskirk@yahoo.com'),
 ('456','WOODRUFF(RESOLVE)','craigskirk@yahoo.com'),
 ('514','LOGAN(RESOLVE)','craigskirk@yahoo.com'),
 ('527','RICO, ERNEST','rjteamcarpet@aol.com'),
 ('524','THACKER JR(RESOLVE)','craigskirk@yahoo.com'),
 ('597','KIRK, CRAIG(RESOLVE)','craigskirk@yahoo.com'),
 ('752','PIERCE(RESOLVE)','craigskirk@yahoo.com'),
 ('001','SWISTAK, FRANK','lovezhogz@aol.com'),
 ('113','TYNES, CODY','alloutcarpetcleaning@hotmail.com');


UPDATE TechnicianDefault td
inner join Techmast t on t.tech_id = td.ServmanId
SET td.Email = t.EMAILADDR;

DROP TABLE `techmast`;

INSERT INTO `sysversion` (`Version`) VALUES 
(14);