package com.ebs.eroof.dto
{
	import com.adobe.cairngorm.vo.IValueObject;
	import com.quickbase.idn.dto.IKingussieInfo;
	import com.quickbase.idn.fieldtypes.*;
	import com.quickbase.idn.fieldtypes.bool.*;
	import com.quickbase.idn.fieldtypes.float.*;
	import com.quickbase.idn.fieldtypes.int32.*;
	import com.quickbase.idn.fieldtypes.int64.*;
	import com.quickbase.idn.fieldtypes.text.*;
	import mx.collections.ArrayCollection;

	public class Facilities_Info implements IKingussieInfo
	{
		// Important Note:
		//    This class was automatically generated.  If you make changes to it and
		//    subsequently run the generator tool again, all changes will be overwritten!

		private static var _instance:Facilities_Info = null;

		function Facilities_Info(forcePrivateClass:Private)
		{
			// MetaData Initializers
			var field:FieldDescriptor;

			field = new FieldDescriptor();
			field.fid = 79;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.URL;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Address Map";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.appearsAs = "Address Map";
			field.fieldName = "AddressMap";
			field.required = false;
			field.formula = "\"http://maps.google.com/maps?t=m&hl=en&z=\" & [MapZoom] & \"&q=\" & URLEncode(Trim([Facility Name])) & \"@\" & [MapLatLong]";
			field.foreignKey = 0;
			field.findEnabled = true;
			_AddressMapInfo = new URLField(field);
			_fieldInfo.addItem(_AddressMapInfo);

			field = new FieldDescriptor();
			field.fid = 80;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.URL;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Site Map";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.appearsAs = "Site Plan";
			field.fieldName = "SiteMap";
			field.required = false;
			field.formula = "\"http://maps.google.com/maps?t=k&hl=en&z=\" & [SitePlanZoom] & \"&q=\" & URLEncode(Trim([Facility Name])) & \"@\" & [MapLatLong]";
			field.foreignKey = 0;
			field.findEnabled = true;
			_SiteMapInfo = new URLField(field);
			_fieldInfo.addItem(_SiteMapInfo);

			field = new FieldDescriptor();
			field.fid = 30;
			field.lutFid = 7;
			field.numLines = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 29;
			field.label = "Client";
			field.allowNewChoices = false;
			field.mode = ENMode.Lookup;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "Client";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_ClientInfo = new TextField(field);
			_fieldInfo.addItem(_ClientInfo);

			field = new FieldDescriptor();
			field.fid = 6;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Facility Name";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "FacilityName";
			field.required = true;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_FacilityNameInfo = new TextField(field);
			_fieldInfo.addItem(_FacilityNameInfo);

			field = new FieldDescriptor();
			field.fid = 9;
			field.lutFid = 0;
			field.numLines = 3;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Address";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "Address";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_AddressInfo = new TextField(field);
			_fieldInfo.addItem(_AddressInfo);

			field = new FieldDescriptor();
			field.fid = 11;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "City";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "City";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_CityInfo = new TextField(field);
			_fieldInfo.addItem(_CityInfo);

			field = new FieldDescriptor();
			field.fid = 33;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "SectionsCount";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = 0;
			field.mode = ENMode.Summary;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Facilities";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.fieldName = "SectionsCount";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = false;
			_SectionsCountInfo = new NumberField(field);
			_fieldInfo.addItem(_SectionsCountInfo);

			field = new FieldDescriptor();
			field.fid = 34;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Total Sq Ft";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = 0;
			field.mode = ENMode.Summary;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Facilities";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.fieldName = "TotalSqFt";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = false;
			_TotalSqFtInfo = new NumberField(field);
			_fieldInfo.addItem(_TotalSqFtInfo);

			field = new FieldDescriptor();
			field.fid = 35;
			field.unique = false;
			field.commaStart = 3;
			field.fieldHelp = "";
			field.allowNewChoices = false;
			field.mode = ENMode.Summary;
			field.baseType = ENBaseType.Float;
			field.tableName = "Facilities";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.required = false;
			field.fieldName = "TotalValue";
			field.foreignKey = 0;
			field.currencyFormat = "1";
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.fieldType = ENFieldType.Currency;
			field.lusFid = 0;
			field.label = "Total Value";
			field.units = "";
			field.decimalPlaces = 0;
			field.carryChoices = true;
			field.currencySymbol = "$";
			field.findEnabled = false;
			field.formula = "";
			_TotalValueInfo = new CurrencyField(field);
			_fieldInfo.addItem(_TotalValueInfo);

			field = new FieldDescriptor();
			field.fid = 31;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.URL;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Sections";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.appearsAs = "Sections";
			field.fieldName = "Sections";
			field.required = false;
			field.formula = "\"https://workplace.intuit.com/db/be9nwdiyu?a=q&qt=tab&dvqid=1&clist=30.31.6.7.9.10.19.11.13&slist=30.31.6&query={Related Facility.ex.'\" & [Record ID#] & \"'}&opts=so-AAA.gb-XXX.\"";
			field.foreignKey = 0;
			field.findEnabled = true;
			_SectionsInfo = new URLField(field);
			_fieldInfo.addItem(_SectionsInfo);

			field = new FieldDescriptor();
			field.fid = 29;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.commaStart = 0;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Related Client";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = 0;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Facilities";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.fieldName = "RelatedClient";
			field.required = true;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_RelatedClientInfo = new NumberField(field);
			_fieldInfo.addItem(_RelatedClientInfo);

			field = new FieldDescriptor();
			field.fid = 32;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.URL;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Add Section";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.appearsAs = "Add  Section";
			field.fieldName = "AddSection";
			field.required = false;
			field.formula = "URLRoot() & \"db/\" & [_DBID_SECTIONS] & \"?a=API_GenAddRecordForm&_fid_29=\" & URLEncode ([Record ID#])& \"&z=\" & Rurl()";
			field.foreignKey = 0;
			field.findEnabled = false;
			_AddSectionInfo = new URLField(field);
			_fieldInfo.addItem(_AddSectionInfo);

			field = new FieldDescriptor();
			field.fid = 57;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.URL;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Add Document";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.appearsAs = "Add  Document";
			field.fieldName = "AddDocument";
			field.required = false;
			field.formula = "URLRoot() & \"db/\" & [_DBID_FACILITY_ATTACHMENTS] & \"?a=API_GenAddRecordForm&_fid_12=\" & URLEncode ([Record ID#])& \"&z=\" & Rurl()";
			field.foreignKey = 0;
			field.findEnabled = false;
			_AddDocumentInfo = new URLField(field);
			_fieldInfo.addItem(_AddDocumentInfo);

			field = new FieldDescriptor();
			field.fid = 56;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.sourceFID = 3;
			field.unique = false;
			field.fieldType = ENFieldType.DbLink;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.targetFID = 12;
			field.targetDBID = "be9nwdizs";
			field.label = "Documents";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.coverText = "Facility Documents";
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.exact = true;
			field.role = ENRole.NotFound;
			field.fieldName = "Documents";
			field.required = false;
			field.foreignKey = 0;
			field.findEnabled = true;
			_DocumentsInfo = new DbLinkField(field);
			_fieldInfo.addItem(_DocumentsInfo);

			field = new FieldDescriptor();
			field.fid = 7;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 20;
			field.lusFid = 0;
			field.label = "Brief Name";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "BriefName";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_BriefNameInfo = new TextField(field);
			_fieldInfo.addItem(_BriefNameInfo);

			field = new FieldDescriptor();
			field.fid = 8;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.File;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Photo";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "Photo";
			field.required = false;
			field.maxVersions = 3;
			field.foreignKey = 0;
			field.findEnabled = true;
			_PhotoInfo = new FileField(field);
			_fieldInfo.addItem(_PhotoInfo);

			field = new FieldDescriptor();
			field.fid = 45;
			field.lutFid = 0;
			field.numLines = 1;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Photo Name";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "PhotoName";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_PhotoNameInfo = new TextField(field);
			_fieldInfo.addItem(_PhotoNameInfo);

			field = new FieldDescriptor();
			field.fid = 12;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 20;
			field.lusFid = 0;
			field.label = "Province";
			field.allowNewChoices = true;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "Province";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_ProvinceInfo = new ChoiceField(field);
			_fieldInfo.addItem(_ProvinceInfo);

			field = new FieldDescriptor();
			field.fid = 13;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Country";
			field.allowNewChoices = true;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "Country";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_CountryInfo = new ChoiceField(field);
			_fieldInfo.addItem(_CountryInfo);

			field = new FieldDescriptor();
			field.fid = 14;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 20;
			field.lusFid = 0;
			field.label = "Postal Code";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "PostalCode";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_PostalCodeInfo = new TextField(field);
			_fieldInfo.addItem(_PostalCodeInfo);

			field = new FieldDescriptor();
			field.fid = 15;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Type of Building";
			field.allowNewChoices = true;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "TypeOfBuilding";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_TypeOfBuildingInfo = new ChoiceField(field);
			_fieldInfo.addItem(_TypeOfBuildingInfo);

			field = new FieldDescriptor();
			field.fid = 16;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Neighbourhood";
			field.allowNewChoices = true;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "Neighbourhood";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_NeighbourhoodInfo = new ChoiceField(field);
			_fieldInfo.addItem(_NeighbourhoodInfo);

			field = new FieldDescriptor();
			field.fid = 17;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Primary Contact";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "PrimaryContact";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_PrimaryContactInfo = new TextField(field);
			_fieldInfo.addItem(_PrimaryContactInfo);

			field = new FieldDescriptor();
			field.fid = 19;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = true;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Position";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "Position";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_PositionInfo = new TextField(field);
			_fieldInfo.addItem(_PositionInfo);

			field = new FieldDescriptor();
			field.fid = 20;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.fieldType = ENFieldType.Phone;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Phone";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.hasExtension = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "Phone";
			field.required = false;
			field.foreignKey = 0;
			field.findEnabled = true;
			_PhoneInfo = new PhoneField(field);
			_fieldInfo.addItem(_PhoneInfo);

			field = new FieldDescriptor();
			field.fid = 21;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.fieldType = ENFieldType.Phone;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Cell";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.hasExtension = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "Cell";
			field.required = false;
			field.foreignKey = 0;
			field.findEnabled = true;
			_CellInfo = new PhoneField(field);
			_fieldInfo.addItem(_CellInfo);

			field = new FieldDescriptor();
			field.fid = 22;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.fieldType = ENFieldType.Phone;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Fax";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.hasExtension = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "Fax";
			field.required = false;
			field.foreignKey = 0;
			field.findEnabled = true;
			_FaxInfo = new PhoneField(field);
			_fieldInfo.addItem(_FaxInfo);

			field = new FieldDescriptor();
			field.fid = 23;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.fieldType = ENFieldType.Email;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "EMail";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "EMail";
			field.required = false;
			field.foreignKey = 0;
			field.findEnabled = true;
			_EMailInfo = new EmailField(field);
			_fieldInfo.addItem(_EMailInfo);

			field = new FieldDescriptor();
			field.fid = 24;
			field.lutFid = 0;
			field.numLines = 3;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 80;
			field.lusFid = 0;
			field.label = "Additional Contacts";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "AdditionalContacts";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_AdditionalContactsInfo = new TextField(field);
			_fieldInfo.addItem(_AdditionalContactsInfo);

			field = new FieldDescriptor();
			field.fid = 53;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Fiscal Year End";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "FiscalYearEnd";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_FiscalYearEndInfo = new TextField(field);
			_fieldInfo.addItem(_FiscalYearEndInfo);

			field = new FieldDescriptor();
			field.fid = 25;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Budget Deadline";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "BudgetDeadline";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_BudgetDeadlineInfo = new TextField(field);
			_fieldInfo.addItem(_BudgetDeadlineInfo);

			field = new FieldDescriptor();
			field.fid = 26;
			field.lutFid = 0;
			field.numLines = 3;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 80;
			field.lusFid = 0;
			field.label = "Budget Notes";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "BudgetNotes";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_BudgetNotesInfo = new TextField(field);
			_fieldInfo.addItem(_BudgetNotesInfo);

			field = new FieldDescriptor();
			field.fid = 27;
			field.lutFid = 0;
			field.numLines = 3;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 80;
			field.lusFid = 0;
			field.label = "Facility Standards";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "FacilityStandards";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_FacilityStandardsInfo = new TextField(field);
			_fieldInfo.addItem(_FacilityStandardsInfo);

			field = new FieldDescriptor();
			field.fid = 47;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.fieldType = ENFieldType.CheckBox;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Leaking";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Boolean;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "Leaking";
			field.required = false;
			field.foreignKey = 0;
			field.findEnabled = true;
			_LeakingInfo = new BooleanField(field);
			_fieldInfo.addItem(_LeakingInfo);

			field = new FieldDescriptor();
			field.fid = 46;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.File;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Keyplan";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "Keyplan";
			field.required = false;
			field.maxVersions = 3;
			field.foreignKey = 0;
			field.findEnabled = true;
			_KeyplanInfo = new FileField(field);
			_fieldInfo.addItem(_KeyplanInfo);

			field = new FieldDescriptor();
			field.fid = 60;
			field.lutFid = 0;
			field.numLines = 1;
			field.doesDataCopy = false;
			field.unique = false;
			field.allowHTML = true;
			field.appendOnly = true;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Keyplan Name";
			field.allowNewChoices = true;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "KeyplanName";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_KeyplanNameInfo = new TextField(field);
			_fieldInfo.addItem(_KeyplanNameInfo);

			field = new FieldDescriptor();
			field.fid = 48;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "X1";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = 0;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Facilities";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.fieldName = "X1";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_X1Info = new NumberField(field);
			_fieldInfo.addItem(_X1Info);

			field = new FieldDescriptor();
			field.fid = 49;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Y1";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = 0;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Facilities";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.fieldName = "Y1";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_Y1Info = new NumberField(field);
			_fieldInfo.addItem(_Y1Info);

			field = new FieldDescriptor();
			field.fid = 50;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "X2";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = -1;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Facilities";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.fieldName = "X2";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_X2Info = new NumberField(field);
			_fieldInfo.addItem(_X2Info);

			field = new FieldDescriptor();
			field.fid = 51;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Y2";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = -1;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Facilities";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.fieldName = "Y2";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_Y2Info = new NumberField(field);
			_fieldInfo.addItem(_Y2Info);

			field = new FieldDescriptor();
			field.fid = 61;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.File;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Drawing";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "Drawing";
			field.required = false;
			field.maxVersions = 3;
			field.foreignKey = 0;
			field.findEnabled = true;
			_DrawingInfo = new FileField(field);
			_fieldInfo.addItem(_DrawingInfo);

			field = new FieldDescriptor();
			field.fid = 52;
			field.lutFid = 0;
			field.numLines = 1;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Drawing Name";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "DrawingName";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_DrawingNameInfo = new TextField(field);
			_fieldInfo.addItem(_DrawingNameInfo);

			field = new FieldDescriptor();
			field.fid = 28;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Notes";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "Notes";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_NotesInfo = new TextField(field);
			_fieldInfo.addItem(_NotesInfo);

			field = new FieldDescriptor();
			field.fid = 63;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.sourceFID = 3;
			field.unique = false;
			field.fieldType = ENFieldType.DbLink;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.targetFID = 6;
			field.targetDBID = "be9nwdi3n";
			field.label = "Facility Users";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.coverText = "Facility Users";
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.exact = true;
			field.role = ENRole.NotFound;
			field.fieldName = "FacilityUsers";
			field.required = false;
			field.foreignKey = 0;
			field.findEnabled = true;
			_FacilityUsersInfo = new DbLinkField(field);
			_fieldInfo.addItem(_FacilityUsersInfo);

			field = new FieldDescriptor();
			field.fid = 64;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.URL;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Add Facility User";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.appearsAs = "Add  Facility User";
			field.fieldName = "AddFacilityUser";
			field.required = false;
			field.formula = "URLRoot() & \"db/\" & [_DBID_FACILITY_USERS] & \"?a=API_GenAddRecordForm&_fid_6=\" & URLEncode ([Record ID#])& \"&z=\" & Rurl()";
			field.foreignKey = 0;
			field.findEnabled = false;
			_AddFacilityUserInfo = new URLField(field);
			_fieldInfo.addItem(_AddFacilityUserInfo);

			field = new FieldDescriptor();
			field.fid = 65;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.allowHTML = true;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Photo Thumbnail";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "PhotoThumbnail";
			field.required = false;
			field.formula = "If ([Photo]=\"\",\"\",\"<a href='https://www.workplace.intuit.com/db/\" & Dbid() & \"/a/r\" & [Record ID#] & \"/e8/va/\" & [Photo] & \"' target=_blank>\"";
			field.foreignKey = 0;
			field.findEnabled = true;
			_PhotoThumbnailInfo = new TextField(field);
			_fieldInfo.addItem(_PhotoThumbnailInfo);

			field = new FieldDescriptor();
			field.fid = 66;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.allowHTML = true;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Keyplan Thumbnail";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "KeyplanThumbnail";
			field.required = false;
			field.formula = "If ([Keyplan]=\"\",\"\",\"<a href='https://www.quickbase.com/up/\" & Dbid() & \"/a/r\" & [Record ID#] & \"/e46/va/\" & [Keyplan] & \"' target=_blank>\"";
			field.foreignKey = 0;
			field.findEnabled = true;
			_KeyplanThumbnailInfo = new TextField(field);
			_fieldInfo.addItem(_KeyplanThumbnailInfo);

			field = new FieldDescriptor();
			field.fid = 68;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Allowed Facility User";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = -1;
			field.mode = ENMode.Summary;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Facilities";
			field.blankIsZero = false;
			field.role = ENRole.NotFound;
			field.fieldName = "AllowedFacilityUser";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = false;
			_AllowedFacilityUserInfo = new NumberField(field);
			_fieldInfo.addItem(_AllowedFacilityUserInfo);

			field = new FieldDescriptor();
			field.fid = 69;
			field.lutFid = 53;
			field.doesDataCopy = false;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 29;
			field.label = "Allowed Client User";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = -1;
			field.mode = ENMode.Lookup;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Facilities";
			field.blankIsZero = false;
			field.role = ENRole.NotFound;
			field.fieldName = "AllowedClientUser";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_AllowedClientUserInfo = new NumberField(field);
			_fieldInfo.addItem(_AllowedClientUserInfo);

			field = new FieldDescriptor();
			field.fid = 71;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Allowed User";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = -1;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Facilities";
			field.blankIsZero = false;
			field.role = ENRole.NotFound;
			field.fieldName = "AllowedUser";
			field.required = false;
			field.formula = "[Allowed Client User] + [Allowed Facility User]";
			field.foreignKey = 0;
			field.findEnabled = true;
			_AllowedUserInfo = new NumberField(field);
			_fieldInfo.addItem(_AllowedUserInfo);

			field = new FieldDescriptor();
			field.fid = 72;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Old FacilityID";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = -1;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Facilities";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.fieldName = "OldFacilityid";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_OldFacilityidInfo = new NumberField(field);
			_fieldInfo.addItem(_OldFacilityidInfo);

			field = new FieldDescriptor();
			field.fid = 73;
			field.lutFid = 0;
			field.numLines = 1;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 20;
			field.lusFid = 0;
			field.label = "MapLatLong";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "MapLatLong";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_MapLatLongInfo = new TextField(field);
			_fieldInfo.addItem(_MapLatLongInfo);

			field = new FieldDescriptor();
			field.fid = 75;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "MapZoom";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = -1;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Facilities";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.fieldName = "MapZoom";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_MapZoomInfo = new NumberField(field);
			_fieldInfo.addItem(_MapZoomInfo);

			field = new FieldDescriptor();
			field.fid = 78;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "SitePlanZoom";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = -1;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Facilities";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.fieldName = "SitePlanZoom";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_SitePlanZoomInfo = new NumberField(field);
			_fieldInfo.addItem(_SitePlanZoomInfo);

			field = new FieldDescriptor();
			field.fid = 84;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.allowHTML = true;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Drawing Thumbnail";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "DrawingThumbnail";
			field.required = false;
			field.formula = "If ([Drawing]=\"\",\"\",\"<a href='https://www.quickbase.com/up/\" & Dbid() & \"/a/r\" & [Record ID#] & \"/e61/va/\" & [Drawing] & \"' target=_blank>\"";
			field.foreignKey = 0;
			field.findEnabled = true;
			_DrawingThumbnailInfo = new TextField(field);
			_fieldInfo.addItem(_DrawingThumbnailInfo);

			field = new FieldDescriptor();
			field.fid = 85;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Address Lat";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = -1;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Facilities";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.fieldName = "AddressLat";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_AddressLatInfo = new NumberField(field);
			_fieldInfo.addItem(_AddressLatInfo);

			field = new FieldDescriptor();
			field.fid = 86;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Address Long";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = -1;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Facilities";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.fieldName = "AddressLong";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_AddressLongInfo = new NumberField(field);
			_fieldInfo.addItem(_AddressLongInfo);

			field = new FieldDescriptor();
			field.fid = 87;
			field.lutFid = 0;
			field.numLines = 1;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "IRPCoverPagePhotoFileName";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "IRPCoverPagePhotoFileName";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_IRPCoverPagePhotoFileNameInfo = new TextField(field);
			_fieldInfo.addItem(_IRPCoverPagePhotoFileNameInfo);

			field = new FieldDescriptor();
			field.fid = 88;
			field.lutFid = 0;
			field.numLines = 1;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "IRPKeyPlanFileName";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "IRPKeyPlanFileName";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_IRPKeyPlanFileNameInfo = new TextField(field);
			_fieldInfo.addItem(_IRPKeyPlanFileNameInfo);

			field = new FieldDescriptor();
			field.fid = 89;
			field.lutFid = 0;
			field.numLines = 1;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "IRPDrawingFileName";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "IRPDrawingFileName";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_IRPDrawingFileNameInfo = new TextField(field);
			_fieldInfo.addItem(_IRPDrawingFileNameInfo);

			field = new FieldDescriptor();
			field.fid = 90;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "QB Maps URL";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "QBMapsUrl";
			field.required = false;
			field.formula = "URLRoot() & \"db/\" & [_DBID_FACILITIES] & \"?a=dr&rid=\"";
			field.foreignKey = 0;
			field.findEnabled = true;
			_QBMapsUrlInfo = new TextField(field);
			_fieldInfo.addItem(_QBMapsUrlInfo);

			field = new FieldDescriptor();
			field.fid = 91;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "QB Maps Marker";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "QBMapsMarker";
			field.required = false;
			field.formula = "\"F-Blue\"";
			field.foreignKey = 0;
			field.findEnabled = true;
			_QBMapsMarkerInfo = new TextField(field);
			_fieldInfo.addItem(_QBMapsMarkerInfo);

			field = new FieldDescriptor();
			field.fid = 93;
			field.lutFid = 0;
			field.numLines = 1;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "QB Address";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "QBAddress";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_QBAddressInfo = new TextField(field);
			_fieldInfo.addItem(_QBAddressInfo);

			field = new FieldDescriptor();
			field.fid = 94;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.URL;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Site Plan";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.appearsAs = "Site Plan";
			field.fieldName = "SitePlan";
			field.required = false;
			field.formula = "\"http://www.quickbaseutilities.com/Maybee/QBMaps/default.aspx?\"";
			field.foreignKey = 0;
			field.findEnabled = true;
			_SitePlanInfo = new URLField(field);
			_fieldInfo.addItem(_SitePlanInfo);

			field = new FieldDescriptor();
			field.fid = 95;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "\"<a href=http://www.quickbaseutilities.com/Maybee/QBMaps/default.aspx?\"";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Map2";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "Map2";
			field.required = false;
			field.formula = "\"<a href=http://www.ibm.com>Map11111111111</a>&nbsp;<a href=http://www.quickbase.com>QB2222222222222</a>&nbsp;<a href=http://www.quickbase.com>QB333333333</a>&nbsp;<a href=http://www.quickbase.com>QB444444444444442</a>&nbsp;<a href=http://www.quickbase.com>QB55555555</a>\"";
			field.foreignKey = 0;
			field.findEnabled = true;
			_Map2Info = new TextField(field);
			_fieldInfo.addItem(_Map2Info);

			field = new FieldDescriptor();
			field.fid = 96;
			field.lutFid = 0;
			field.numLines = 1;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "SitePlanLatLong";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.NotFound;
			field.fieldName = "SitePlanLatLong";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_SitePlanLatLongInfo = new TextField(field);
			_fieldInfo.addItem(_SitePlanLatLongInfo);

			field = new FieldDescriptor();
			field.fid = 1;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.TimeStamp;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Date Created";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Int64;
			field.tableName = "Facilities";
			field.role = ENRole.Created;
			field.fieldName = "DateCreated";
			field.required = false;
			field.foreignKey = 0;
			field.findEnabled = false;
			_DateCreatedInfo = new TimeStampField(field);
			_fieldInfo.addItem(_DateCreatedInfo);

			field = new FieldDescriptor();
			field.fid = 2;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.TimeStamp;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Date Modified";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Int64;
			field.tableName = "Facilities";
			field.role = ENRole.Modifed;
			field.fieldName = "DateModified";
			field.required = false;
			field.foreignKey = 0;
			field.findEnabled = false;
			_DateModifiedInfo = new TimeStampField(field);
			_fieldInfo.addItem(_DateModifiedInfo);

			field = new FieldDescriptor();
			field.fid = 4;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.UserId;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Record Owner";
			field.allowNewChoices = true;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.Owner;
			field.fieldName = "RecordOwner";
			field.required = false;
			field.foreignKey = 0;
			field.findEnabled = true;
			_RecordOwnerInfo = new UserIdField(field);
			_fieldInfo.addItem(_RecordOwnerInfo);

			field = new FieldDescriptor();
			field.fid = 5;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.UserId;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Last Modified By";
			field.allowNewChoices = true;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Facilities";
			field.role = ENRole.Modifier;
			field.fieldName = "LastModifiedBy";
			field.required = false;
			field.foreignKey = 0;
			field.findEnabled = true;
			_LastModifiedByInfo = new UserIdField(field);
			_fieldInfo.addItem(_LastModifiedByInfo);

		}

		public static function getInstance():Facilities_Info
		{
			if(_instance == null)
				_instance = new Facilities_Info(new Private);
			return _instance;
		}

		public function get tableName():String
		{
			return "Facilities";
		}

		public function get isMSATable():Boolean
		{
			return false;
		}

		public function getFieldInfo(name:String):AbstractField
		{
			return this[name + "_Info"];
		}

		// MetaData Information Objects
		private var _AddressMapInfo:URLField;
		private var _SiteMapInfo:URLField;
		private var _ClientInfo:TextField;
		private var _FacilityNameInfo:TextField;
		private var _AddressInfo:TextField;
		private var _CityInfo:TextField;
		private var _SectionsCountInfo:NumberField;
		private var _TotalSqFtInfo:NumberField;
		private var _TotalValueInfo:CurrencyField;
		private var _SectionsInfo:URLField;
		private var _RelatedClientInfo:NumberField;
		private var _AddSectionInfo:URLField;
		private var _AddDocumentInfo:URLField;
		private var _DocumentsInfo:DbLinkField;
		private var _BriefNameInfo:TextField;
		private var _PhotoInfo:FileField;
		private var _PhotoNameInfo:TextField;
		private var _ProvinceInfo:ChoiceField;
		private var _CountryInfo:ChoiceField;
		private var _PostalCodeInfo:TextField;
		private var _TypeOfBuildingInfo:ChoiceField;
		private var _NeighbourhoodInfo:ChoiceField;
		private var _PrimaryContactInfo:TextField;
		private var _PositionInfo:TextField;
		private var _PhoneInfo:PhoneField;
		private var _CellInfo:PhoneField;
		private var _FaxInfo:PhoneField;
		private var _EMailInfo:EmailField;
		private var _AdditionalContactsInfo:TextField;
		private var _FiscalYearEndInfo:TextField;
		private var _BudgetDeadlineInfo:TextField;
		private var _BudgetNotesInfo:TextField;
		private var _FacilityStandardsInfo:TextField;
		private var _LeakingInfo:BooleanField;
		private var _KeyplanInfo:FileField;
		private var _KeyplanNameInfo:TextField;
		private var _X1Info:NumberField;
		private var _Y1Info:NumberField;
		private var _X2Info:NumberField;
		private var _Y2Info:NumberField;
		private var _DrawingInfo:FileField;
		private var _DrawingNameInfo:TextField;
		private var _NotesInfo:TextField;
		private var _FacilityUsersInfo:DbLinkField;
		private var _AddFacilityUserInfo:URLField;
		private var _PhotoThumbnailInfo:TextField;
		private var _KeyplanThumbnailInfo:TextField;
		private var _AllowedFacilityUserInfo:NumberField;
		private var _AllowedClientUserInfo:NumberField;
		private var _AllowedUserInfo:NumberField;
		private var _OldFacilityidInfo:NumberField;
		private var _MapLatLongInfo:TextField;
		private var _MapZoomInfo:NumberField;
		private var _SitePlanZoomInfo:NumberField;
		private var _DrawingThumbnailInfo:TextField;
		private var _AddressLatInfo:NumberField;
		private var _AddressLongInfo:NumberField;
		private var _IRPCoverPagePhotoFileNameInfo:TextField;
		private var _IRPKeyPlanFileNameInfo:TextField;
		private var _IRPDrawingFileNameInfo:TextField;
		private var _QBMapsUrlInfo:TextField;
		private var _QBMapsMarkerInfo:TextField;
		private var _QBAddressInfo:TextField;
		private var _SitePlanInfo:URLField;
		private var _Map2Info:TextField;
		private var _SitePlanLatLongInfo:TextField;
		private var _DateCreatedInfo:TimeStampField;
		private var _DateModifiedInfo:TimeStampField;
		private var _RecordOwnerInfo:UserIdField;
		private var _LastModifiedByInfo:UserIdField;

		// MetaData Information Objects getters
		public function get AddressMap_Info():URLField					{return _AddressMapInfo;}
		public function get SiteMap_Info():URLField						{return _SiteMapInfo;}
		public function get Client_Info():TextField						{return _ClientInfo;}
		public function get FacilityName_Info():TextField				{return _FacilityNameInfo;}
		public function get Address_Info():TextField					{return _AddressInfo;}
		public function get City_Info():TextField						{return _CityInfo;}
		public function get SectionsCount_Info():NumberField			{return _SectionsCountInfo;}
		public function get TotalSqFt_Info():NumberField				{return _TotalSqFtInfo;}
		public function get TotalValue_Info():CurrencyField				{return _TotalValueInfo;}
		public function get Sections_Info():URLField					{return _SectionsInfo;}
		public function get RelatedClient_Info():NumberField			{return _RelatedClientInfo;}
		public function get AddSection_Info():URLField					{return _AddSectionInfo;}
		public function get AddDocument_Info():URLField					{return _AddDocumentInfo;}
		public function get Documents_Info():DbLinkField				{return _DocumentsInfo;}
		public function get BriefName_Info():TextField					{return _BriefNameInfo;}
		public function get Photo_Info():FileField						{return _PhotoInfo;}
		public function get PhotoName_Info():TextField					{return _PhotoNameInfo;}
		public function get Province_Info():ChoiceField					{return _ProvinceInfo;}
		public function get Country_Info():ChoiceField					{return _CountryInfo;}
		public function get PostalCode_Info():TextField					{return _PostalCodeInfo;}
		public function get TypeOfBuilding_Info():ChoiceField			{return _TypeOfBuildingInfo;}
		public function get Neighbourhood_Info():ChoiceField			{return _NeighbourhoodInfo;}
		public function get PrimaryContact_Info():TextField				{return _PrimaryContactInfo;}
		public function get Position_Info():TextField					{return _PositionInfo;}
		public function get Phone_Info():PhoneField						{return _PhoneInfo;}
		public function get Cell_Info():PhoneField						{return _CellInfo;}
		public function get Fax_Info():PhoneField						{return _FaxInfo;}
		public function get EMail_Info():EmailField						{return _EMailInfo;}
		public function get AdditionalContacts_Info():TextField			{return _AdditionalContactsInfo;}
		public function get FiscalYearEnd_Info():TextField				{return _FiscalYearEndInfo;}
		public function get BudgetDeadline_Info():TextField				{return _BudgetDeadlineInfo;}
		public function get BudgetNotes_Info():TextField				{return _BudgetNotesInfo;}
		public function get FacilityStandards_Info():TextField			{return _FacilityStandardsInfo;}
		public function get Leaking_Info():BooleanField					{return _LeakingInfo;}
		public function get Keyplan_Info():FileField					{return _KeyplanInfo;}
		public function get KeyplanName_Info():TextField				{return _KeyplanNameInfo;}
		public function get X1_Info():NumberField						{return _X1Info;}
		public function get Y1_Info():NumberField						{return _Y1Info;}
		public function get X2_Info():NumberField						{return _X2Info;}
		public function get Y2_Info():NumberField						{return _Y2Info;}
		public function get Drawing_Info():FileField					{return _DrawingInfo;}
		public function get DrawingName_Info():TextField				{return _DrawingNameInfo;}
		public function get Notes_Info():TextField						{return _NotesInfo;}
		public function get FacilityUsers_Info():DbLinkField			{return _FacilityUsersInfo;}
		public function get AddFacilityUser_Info():URLField				{return _AddFacilityUserInfo;}
		public function get PhotoThumbnail_Info():TextField				{return _PhotoThumbnailInfo;}
		public function get KeyplanThumbnail_Info():TextField			{return _KeyplanThumbnailInfo;}
		public function get AllowedFacilityUser_Info():NumberField		{return _AllowedFacilityUserInfo;}
		public function get AllowedClientUser_Info():NumberField		{return _AllowedClientUserInfo;}
		public function get AllowedUser_Info():NumberField				{return _AllowedUserInfo;}
		public function get OldFacilityid_Info():NumberField			{return _OldFacilityidInfo;}
		public function get MapLatLong_Info():TextField					{return _MapLatLongInfo;}
		public function get MapZoom_Info():NumberField					{return _MapZoomInfo;}
		public function get SitePlanZoom_Info():NumberField				{return _SitePlanZoomInfo;}
		public function get DrawingThumbnail_Info():TextField			{return _DrawingThumbnailInfo;}
		public function get AddressLat_Info():NumberField				{return _AddressLatInfo;}
		public function get AddressLong_Info():NumberField				{return _AddressLongInfo;}
		public function get IRPCoverPagePhotoFileName_Info():TextField	{return _IRPCoverPagePhotoFileNameInfo;}
		public function get IRPKeyPlanFileName_Info():TextField			{return _IRPKeyPlanFileNameInfo;}
		public function get IRPDrawingFileName_Info():TextField			{return _IRPDrawingFileNameInfo;}
		public function get QBMapsUrl_Info():TextField					{return _QBMapsUrlInfo;}
		public function get QBMapsMarker_Info():TextField				{return _QBMapsMarkerInfo;}
		public function get QBAddress_Info():TextField					{return _QBAddressInfo;}
		public function get SitePlan_Info():URLField					{return _SitePlanInfo;}
		public function get Map2_Info():TextField						{return _Map2Info;}
		public function get SitePlanLatLong_Info():TextField			{return _SitePlanLatLongInfo;}
		public function get DateCreated_Info():TimeStampField			{return _DateCreatedInfo;}
		public function get DateModified_Info():TimeStampField			{return _DateModifiedInfo;}
		public function get RecordOwner_Info():UserIdField				{return _RecordOwnerInfo;}
		public function get LastModifiedBy_Info():UserIdField			{return _LastModifiedByInfo;}

		// Field getter variables
		private var _fieldNames:ArrayCollection = new ArrayCollection(["AddressMap", "SiteMap", "Client", "FacilityName", "Address", 
																		"City", "SectionsCount", "TotalSqFt", "TotalValue", "Sections", "RelatedClient", "AddSection", "AddDocument", 
																		"Documents", "BriefName", "Photo", "PhotoName", "Province", "Country", "PostalCode", "TypeOfBuilding", 
																		"Neighbourhood", "PrimaryContact", "Position", "Phone", "Cell", "Fax", "EMail", "AdditionalContacts", "FiscalYearEnd", 
																		"BudgetDeadline", "BudgetNotes", "FacilityStandards", "Leaking", "Keyplan", "KeyplanName", "X1", "Y1", "X2", 
																		"Y2", "Drawing", "DrawingName", "Notes", "FacilityUsers", "AddFacilityUser", "PhotoThumbnail", "KeyplanThumbnail", 
																		"AllowedFacilityUser", "AllowedClientUser", "AllowedUser", "OldFacilityid", "MapLatLong", "MapZoom", 
																		"SitePlanZoom", "DrawingThumbnail", "AddressLat", "AddressLong", "IRPCoverPagePhotoFileName", "IRPKeyPlanFileName", 
																		"IRPDrawingFileName", "QBMapsUrl", "QBMapsMarker", "QBAddress", "SitePlan", "Map2", "SitePlanLatLong", 
																		"DateCreated", "DateModified", "RecordOwner", "LastModifiedBy", ]);
		private var _fieldInfo:ArrayCollection = new ArrayCollection();

		// Field getters
		public function get FieldNames():ArrayCollection				{return _fieldNames;}
		public function get FieldsInfo():ArrayCollection				{return _fieldInfo;}
	}
}

class Private{}
