package com.ebs.eroof.dto
{
	import com.adobe.cairngorm.vo.IValueObject;
	import com.quickbase.idn.dto.IKingussieInfo;
	import com.quickbase.idn.fieldtypes.*;
	import com.quickbase.idn.fieldtypes.bool.*;
	import com.quickbase.idn.fieldtypes.float.*;
	import com.quickbase.idn.fieldtypes.int32.*;
	import com.quickbase.idn.fieldtypes.int64.*;
	import com.quickbase.idn.fieldtypes.text.*;
	import mx.collections.ArrayCollection;

	public class Sections_Info implements IKingussieInfo
	{
		// Important Note:
		//    This class was automatically generated.  If you make changes to it and
		//    subsequently run the generator tool again, all changes will be overwritten!

		private static var _instance:Sections_Info = null;

		function Sections_Info(forcePrivateClass:Private)
		{
			// MetaData Initializers
			var field:FieldDescriptor;

			field = new FieldDescriptor();
			field.fid = 30;
			field.lutFid = 30;
			field.numLines = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 29;
			field.label = "Client";
			field.allowNewChoices = false;
			field.mode = ENMode.Lookup;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "Client";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_ClientInfo = new TextField(field);
			_fieldInfo.addItem(_ClientInfo);

			field = new FieldDescriptor();
			field.fid = 31;
			field.lutFid = 6;
			field.numLines = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 29;
			field.label = "Facility";
			field.allowNewChoices = false;
			field.mode = ENMode.Lookup;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "Facility";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_FacilityInfo = new TextField(field);
			_fieldInfo.addItem(_FacilityInfo);

			field = new FieldDescriptor();
			field.fid = 6;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 10;
			field.lusFid = 0;
			field.label = "Designation";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "Designation";
			field.required = true;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_DesignationInfo = new TextField(field);
			_fieldInfo.addItem(_DesignationInfo);

			field = new FieldDescriptor();
			field.fid = 7;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Roof Name";
			field.allowNewChoices = true;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "RoofName";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_RoofNameInfo = new ChoiceField(field);
			_fieldInfo.addItem(_RoofNameInfo);

			field = new FieldDescriptor();
			field.fid = 9;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Roof System";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "RoofSystem";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_RoofSystemInfo = new ChoiceField(field);
			_fieldInfo.addItem(_RoofSystemInfo);

			field = new FieldDescriptor();
			field.fid = 10;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Age";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = -1;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Sections";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.fieldName = "Age";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_AgeInfo = new NumberField(field);
			_fieldInfo.addItem(_AgeInfo);

			field = new FieldDescriptor();
			field.fid = 19;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 20;
			field.lusFid = 0;
			field.label = "Condition Index";
			field.allowNewChoices = true;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "ConditionIndex";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_ConditionIndexInfo = new ChoiceField(field);
			_fieldInfo.addItem(_ConditionIndexInfo);

			field = new FieldDescriptor();
			field.fid = 11;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Sq Ft";
			field.allowNewChoices = false;
			field.units = "Sq Ft";
			field.decimalPlaces = 0;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Sections";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.fieldName = "SqFt";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_SqFtInfo = new NumberField(field);
			_fieldInfo.addItem(_SqFtInfo);

			field = new FieldDescriptor();
			field.fid = 13;
			field.unique = false;
			field.commaStart = 4;
			field.fieldHelp = "";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.baseType = ENBaseType.Float;
			field.tableName = "Sections";
			field.blankIsZero = false;
			field.role = ENRole.NotFound;
			field.required = false;
			field.fieldName = "EstCost";
			field.foreignKey = 0;
			field.currencyFormat = "1";
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.fieldType = ENFieldType.Currency;
			field.lusFid = 0;
			field.label = "Est Cost";
			field.units = "";
			field.decimalPlaces = 0;
			field.carryChoices = true;
			field.currencySymbol = "$";
			field.findEnabled = true;
			field.formula = "[Sq Ft] * [Est Cost per Sq Ft]";
			_EstCostInfo = new CurrencyField(field);
			_fieldInfo.addItem(_EstCostInfo);

			field = new FieldDescriptor();
			field.fid = 29;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.commaStart = 0;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Related Facility";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = 0;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Sections";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.fieldName = "RelatedFacility";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_RelatedFacilityInfo = new NumberField(field);
			_fieldInfo.addItem(_RelatedFacilityInfo);

			field = new FieldDescriptor();
			field.fid = 33;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.URL;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Add Layer";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.appearsAs = "Add  Composition";
			field.fieldName = "AddLayer";
			field.required = false;
			field.formula = "URLRoot() & \"db/\" & [_DBID_LAYERS] & \"?a=API_GenAddRecordForm&_fid_10=\" & URLEncode ([Record ID#])& \"&z=\" & Rurl()";
			field.foreignKey = 0;
			field.findEnabled = false;
			_AddLayerInfo = new URLField(field);
			_fieldInfo.addItem(_AddLayerInfo);

			field = new FieldDescriptor();
			field.fid = 32;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.sourceFID = 3;
			field.unique = false;
			field.fieldType = ENFieldType.DbLink;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.targetFID = 10;
			field.targetDBID = "be9nwdizu";
			field.label = "Layers";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.coverText = "Layers";
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.exact = true;
			field.role = ENRole.NotFound;
			field.fieldName = "Layers";
			field.required = false;
			field.foreignKey = 0;
			field.findEnabled = true;
			_LayersInfo = new DbLinkField(field);
			_fieldInfo.addItem(_LayersInfo);

			field = new FieldDescriptor();
			field.fid = 68;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.URL;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Add Core Photo";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.appearsAs = "Add  Core Photo";
			field.fieldName = "AddCorePhoto";
			field.required = false;
			field.formula = "URLRoot() & \"db/\" & [_DBID_CORE_PHOTOS] & \"?a=API_GenAddRecordForm&_fid_10=\" & URLEncode ([Record ID#])& \"&z=\" & Rurl()";
			field.foreignKey = 0;
			field.findEnabled = false;
			_AddCorePhotoInfo = new URLField(field);
			_fieldInfo.addItem(_AddCorePhotoInfo);

			field = new FieldDescriptor();
			field.fid = 67;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.sourceFID = 3;
			field.unique = false;
			field.fieldType = ENFieldType.DbLink;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.targetFID = 10;
			field.targetDBID = "be9nwdizw";
			field.label = "Core Photos";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.coverText = "Core Photos";
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.exact = true;
			field.role = ENRole.NotFound;
			field.fieldName = "CorePhotos";
			field.required = false;
			field.foreignKey = 0;
			field.findEnabled = true;
			_CorePhotosInfo = new DbLinkField(field);
			_fieldInfo.addItem(_CorePhotosInfo);

			field = new FieldDescriptor();
			field.fid = 35;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.URL;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Add Detail";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.appearsAs = "Add  Detail";
			field.fieldName = "AddDetail";
			field.required = false;
			field.formula = "URLRoot() & \"db/\" & [_DBID_DETAILS] & \"?a=API_GenAddRecordForm&_fid_12=\" & URLEncode ([Record ID#])& \"&z=\" & Rurl()";
			field.foreignKey = 0;
			field.findEnabled = false;
			_AddDetailInfo = new URLField(field);
			_fieldInfo.addItem(_AddDetailInfo);

			field = new FieldDescriptor();
			field.fid = 34;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.sourceFID = 3;
			field.unique = false;
			field.fieldType = ENFieldType.DbLink;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.targetFID = 12;
			field.targetDBID = "be9nwdiz9";
			field.label = "Details";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.coverText = "Details";
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.exact = true;
			field.role = ENRole.NotFound;
			field.fieldName = "Details";
			field.required = false;
			field.foreignKey = 0;
			field.findEnabled = true;
			_DetailsInfo = new DbLinkField(field);
			_fieldInfo.addItem(_DetailsInfo);

			field = new FieldDescriptor();
			field.fid = 37;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.URL;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Add Defect";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.appearsAs = "Add  Defect";
			field.fieldName = "AddDefect";
			field.required = false;
			field.formula = "URLRoot() & \"db/\" & [_DBID_DEFECTS] & \"?a=API_GenAddRecordForm&_fid_11=\" & URLEncode ([Record ID#])& \"&z=\" & Rurl()";
			field.foreignKey = 0;
			field.findEnabled = false;
			_AddDefectInfo = new URLField(field);
			_fieldInfo.addItem(_AddDefectInfo);

			field = new FieldDescriptor();
			field.fid = 36;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.sourceFID = 3;
			field.unique = false;
			field.fieldType = ENFieldType.DbLink;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.targetFID = 11;
			field.targetDBID = "be9nwdi2b";
			field.label = "Defects";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.coverText = "Defects";
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.exact = true;
			field.role = ENRole.NotFound;
			field.fieldName = "Defects";
			field.required = false;
			field.foreignKey = 0;
			field.findEnabled = true;
			_DefectsInfo = new DbLinkField(field);
			_fieldInfo.addItem(_DefectsInfo);

			field = new FieldDescriptor();
			field.fid = 45;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.URL;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Add Inspection";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.appearsAs = "Add  Inspection";
			field.fieldName = "AddInspection";
			field.required = false;
			field.formula = "URLRoot() & \"db/\" & [_DBID_INSPECTIONS] & \"?a=API_GenAddRecordForm&_fid_11=\" & URLEncode ([Record ID#])& \"&z=\" & Rurl()";
			field.foreignKey = 0;
			field.findEnabled = false;
			_AddInspectionInfo = new URLField(field);
			_fieldInfo.addItem(_AddInspectionInfo);

			field = new FieldDescriptor();
			field.fid = 44;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.sourceFID = 3;
			field.unique = false;
			field.fieldType = ENFieldType.DbLink;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.targetFID = 11;
			field.targetDBID = "be9nwdi2d";
			field.label = "Inspections";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.coverText = "Inspections";
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.exact = true;
			field.role = ENRole.NotFound;
			field.fieldName = "Inspections";
			field.required = false;
			field.foreignKey = 0;
			field.findEnabled = true;
			_InspectionsInfo = new DbLinkField(field);
			_fieldInfo.addItem(_InspectionsInfo);

			field = new FieldDescriptor();
			field.fid = 70;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.URL;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Add Survey";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.appearsAs = "Add  Survey";
			field.fieldName = "AddSurvey";
			field.required = false;
			field.formula = "URLRoot() & \"db/\" & [_DBID_SURVEYS] & \"?a=API_GenAddRecordForm&_fid_14=\" & URLEncode ([Record ID#])& \"&z=\" & Rurl()";
			field.foreignKey = 0;
			field.findEnabled = false;
			_AddSurveyInfo = new URLField(field);
			_fieldInfo.addItem(_AddSurveyInfo);

			field = new FieldDescriptor();
			field.fid = 69;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.sourceFID = 3;
			field.unique = false;
			field.fieldType = ENFieldType.DbLink;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.targetFID = 14;
			field.targetDBID = "be9nwdi2q";
			field.label = "Surveys";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.coverText = "Surveys";
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.exact = true;
			field.role = ENRole.NotFound;
			field.fieldName = "Surveys";
			field.required = false;
			field.foreignKey = 0;
			field.findEnabled = true;
			_SurveysInfo = new DbLinkField(field);
			_fieldInfo.addItem(_SurveysInfo);

			field = new FieldDescriptor();
			field.fid = 39;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.URL;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Add Expenditure";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.appearsAs = "Add  Expenditure";
			field.fieldName = "AddExpenditure";
			field.required = false;
			field.formula = "URLRoot() & \"db/\" & [_DBID_BUDGETS] & \"?a=API_GenAddRecordForm&_fid_12=\" & URLEncode ([Record ID#])& \"&z=\" & Rurl()";
			field.foreignKey = 0;
			field.findEnabled = false;
			_AddExpenditureInfo = new URLField(field);
			_fieldInfo.addItem(_AddExpenditureInfo);

			field = new FieldDescriptor();
			field.fid = 38;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.sourceFID = 3;
			field.unique = false;
			field.fieldType = ENFieldType.DbLink;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.targetFID = 12;
			field.targetDBID = "be9nwdi2t";
			field.label = "Expenditures";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.coverText = "Expenditures";
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.exact = true;
			field.role = ENRole.NotFound;
			field.fieldName = "Expenditures";
			field.required = false;
			field.foreignKey = 0;
			field.findEnabled = true;
			_ExpendituresInfo = new DbLinkField(field);
			_fieldInfo.addItem(_ExpendituresInfo);

			field = new FieldDescriptor();
			field.fid = 43;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.URL;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Add Warranty";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.appearsAs = "Add  Warranty";
			field.fieldName = "AddWarranty";
			field.required = false;
			field.formula = "URLRoot() & \"db/\" & [_DBID_WARRANTIES] & \"?a=API_GenAddRecordForm&_fid_12=\" & URLEncode ([Record ID#])& \"&z=\" & Rurl()";
			field.foreignKey = 0;
			field.findEnabled = false;
			_AddWarrantyInfo = new URLField(field);
			_fieldInfo.addItem(_AddWarrantyInfo);

			field = new FieldDescriptor();
			field.fid = 42;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.sourceFID = 3;
			field.unique = false;
			field.fieldType = ENFieldType.DbLink;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.targetFID = 12;
			field.targetDBID = "be9nwdi2z";
			field.label = "Warranties";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.coverText = "Warranties";
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.exact = true;
			field.role = ENRole.NotFound;
			field.fieldName = "Warranties";
			field.required = false;
			field.foreignKey = 0;
			field.findEnabled = true;
			_WarrantiesInfo = new DbLinkField(field);
			_fieldInfo.addItem(_WarrantiesInfo);

			field = new FieldDescriptor();
			field.fid = 8;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.File;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Photo";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "Photo";
			field.required = false;
			field.maxVersions = 3;
			field.foreignKey = 0;
			field.findEnabled = true;
			_PhotoInfo = new FileField(field);
			_fieldInfo.addItem(_PhotoInfo);

			field = new FieldDescriptor();
			field.fid = 56;
			field.lutFid = 0;
			field.numLines = 1;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Photo Name";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "PhotoName";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_PhotoNameInfo = new TextField(field);
			_fieldInfo.addItem(_PhotoNameInfo);

			field = new FieldDescriptor();
			field.fid = 14;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Year Installed";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = 0;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Sections";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.fieldName = "YearInstalled";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_YearInstalledInfo = new NumberField(field);
			_fieldInfo.addItem(_YearInstalledInfo);

			field = new FieldDescriptor();
			field.fid = 15;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 20;
			field.lusFid = 0;
			field.label = "Year Installed Source";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "YearInstalledSource";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_YearInstalledSourceInfo = new ChoiceField(field);
			_fieldInfo.addItem(_YearInstalledSourceInfo);

			field = new FieldDescriptor();
			field.fid = 12;
			field.unique = false;
			field.commaStart = 3;
			field.fieldHelp = "";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.baseType = ENBaseType.Float;
			field.tableName = "Sections";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.required = false;
			field.fieldName = "EstCostPerSqFt";
			field.foreignKey = 0;
			field.currencyFormat = "1";
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.fieldType = ENFieldType.Currency;
			field.lusFid = 0;
			field.label = "Est Cost per Sq Ft";
			field.units = "";
			field.decimalPlaces = 2;
			field.carryChoices = true;
			field.currencySymbol = "$";
			field.findEnabled = true;
			field.formula = "";
			_EstCostPerSqFtInfo = new CurrencyField(field);
			_fieldInfo.addItem(_EstCostPerSqFtInfo);

			field = new FieldDescriptor();
			field.fid = 16;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Height";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = 0;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Sections";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.fieldName = "Height";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_HeightInfo = new NumberField(field);
			_fieldInfo.addItem(_HeightInfo);

			field = new FieldDescriptor();
			field.fid = 17;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 20;
			field.lusFid = 0;
			field.label = "Slope";
			field.allowNewChoices = true;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "Slope";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_SlopeInfo = new ChoiceField(field);
			_fieldInfo.addItem(_SlopeInfo);

			field = new FieldDescriptor();
			field.fid = 18;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 20;
			field.lusFid = 0;
			field.label = "Interior Sensitivity";
			field.allowNewChoices = true;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "InteriorSensitivity";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_InteriorSensitivityInfo = new ChoiceField(field);
			_fieldInfo.addItem(_InteriorSensitivityInfo);

			field = new FieldDescriptor();
			field.fid = 58;
			field.lutFid = 0;
			field.numLines = 4;
			field.doesDataCopy = false;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = true;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Sensitivity Details";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "SensitivityDetails";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_SensitivityDetailsInfo = new TextField(field);
			_fieldInfo.addItem(_SensitivityDetailsInfo);

			field = new FieldDescriptor();
			field.fid = 59;
			field.lutFid = 0;
			field.numLines = 6;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Condition Details";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "ConditionDetails";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_ConditionDetailsInfo = new TextField(field);
			_fieldInfo.addItem(_ConditionDetailsInfo);

			field = new FieldDescriptor();
			field.fid = 20;
			field.lutFid = 0;
			field.numLines = 1;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Restorable";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "Restorable";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_RestorableInfo = new ChoiceField(field);
			_fieldInfo.addItem(_RestorableInfo);

			field = new FieldDescriptor();
			field.fid = 21;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 20;
			field.lusFid = 0;
			field.label = "Drainage";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "Drainage";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_DrainageInfo = new ChoiceField(field);
			_fieldInfo.addItem(_DrainageInfo);

			field = new FieldDescriptor();
			field.fid = 22;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Currently Leaking";
			field.allowNewChoices = true;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "CurrentlyLeaking";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_CurrentlyLeakingInfo = new ChoiceField(field);
			_fieldInfo.addItem(_CurrentlyLeakingInfo);

			field = new FieldDescriptor();
			field.fid = 23;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 20;
			field.lusFid = 0;
			field.label = "History of Leaking";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "HistoryOfLeaking";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_HistoryOfLeakingInfo = new ChoiceField(field);
			_fieldInfo.addItem(_HistoryOfLeakingInfo);

			field = new FieldDescriptor();
			field.fid = 24;
			field.lutFid = 0;
			field.numLines = 4;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 80;
			field.lusFid = 0;
			field.label = "Drainage Details";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "DrainageDetails";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_DrainageDetailsInfo = new ChoiceField(field);
			_fieldInfo.addItem(_DrainageDetailsInfo);

			field = new FieldDescriptor();
			field.fid = 57;
			field.lutFid = 0;
			field.numLines = 4;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 80;
			field.lusFid = 0;
			field.label = "Leak Details";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "LeakDetails";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_LeakDetailsInfo = new TextField(field);
			_fieldInfo.addItem(_LeakDetailsInfo);

			field = new FieldDescriptor();
			field.fid = 61;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "X1";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = -1;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Sections";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.fieldName = "X1";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_X1Info = new NumberField(field);
			_fieldInfo.addItem(_X1Info);

			field = new FieldDescriptor();
			field.fid = 62;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Y1";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = -1;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Sections";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.fieldName = "Y1";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_Y1Info = new NumberField(field);
			_fieldInfo.addItem(_Y1Info);

			field = new FieldDescriptor();
			field.fid = 63;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "X2";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = -1;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Sections";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.fieldName = "X2";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_X2Info = new NumberField(field);
			_fieldInfo.addItem(_X2Info);

			field = new FieldDescriptor();
			field.fid = 64;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Y2";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = -1;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Sections";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.fieldName = "Y2";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_Y2Info = new NumberField(field);
			_fieldInfo.addItem(_Y2Info);

			field = new FieldDescriptor();
			field.fid = 60;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Overall Core Condition";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "OverallCoreCondition";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_OverallCoreConditionInfo = new TextField(field);
			_fieldInfo.addItem(_OverallCoreConditionInfo);

			field = new FieldDescriptor();
			field.fid = 25;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Notes";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "Notes";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_NotesInfo = new ChoiceField(field);
			_fieldInfo.addItem(_NotesInfo);

			field = new FieldDescriptor();
			field.fid = 74;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.sourceFID = 3;
			field.unique = false;
			field.fieldType = ENFieldType.DbLink;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.targetFID = 6;
			field.targetDBID = "be9nwdi3p";
			field.label = "Section Users";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.coverText = "Section Users";
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.exact = true;
			field.role = ENRole.NotFound;
			field.fieldName = "SectionUsers";
			field.required = false;
			field.foreignKey = 0;
			field.findEnabled = true;
			_SectionUsersInfo = new DbLinkField(field);
			_fieldInfo.addItem(_SectionUsersInfo);

			field = new FieldDescriptor();
			field.fid = 75;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.URL;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Add Section User";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.appearsAs = "Add  Section User";
			field.fieldName = "AddSectionUser";
			field.required = false;
			field.formula = "URLRoot() & \"db/\" & [_DBID_SECTION_USERS] & \"?a=API_GenAddRecordForm&_fid_6=\" & URLEncode ([Record ID#])& \"&z=\" & Rurl()";
			field.foreignKey = 0;
			field.findEnabled = false;
			_AddSectionUserInfo = new URLField(field);
			_fieldInfo.addItem(_AddSectionUserInfo);

			field = new FieldDescriptor();
			field.fid = 77;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Allowed Section User";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = -1;
			field.mode = ENMode.Summary;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Sections";
			field.blankIsZero = false;
			field.role = ENRole.NotFound;
			field.fieldName = "AllowedSectionUser";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = false;
			_AllowedSectionUserInfo = new NumberField(field);
			_fieldInfo.addItem(_AllowedSectionUserInfo);

			field = new FieldDescriptor();
			field.fid = 78;
			field.lutFid = 69;
			field.doesDataCopy = false;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 29;
			field.label = "Allowed Client User";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = -1;
			field.mode = ENMode.Lookup;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Sections";
			field.blankIsZero = false;
			field.role = ENRole.NotFound;
			field.fieldName = "AllowedClientUser";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_AllowedClientUserInfo = new NumberField(field);
			_fieldInfo.addItem(_AllowedClientUserInfo);

			field = new FieldDescriptor();
			field.fid = 79;
			field.lutFid = 68;
			field.doesDataCopy = false;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 29;
			field.label = "Allowed Facility User";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = -1;
			field.mode = ENMode.Lookup;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Sections";
			field.blankIsZero = false;
			field.role = ENRole.NotFound;
			field.fieldName = "AllowedFacilityUser";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_AllowedFacilityUserInfo = new NumberField(field);
			_fieldInfo.addItem(_AllowedFacilityUserInfo);

			field = new FieldDescriptor();
			field.fid = 80;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Allowed User";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = -1;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Sections";
			field.blankIsZero = false;
			field.role = ENRole.NotFound;
			field.fieldName = "AllowedUser";
			field.required = false;
			field.formula = "[Allowed Client User] + [Allowed Facility User] + [Allowed Section User]";
			field.foreignKey = 0;
			field.findEnabled = true;
			_AllowedUserInfo = new NumberField(field);
			_fieldInfo.addItem(_AllowedUserInfo);

			field = new FieldDescriptor();
			field.fid = 81;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Old RoofSectionID";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = -1;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Sections";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.fieldName = "OldRoofsectionid";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_OldRoofsectionidInfo = new NumberField(field);
			_fieldInfo.addItem(_OldRoofsectionidInfo);

			field = new FieldDescriptor();
			field.fid = 82;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Section Lat";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = -1;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Sections";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.fieldName = "SectionLat";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_SectionLatInfo = new NumberField(field);
			_fieldInfo.addItem(_SectionLatInfo);

			field = new FieldDescriptor();
			field.fid = 83;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Section Long";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = -1;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Sections";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.fieldName = "SectionLong";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_SectionLongInfo = new NumberField(field);
			_fieldInfo.addItem(_SectionLongInfo);

			field = new FieldDescriptor();
			field.fid = 84;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.allowHTML = true;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Photo Thumbnail";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "PhotoThumbnail";
			field.required = false;
			field.formula = "If ([Photo]=\"\",\"\",\"<a href='https://www.quickbase.com/up/\" & Dbid() & \"/a/r\" & [Record ID#] & \"/e8/va/\" & [Photo] & \"' target=_blank>\"";
			field.foreignKey = 0;
			field.findEnabled = true;
			_PhotoThumbnailInfo = new TextField(field);
			_fieldInfo.addItem(_PhotoThumbnailInfo);

			field = new FieldDescriptor();
			field.fid = 85;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.URL;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "QB Map";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.appearsAs = "Site Plan";
			field.fieldName = "QBMap";
			field.required = false;
			field.formula = "\"http://www.quickbaseutilities.com/Maybee/QBMaps/default.aspx?\"";
			field.foreignKey = 0;
			field.findEnabled = true;
			_QBMapInfo = new URLField(field);
			_fieldInfo.addItem(_QBMapInfo);

			field = new FieldDescriptor();
			field.fid = 86;
			field.lutFid = 0;
			field.numLines = 1;
			field.doesDataCopy = false;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "QB Maps Marker";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "QBMapsMarker";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_QBMapsMarkerInfo = new TextField(field);
			_fieldInfo.addItem(_QBMapsMarkerInfo);

			field = new FieldDescriptor();
			field.fid = 87;
			field.lutFid = 0;
			field.numLines = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "QB Maps URL";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "QBMapsUrl";
			field.required = false;
			field.formula = "URLRoot() & \"db/\" & [_DBID_SECTIONS] & \"?a=dr&rid=\"";
			field.foreignKey = 0;
			field.findEnabled = true;
			_QBMapsUrlInfo = new TextField(field);
			_fieldInfo.addItem(_QBMapsUrlInfo);

			field = new FieldDescriptor();
			field.fid = 88;
			field.lutFid = 0;
			field.numLines = 1;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "QB Address";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "QBAddress";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_QBAddressInfo = new TextField(field);
			_fieldInfo.addItem(_QBAddressInfo);

			field = new FieldDescriptor();
			field.fid = 90;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.URL;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Create Report";
			field.allowNewChoices = false;
			field.mode = ENMode.Virtual;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.appearsAs = "Create report";
			field.fieldName = "CreateReport";
			field.required = false;
			field.formula = "\"javascript:void(window.open(\\\"\" &";
			field.foreignKey = 0;
			field.findEnabled = true;
			_CreateReportInfo = new URLField(field);
			_fieldInfo.addItem(_CreateReportInfo);

			field = new FieldDescriptor();
			field.fid = 91;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.File;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Report";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "Report";
			field.required = false;
			field.maxVersions = 3;
			field.foreignKey = 0;
			field.findEnabled = true;
			_ReportInfo = new FileField(field);
			_fieldInfo.addItem(_ReportInfo);

			field = new FieldDescriptor();
			field.fid = 92;
			field.lutFid = 0;
			field.numLines = 1;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "RoofPlanLatLong";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "RoofPlanLatLong";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_RoofPlanLatLongInfo = new TextField(field);
			_fieldInfo.addItem(_RoofPlanLatLongInfo);

			field = new FieldDescriptor();
			field.fid = 93;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.commaStart = 4;
			field.fieldType = ENFieldType.Float;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "RoofPlanZoom";
			field.allowNewChoices = false;
			field.units = "";
			field.decimalPlaces = -1;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Float;
			field.tableName = "Sections";
			field.blankIsZero = true;
			field.role = ENRole.NotFound;
			field.fieldName = "RoofPlanZoom";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_RoofPlanZoomInfo = new NumberField(field);
			_fieldInfo.addItem(_RoofPlanZoomInfo);

			field = new FieldDescriptor();
			field.fid = 94;
			field.lutFid = 0;
			field.numLines = 1;
			field.doesDataCopy = true;
			field.unique = false;
			field.allowHTML = false;
			field.appendOnly = false;
			field.fieldType = ENFieldType.Text;
			field.fieldHelp = "";
			field.width = 40;
			field.lusFid = 0;
			field.label = "Polygon";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "Polygon";
			field.required = false;
			field.formula = "";
			field.foreignKey = 0;
			field.findEnabled = true;
			_PolygonInfo = new TextField(field);
			_fieldInfo.addItem(_PolygonInfo);

			field = new FieldDescriptor();
			field.fid = 95;
			field.lutFid = 0;
			field.doesDataCopy = true;
			field.unique = false;
			field.fieldType = ENFieldType.Date;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Date Installed";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Int64;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "DateInstalled";
			field.required = false;
			field.foreignKey = 0;
			field.findEnabled = true;
			_DateInstalledInfo = new DateField(field);
			_fieldInfo.addItem(_DateInstalledInfo);

			field = new FieldDescriptor();
			field.fid = 96;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.File;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Test Doc";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.NotFound;
			field.fieldName = "TestDoc";
			field.required = false;
			field.maxVersions = 3;
			field.foreignKey = 0;
			field.findEnabled = true;
			_TestDocInfo = new FileField(field);
			_fieldInfo.addItem(_TestDocInfo);

			field = new FieldDescriptor();
			field.fid = 1;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.TimeStamp;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Date Created";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Int64;
			field.tableName = "Sections";
			field.role = ENRole.Created;
			field.fieldName = "DateCreated";
			field.required = false;
			field.foreignKey = 0;
			field.findEnabled = false;
			_DateCreatedInfo = new TimeStampField(field);
			_fieldInfo.addItem(_DateCreatedInfo);

			field = new FieldDescriptor();
			field.fid = 2;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.TimeStamp;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Date Modified";
			field.allowNewChoices = false;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Int64;
			field.tableName = "Sections";
			field.role = ENRole.Modifed;
			field.fieldName = "DateModified";
			field.required = false;
			field.foreignKey = 0;
			field.findEnabled = false;
			_DateModifiedInfo = new TimeStampField(field);
			_fieldInfo.addItem(_DateModifiedInfo);

			field = new FieldDescriptor();
			field.fid = 4;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.UserId;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Record Owner";
			field.allowNewChoices = true;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.Owner;
			field.fieldName = "RecordOwner";
			field.required = false;
			field.foreignKey = 0;
			field.findEnabled = true;
			_RecordOwnerInfo = new UserIdField(field);
			_fieldInfo.addItem(_RecordOwnerInfo);

			field = new FieldDescriptor();
			field.fid = 5;
			field.lutFid = 0;
			field.doesDataCopy = false;
			field.unique = false;
			field.fieldType = ENFieldType.UserId;
			field.fieldHelp = "";
			field.lusFid = 0;
			field.label = "Last Modified By";
			field.allowNewChoices = true;
			field.mode = ENMode.NotFound;
			field.carryChoices = true;
			field.baseType = ENBaseType.Text;
			field.tableName = "Sections";
			field.role = ENRole.Modifier;
			field.fieldName = "LastModifiedBy";
			field.required = false;
			field.foreignKey = 0;
			field.findEnabled = true;
			_LastModifiedByInfo = new UserIdField(field);
			_fieldInfo.addItem(_LastModifiedByInfo);

		}

		public static function getInstance():Sections_Info
		{
			if(_instance == null)
				_instance = new Sections_Info(new Private);
			return _instance;
		}

		public function get tableName():String
		{
			return "Sections";
		}

		public function get isMSATable():Boolean
		{
			return false;
		}

		public function getFieldInfo(name:String):AbstractField
		{
			return this[name + "_Info"];
		}

		// MetaData Information Objects
		private var _ClientInfo:TextField;
		private var _FacilityInfo:TextField;
		private var _DesignationInfo:TextField;
		private var _RoofNameInfo:ChoiceField;
		private var _RoofSystemInfo:ChoiceField;
		private var _AgeInfo:NumberField;
		private var _ConditionIndexInfo:ChoiceField;
		private var _SqFtInfo:NumberField;
		private var _EstCostInfo:CurrencyField;
		private var _RelatedFacilityInfo:NumberField;
		private var _AddLayerInfo:URLField;
		private var _LayersInfo:DbLinkField;
		private var _AddCorePhotoInfo:URLField;
		private var _CorePhotosInfo:DbLinkField;
		private var _AddDetailInfo:URLField;
		private var _DetailsInfo:DbLinkField;
		private var _AddDefectInfo:URLField;
		private var _DefectsInfo:DbLinkField;
		private var _AddInspectionInfo:URLField;
		private var _InspectionsInfo:DbLinkField;
		private var _AddSurveyInfo:URLField;
		private var _SurveysInfo:DbLinkField;
		private var _AddExpenditureInfo:URLField;
		private var _ExpendituresInfo:DbLinkField;
		private var _AddWarrantyInfo:URLField;
		private var _WarrantiesInfo:DbLinkField;
		private var _PhotoInfo:FileField;
		private var _PhotoNameInfo:TextField;
		private var _YearInstalledInfo:NumberField;
		private var _YearInstalledSourceInfo:ChoiceField;
		private var _EstCostPerSqFtInfo:CurrencyField;
		private var _HeightInfo:NumberField;
		private var _SlopeInfo:ChoiceField;
		private var _InteriorSensitivityInfo:ChoiceField;
		private var _SensitivityDetailsInfo:TextField;
		private var _ConditionDetailsInfo:TextField;
		private var _RestorableInfo:ChoiceField;
		private var _DrainageInfo:ChoiceField;
		private var _CurrentlyLeakingInfo:ChoiceField;
		private var _HistoryOfLeakingInfo:ChoiceField;
		private var _DrainageDetailsInfo:ChoiceField;
		private var _LeakDetailsInfo:TextField;
		private var _X1Info:NumberField;
		private var _Y1Info:NumberField;
		private var _X2Info:NumberField;
		private var _Y2Info:NumberField;
		private var _OverallCoreConditionInfo:TextField;
		private var _NotesInfo:ChoiceField;
		private var _SectionUsersInfo:DbLinkField;
		private var _AddSectionUserInfo:URLField;
		private var _AllowedSectionUserInfo:NumberField;
		private var _AllowedClientUserInfo:NumberField;
		private var _AllowedFacilityUserInfo:NumberField;
		private var _AllowedUserInfo:NumberField;
		private var _OldRoofsectionidInfo:NumberField;
		private var _SectionLatInfo:NumberField;
		private var _SectionLongInfo:NumberField;
		private var _PhotoThumbnailInfo:TextField;
		private var _QBMapInfo:URLField;
		private var _QBMapsMarkerInfo:TextField;
		private var _QBMapsUrlInfo:TextField;
		private var _QBAddressInfo:TextField;
		private var _CreateReportInfo:URLField;
		private var _ReportInfo:FileField;
		private var _RoofPlanLatLongInfo:TextField;
		private var _RoofPlanZoomInfo:NumberField;
		private var _PolygonInfo:TextField;
		private var _DateInstalledInfo:DateField;
		private var _TestDocInfo:FileField;
		private var _DateCreatedInfo:TimeStampField;
		private var _DateModifiedInfo:TimeStampField;
		private var _RecordOwnerInfo:UserIdField;
		private var _LastModifiedByInfo:UserIdField;

		// MetaData Information Objects getters
		public function get Client_Info():TextField						{return _ClientInfo;}
		public function get Facility_Info():TextField					{return _FacilityInfo;}
		public function get Designation_Info():TextField				{return _DesignationInfo;}
		public function get RoofName_Info():ChoiceField					{return _RoofNameInfo;}
		public function get RoofSystem_Info():ChoiceField				{return _RoofSystemInfo;}
		public function get Age_Info():NumberField						{return _AgeInfo;}
		public function get ConditionIndex_Info():ChoiceField			{return _ConditionIndexInfo;}
		public function get SqFt_Info():NumberField						{return _SqFtInfo;}
		public function get EstCost_Info():CurrencyField				{return _EstCostInfo;}
		public function get RelatedFacility_Info():NumberField			{return _RelatedFacilityInfo;}
		public function get AddLayer_Info():URLField					{return _AddLayerInfo;}
		public function get Layers_Info():DbLinkField					{return _LayersInfo;}
		public function get AddCorePhoto_Info():URLField				{return _AddCorePhotoInfo;}
		public function get CorePhotos_Info():DbLinkField				{return _CorePhotosInfo;}
		public function get AddDetail_Info():URLField					{return _AddDetailInfo;}
		public function get Details_Info():DbLinkField					{return _DetailsInfo;}
		public function get AddDefect_Info():URLField					{return _AddDefectInfo;}
		public function get Defects_Info():DbLinkField					{return _DefectsInfo;}
		public function get AddInspection_Info():URLField				{return _AddInspectionInfo;}
		public function get Inspections_Info():DbLinkField				{return _InspectionsInfo;}
		public function get AddSurvey_Info():URLField					{return _AddSurveyInfo;}
		public function get Surveys_Info():DbLinkField					{return _SurveysInfo;}
		public function get AddExpenditure_Info():URLField				{return _AddExpenditureInfo;}
		public function get Expenditures_Info():DbLinkField				{return _ExpendituresInfo;}
		public function get AddWarranty_Info():URLField					{return _AddWarrantyInfo;}
		public function get Warranties_Info():DbLinkField				{return _WarrantiesInfo;}
		public function get Photo_Info():FileField						{return _PhotoInfo;}
		public function get PhotoName_Info():TextField					{return _PhotoNameInfo;}
		public function get YearInstalled_Info():NumberField			{return _YearInstalledInfo;}
		public function get YearInstalledSource_Info():ChoiceField		{return _YearInstalledSourceInfo;}
		public function get EstCostPerSqFt_Info():CurrencyField			{return _EstCostPerSqFtInfo;}
		public function get Height_Info():NumberField					{return _HeightInfo;}
		public function get Slope_Info():ChoiceField					{return _SlopeInfo;}
		public function get InteriorSensitivity_Info():ChoiceField		{return _InteriorSensitivityInfo;}
		public function get SensitivityDetails_Info():TextField			{return _SensitivityDetailsInfo;}
		public function get ConditionDetails_Info():TextField			{return _ConditionDetailsInfo;}
		public function get Restorable_Info():ChoiceField				{return _RestorableInfo;}
		public function get Drainage_Info():ChoiceField					{return _DrainageInfo;}
		public function get CurrentlyLeaking_Info():ChoiceField			{return _CurrentlyLeakingInfo;}
		public function get HistoryOfLeaking_Info():ChoiceField			{return _HistoryOfLeakingInfo;}
		public function get DrainageDetails_Info():ChoiceField			{return _DrainageDetailsInfo;}
		public function get LeakDetails_Info():TextField				{return _LeakDetailsInfo;}
		public function get X1_Info():NumberField						{return _X1Info;}
		public function get Y1_Info():NumberField						{return _Y1Info;}
		public function get X2_Info():NumberField						{return _X2Info;}
		public function get Y2_Info():NumberField						{return _Y2Info;}
		public function get OverallCoreCondition_Info():TextField		{return _OverallCoreConditionInfo;}
		public function get Notes_Info():ChoiceField					{return _NotesInfo;}
		public function get SectionUsers_Info():DbLinkField				{return _SectionUsersInfo;}
		public function get AddSectionUser_Info():URLField				{return _AddSectionUserInfo;}
		public function get AllowedSectionUser_Info():NumberField		{return _AllowedSectionUserInfo;}
		public function get AllowedClientUser_Info():NumberField		{return _AllowedClientUserInfo;}
		public function get AllowedFacilityUser_Info():NumberField		{return _AllowedFacilityUserInfo;}
		public function get AllowedUser_Info():NumberField				{return _AllowedUserInfo;}
		public function get OldRoofsectionid_Info():NumberField			{return _OldRoofsectionidInfo;}
		public function get SectionLat_Info():NumberField				{return _SectionLatInfo;}
		public function get SectionLong_Info():NumberField				{return _SectionLongInfo;}
		public function get PhotoThumbnail_Info():TextField				{return _PhotoThumbnailInfo;}
		public function get QBMap_Info():URLField						{return _QBMapInfo;}
		public function get QBMapsMarker_Info():TextField				{return _QBMapsMarkerInfo;}
		public function get QBMapsUrl_Info():TextField					{return _QBMapsUrlInfo;}
		public function get QBAddress_Info():TextField					{return _QBAddressInfo;}
		public function get CreateReport_Info():URLField				{return _CreateReportInfo;}
		public function get Report_Info():FileField						{return _ReportInfo;}
		public function get RoofPlanLatLong_Info():TextField			{return _RoofPlanLatLongInfo;}
		public function get RoofPlanZoom_Info():NumberField				{return _RoofPlanZoomInfo;}
		public function get Polygon_Info():TextField					{return _PolygonInfo;}
		public function get DateInstalled_Info():DateField				{return _DateInstalledInfo;}
		public function get TestDoc_Info():FileField					{return _TestDocInfo;}
		public function get DateCreated_Info():TimeStampField			{return _DateCreatedInfo;}
		public function get DateModified_Info():TimeStampField			{return _DateModifiedInfo;}
		public function get RecordOwner_Info():UserIdField				{return _RecordOwnerInfo;}
		public function get LastModifiedBy_Info():UserIdField			{return _LastModifiedByInfo;}

		// Field getter variables
		private var _fieldNames:ArrayCollection = new ArrayCollection(["Client", "Facility", "Designation", "RoofName", "RoofSystem", 
																		"Age", "ConditionIndex", "SqFt", "EstCost", "RelatedFacility", "AddLayer", "Layers", "AddCorePhoto", 
																		"CorePhotos", "AddDetail", "Details", "AddDefect", "Defects", "AddInspection", "Inspections", "AddSurvey", "Surveys", 
																		"AddExpenditure", "Expenditures", "AddWarranty", "Warranties", "Photo", "PhotoName", "YearInstalled", 
																		"YearInstalledSource", "EstCostPerSqFt", "Height", "Slope", "InteriorSensitivity", "SensitivityDetails", 
																		"ConditionDetails", "Restorable", "Drainage", "CurrentlyLeaking", "HistoryOfLeaking", "DrainageDetails", "LeakDetails", "X1", 
																		"Y1", "X2", "Y2", "OverallCoreCondition", "Notes", "SectionUsers", "AddSectionUser", "AllowedSectionUser", 
																		"AllowedClientUser", "AllowedFacilityUser", "AllowedUser", "OldRoofsectionid", "SectionLat", "SectionLong", 
																		"PhotoThumbnail", "QBMap", "QBMapsMarker", "QBMapsUrl", "QBAddress", "CreateReport", "Report", "RoofPlanLatLong", 
																		"RoofPlanZoom", "Polygon", "DateInstalled", "TestDoc", "DateCreated", "DateModified", "RecordOwner", "LastModifiedBy", ]);
		private var _fieldInfo:ArrayCollection = new ArrayCollection();

		// Field getters
		public function get FieldNames():ArrayCollection				{return _fieldNames;}
		public function get FieldsInfo():ArrayCollection				{return _fieldInfo;}
	}
}

class Private{}
