/* zofwsZoomOnlineFrontendBindingProxy.h
   Generated by gSOAP 2.7.9d from zofws.h
   Copyright(C) 2000-2006, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef zofwsZoomOnlineFrontendBinding_H
#define zofwsZoomOnlineFrontendBinding_H
#include "zofwsH.h"

namespace zofws {
class ZoomOnlineFrontendBinding
{   public:
	struct soap *soap;
	const char *endpoint;
	ZoomOnlineFrontendBinding()
	{ soap = soap_new(); endpoint = "http://moritur/zofws.php"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"zofws", "http://zoomonline.com/zofws", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	virtual ~ZoomOnlineFrontendBinding() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	virtual int zofws__GetNextUrl(char *username, char *&return_) { return soap ? soap_call_zofws__GetNextUrl(soap, endpoint, NULL, username, return_) : SOAP_EOM; };
};

} // namespace zofws

#endif
