/* zoomwsStub.h
   Generated by gSOAP 2.7.9d from zoomws.h
   Copyright(C) 2000-2006, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef zoomwsStub_H
#define zoomwsStub_H
#include "stdsoap2.h"

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/




#ifndef SOAP_TYPE_zoomws__LocalNumberList
#define SOAP_TYPE_zoomws__LocalNumberList (6)
/* zoomws:LocalNumberList */
class SOAP_CMAC zoomws__LocalNumberList
{
public:
	class zoomws__ArrayOfString *list;	/* optional element of type zoomws:ArrayOfString */
	char *warning;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 6; } /* = unique id SOAP_TYPE_zoomws__LocalNumberList */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         zoomws__LocalNumberList() : list(NULL), warning(NULL), soap(NULL) { }
	virtual ~zoomws__LocalNumberList() { }
};
#endif

#ifndef SOAP_TYPE_zoomws__ArrayOfString
#define SOAP_TYPE_zoomws__ArrayOfString (7)
/* zoomws:ArrayOfString */
class SOAP_CMAC zoomws__ArrayOfString
{
public:
	int __sizestring;	/* sequence of elements <string> */
	char **string;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 7; } /* = unique id SOAP_TYPE_zoomws__ArrayOfString */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         zoomws__ArrayOfString() : string(NULL), soap(NULL) { }
	virtual ~zoomws__ArrayOfString() { }
};
#endif

#ifndef SOAP_TYPE__zoomws__GetLocalNumbers
#define SOAP_TYPE__zoomws__GetLocalNumbers (8)
/* zoomws:GetLocalNumbers */
class SOAP_CMAC _zoomws__GetLocalNumbers
{
public:
	char *areaCode;	/* optional element of type xsd:string */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 8; } /* = unique id SOAP_TYPE__zoomws__GetLocalNumbers */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _zoomws__GetLocalNumbers() : areaCode(NULL), soap(NULL) { }
	virtual ~_zoomws__GetLocalNumbers() { }
};
#endif

#ifndef SOAP_TYPE__zoomws__GetLocalNumbersResponse
#define SOAP_TYPE__zoomws__GetLocalNumbersResponse (9)
/* zoomws:GetLocalNumbersResponse */
class SOAP_CMAC _zoomws__GetLocalNumbersResponse
{
public:
	zoomws__LocalNumberList *GetLocalNumbersResult;	/* RPC return element */	/* optional element of type zoomws:LocalNumberList */
	struct soap *soap;	/* transient */
public:
	virtual int soap_type() const { return 9; } /* = unique id SOAP_TYPE__zoomws__GetLocalNumbersResponse */
	virtual void soap_default(struct soap*);
	virtual void soap_serialize(struct soap*) const;
	virtual int soap_put(struct soap*, const char*, const char*) const;
	virtual int soap_out(struct soap*, const char*, int, const char*) const;
	virtual void *soap_get(struct soap*, const char*, const char*);
	virtual void *soap_in(struct soap*, const char*, const char*);
	         _zoomws__GetLocalNumbersResponse() : GetLocalNumbersResult(NULL), soap(NULL) { }
	virtual ~_zoomws__GetLocalNumbersResponse() { }
};
#endif

#ifndef SOAP_TYPE___zoomws__GetLocalNumbers
#define SOAP_TYPE___zoomws__GetLocalNumbers (18)
/* Operation wrapper: */
struct __zoomws__GetLocalNumbers
{
public:
	_zoomws__GetLocalNumbers *zoomws__GetLocalNumbers;	/* optional element of type zoomws:GetLocalNumbers */
};
#endif

#ifndef SOAP_TYPE___zoomws__GetLocalNumbers_
#define SOAP_TYPE___zoomws__GetLocalNumbers_ (20)
/* Operation wrapper: */
struct __zoomws__GetLocalNumbers_
{
public:
	_zoomws__GetLocalNumbers *zoomws__GetLocalNumbers;	/* optional element of type zoomws:GetLocalNumbers */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (23)
/* SOAP Header: */
struct SOAP_ENV__Header
{
public:
	void *dummy;	/* transient */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (24)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (26)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (27)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (28)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (4)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif


/******************************************************************************\
 *                                                                            *
 * Typedef Synonyms                                                           *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Stubs                                                                      *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___zoomws__GetLocalNumbers(struct soap *soap, const char *soap_endpoint, const char *soap_action, _zoomws__GetLocalNumbers *zoomws__GetLocalNumbers, _zoomws__GetLocalNumbersResponse *zoomws__GetLocalNumbersResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___zoomws__GetLocalNumbers_(struct soap *soap, const char *soap_endpoint, const char *soap_action, _zoomws__GetLocalNumbers *zoomws__GetLocalNumbers, _zoomws__GetLocalNumbersResponse *zoomws__GetLocalNumbersResponse);

#endif

/* End of zoomwsStub.h */
