//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileTech.Windows.UI.Setup.Menu {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobileTech.Windows.UI.Setup.Menu.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Bal..
        /// </summary>
        internal static string CustomerBal {
            get {
                return ResourceManager.GetString("CustomerBal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit8000 {
            get {
                return ResourceManager.GetString("Exit8000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen Alignment.
        /// </summary>
        internal static string Pen {
            get {
                return ResourceManager.GetString("Pen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Setup.
        /// </summary>
        internal static string RouteSetup {
            get {
                return ResourceManager.GetString("RouteSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Route.
        /// </summary>
        internal static string SwitchRoute {
            get {
                return ResourceManager.GetString("SwitchRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Info.
        /// </summary>
        internal static string SystemInfo {
            get {
                return ResourceManager.GetString("SystemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telecom Setup.
        /// </summary>
        internal static string TCommSetup {
            get {
                return ResourceManager.GetString("TCommSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8000 - Setup Menu.
        /// </summary>
        internal static string Title8000 {
            get {
                return ResourceManager.GetString("Title8000", resourceCulture);
            }
        }
    }
}
