update advertisingsource
set isRestoration = true
where isActive = 1 and
trim(name) in (
'REPEAT'
,'REF GENERAL'
,'INTERNET WEBSITE'
,'REF CLEANER'
,'YP GENERAL'
,'TV GENERAL'
,'INTERNET GOOGLE'
,'STATE FARM PSP'
,'REF/AGENT CLEANER'
,'REPEAT'
,'REACH LOCAL'
,'LIBERTY MUTUAL'
,'INTERNET YAHOO'
,'RADIO GENERAL'
,'INFORMATION-DIRECT.ASSIST'
,'INTERNET ON LINE ORDER'
,'REFERRAL - CLEANER'
,'INTERNET WEBSITE'
,'REFERRAL - GENERAL'
,'DEFLOOD'
,'FARMERS'
,'TRAVELERS'
,'INTEGRASOURCE'
,'DKI'
,'CONTRACTOR CONNECTIONS'
,'GUARDIAN ENVIRONMENT'
,'ORIENTAL RUG MAILING GENERAL'
,'INSURANCE GENERAL'
);

INSERT INTO `sysversion` (`Version`) VALUES 
(4);