//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DPI.Reports {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class dsStore_ActCustListByDueDate : DataSet {
        
        private spStores_GetActiveCustByDueDateDataTable tablespStores_GetActiveCustByDueDate;
        
        public dsStore_ActCustListByDueDate() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected dsStore_ActCustListByDueDate(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["spStores_GetActiveCustByDueDate"] != null)) {
                    this.Tables.Add(new spStores_GetActiveCustByDueDateDataTable(ds.Tables["spStores_GetActiveCustByDueDate"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public spStores_GetActiveCustByDueDateDataTable spStores_GetActiveCustByDueDate {
            get {
                return this.tablespStores_GetActiveCustByDueDate;
            }
        }
        
        public override DataSet Clone() {
            dsStore_ActCustListByDueDate cln = ((dsStore_ActCustListByDueDate)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["spStores_GetActiveCustByDueDate"] != null)) {
                this.Tables.Add(new spStores_GetActiveCustByDueDateDataTable(ds.Tables["spStores_GetActiveCustByDueDate"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tablespStores_GetActiveCustByDueDate = ((spStores_GetActiveCustByDueDateDataTable)(this.Tables["spStores_GetActiveCustByDueDate"]));
            if ((this.tablespStores_GetActiveCustByDueDate != null)) {
                this.tablespStores_GetActiveCustByDueDate.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "dsStore_ActCustListByDueDate";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsStore_ActCustListByDueDate.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tablespStores_GetActiveCustByDueDate = new spStores_GetActiveCustByDueDateDataTable();
            this.Tables.Add(this.tablespStores_GetActiveCustByDueDate);
        }
        
        private bool ShouldSerializespStores_GetActiveCustByDueDate() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void spStores_GetActiveCustByDueDateRowChangeEventHandler(object sender, spStores_GetActiveCustByDueDateRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class spStores_GetActiveCustByDueDateDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnStoreCode;
            
            private DataColumn columnDisplayName;
            
            private DataColumn columnReportPeriod;
            
            private DataColumn columnCustomerName;
            
            private DataColumn columnAccNumber;
            
            private DataColumn columnPhNumber;
            
            private DataColumn columnlifeMonths;
            
            private DataColumn columnAmtDue;
            
            private DataColumn columnPassDueDays;
            
            private DataColumn columnPayDate;
            
            private DataColumn columnAccountStatus;
            
            private DataColumn columnActivDate;
            
            private DataColumn columnDue_Date;
            
            private DataColumn columnSDiscoDate;
            
            internal spStores_GetActiveCustByDueDateDataTable() : 
                    base("spStores_GetActiveCustByDueDate") {
                this.InitClass();
            }
            
            internal spStores_GetActiveCustByDueDateDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn StoreCodeColumn {
                get {
                    return this.columnStoreCode;
                }
            }
            
            internal DataColumn DisplayNameColumn {
                get {
                    return this.columnDisplayName;
                }
            }
            
            internal DataColumn ReportPeriodColumn {
                get {
                    return this.columnReportPeriod;
                }
            }
            
            internal DataColumn CustomerNameColumn {
                get {
                    return this.columnCustomerName;
                }
            }
            
            internal DataColumn AccNumberColumn {
                get {
                    return this.columnAccNumber;
                }
            }
            
            internal DataColumn PhNumberColumn {
                get {
                    return this.columnPhNumber;
                }
            }
            
            internal DataColumn lifeMonthsColumn {
                get {
                    return this.columnlifeMonths;
                }
            }
            
            internal DataColumn AmtDueColumn {
                get {
                    return this.columnAmtDue;
                }
            }
            
            internal DataColumn PassDueDaysColumn {
                get {
                    return this.columnPassDueDays;
                }
            }
            
            internal DataColumn PayDateColumn {
                get {
                    return this.columnPayDate;
                }
            }
            
            internal DataColumn AccountStatusColumn {
                get {
                    return this.columnAccountStatus;
                }
            }
            
            internal DataColumn ActivDateColumn {
                get {
                    return this.columnActivDate;
                }
            }
            
            internal DataColumn Due_DateColumn {
                get {
                    return this.columnDue_Date;
                }
            }
            
            internal DataColumn SDiscoDateColumn {
                get {
                    return this.columnSDiscoDate;
                }
            }
            
            public spStores_GetActiveCustByDueDateRow this[int index] {
                get {
                    return ((spStores_GetActiveCustByDueDateRow)(this.Rows[index]));
                }
            }
            
            public event spStores_GetActiveCustByDueDateRowChangeEventHandler spStores_GetActiveCustByDueDateRowChanged;
            
            public event spStores_GetActiveCustByDueDateRowChangeEventHandler spStores_GetActiveCustByDueDateRowChanging;
            
            public event spStores_GetActiveCustByDueDateRowChangeEventHandler spStores_GetActiveCustByDueDateRowDeleted;
            
            public event spStores_GetActiveCustByDueDateRowChangeEventHandler spStores_GetActiveCustByDueDateRowDeleting;
            
            public void AddspStores_GetActiveCustByDueDateRow(spStores_GetActiveCustByDueDateRow row) {
                this.Rows.Add(row);
            }
            
            public spStores_GetActiveCustByDueDateRow AddspStores_GetActiveCustByDueDateRow(string StoreCode, string DisplayName, string ReportPeriod, string CustomerName, int AccNumber, string PhNumber, int lifeMonths, System.Decimal AmtDue, int PassDueDays, System.DateTime PayDate, string AccountStatus, System.DateTime ActivDate, System.DateTime Due_Date, System.DateTime SDiscoDate) {
                spStores_GetActiveCustByDueDateRow rowspStores_GetActiveCustByDueDateRow = ((spStores_GetActiveCustByDueDateRow)(this.NewRow()));
                rowspStores_GetActiveCustByDueDateRow.ItemArray = new object[] {
                        StoreCode,
                        DisplayName,
                        ReportPeriod,
                        CustomerName,
                        AccNumber,
                        PhNumber,
                        lifeMonths,
                        AmtDue,
                        PassDueDays,
                        PayDate,
                        AccountStatus,
                        ActivDate,
                        Due_Date,
                        SDiscoDate};
                this.Rows.Add(rowspStores_GetActiveCustByDueDateRow);
                return rowspStores_GetActiveCustByDueDateRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                spStores_GetActiveCustByDueDateDataTable cln = ((spStores_GetActiveCustByDueDateDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new spStores_GetActiveCustByDueDateDataTable();
            }
            
            internal void InitVars() {
                this.columnStoreCode = this.Columns["StoreCode"];
                this.columnDisplayName = this.Columns["DisplayName"];
                this.columnReportPeriod = this.Columns["ReportPeriod"];
                this.columnCustomerName = this.Columns["CustomerName"];
                this.columnAccNumber = this.Columns["AccNumber"];
                this.columnPhNumber = this.Columns["PhNumber"];
                this.columnlifeMonths = this.Columns["lifeMonths"];
                this.columnAmtDue = this.Columns["AmtDue"];
                this.columnPassDueDays = this.Columns["PassDueDays"];
                this.columnPayDate = this.Columns["PayDate"];
                this.columnAccountStatus = this.Columns["AccountStatus"];
                this.columnActivDate = this.Columns["ActivDate"];
                this.columnDue_Date = this.Columns["Due_Date"];
                this.columnSDiscoDate = this.Columns["SDiscoDate"];
            }
            
            private void InitClass() {
                this.columnStoreCode = new DataColumn("StoreCode", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnStoreCode);
                this.columnDisplayName = new DataColumn("DisplayName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDisplayName);
                this.columnReportPeriod = new DataColumn("ReportPeriod", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnReportPeriod);
                this.columnCustomerName = new DataColumn("CustomerName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCustomerName);
                this.columnAccNumber = new DataColumn("AccNumber", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnAccNumber);
                this.columnPhNumber = new DataColumn("PhNumber", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPhNumber);
                this.columnlifeMonths = new DataColumn("lifeMonths", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnlifeMonths);
                this.columnAmtDue = new DataColumn("AmtDue", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnAmtDue);
                this.columnPassDueDays = new DataColumn("PassDueDays", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPassDueDays);
                this.columnPayDate = new DataColumn("PayDate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPayDate);
                this.columnAccountStatus = new DataColumn("AccountStatus", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnAccountStatus);
                this.columnActivDate = new DataColumn("ActivDate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnActivDate);
                this.columnDue_Date = new DataColumn("Due_Date", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDue_Date);
                this.columnSDiscoDate = new DataColumn("SDiscoDate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnSDiscoDate);
                this.columnStoreCode.ReadOnly = true;
                this.columnDisplayName.ReadOnly = true;
                this.columnReportPeriod.ReadOnly = true;
                this.columnCustomerName.ReadOnly = true;
                this.columnAccNumber.AllowDBNull = false;
                this.columnPayDate.AllowDBNull = false;
                this.columnAccountStatus.ReadOnly = true;
            }
            
            public spStores_GetActiveCustByDueDateRow NewspStores_GetActiveCustByDueDateRow() {
                return ((spStores_GetActiveCustByDueDateRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new spStores_GetActiveCustByDueDateRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(spStores_GetActiveCustByDueDateRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.spStores_GetActiveCustByDueDateRowChanged != null)) {
                    this.spStores_GetActiveCustByDueDateRowChanged(this, new spStores_GetActiveCustByDueDateRowChangeEvent(((spStores_GetActiveCustByDueDateRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.spStores_GetActiveCustByDueDateRowChanging != null)) {
                    this.spStores_GetActiveCustByDueDateRowChanging(this, new spStores_GetActiveCustByDueDateRowChangeEvent(((spStores_GetActiveCustByDueDateRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.spStores_GetActiveCustByDueDateRowDeleted != null)) {
                    this.spStores_GetActiveCustByDueDateRowDeleted(this, new spStores_GetActiveCustByDueDateRowChangeEvent(((spStores_GetActiveCustByDueDateRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.spStores_GetActiveCustByDueDateRowDeleting != null)) {
                    this.spStores_GetActiveCustByDueDateRowDeleting(this, new spStores_GetActiveCustByDueDateRowChangeEvent(((spStores_GetActiveCustByDueDateRow)(e.Row)), e.Action));
                }
            }
            
            public void RemovespStores_GetActiveCustByDueDateRow(spStores_GetActiveCustByDueDateRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class spStores_GetActiveCustByDueDateRow : DataRow {
            
            private spStores_GetActiveCustByDueDateDataTable tablespStores_GetActiveCustByDueDate;
            
            internal spStores_GetActiveCustByDueDateRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tablespStores_GetActiveCustByDueDate = ((spStores_GetActiveCustByDueDateDataTable)(this.Table));
            }
            
            public string StoreCode {
                get {
                    try {
                        return ((string)(this[this.tablespStores_GetActiveCustByDueDate.StoreCodeColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetActiveCustByDueDate.StoreCodeColumn] = value;
                }
            }
            
            public string DisplayName {
                get {
                    try {
                        return ((string)(this[this.tablespStores_GetActiveCustByDueDate.DisplayNameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetActiveCustByDueDate.DisplayNameColumn] = value;
                }
            }
            
            public string ReportPeriod {
                get {
                    try {
                        return ((string)(this[this.tablespStores_GetActiveCustByDueDate.ReportPeriodColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetActiveCustByDueDate.ReportPeriodColumn] = value;
                }
            }
            
            public string CustomerName {
                get {
                    try {
                        return ((string)(this[this.tablespStores_GetActiveCustByDueDate.CustomerNameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetActiveCustByDueDate.CustomerNameColumn] = value;
                }
            }
            
            public int AccNumber {
                get {
                    return ((int)(this[this.tablespStores_GetActiveCustByDueDate.AccNumberColumn]));
                }
                set {
                    this[this.tablespStores_GetActiveCustByDueDate.AccNumberColumn] = value;
                }
            }
            
            public string PhNumber {
                get {
                    try {
                        return ((string)(this[this.tablespStores_GetActiveCustByDueDate.PhNumberColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetActiveCustByDueDate.PhNumberColumn] = value;
                }
            }
            
            public int lifeMonths {
                get {
                    try {
                        return ((int)(this[this.tablespStores_GetActiveCustByDueDate.lifeMonthsColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetActiveCustByDueDate.lifeMonthsColumn] = value;
                }
            }
            
            public System.Decimal AmtDue {
                get {
                    try {
                        return ((System.Decimal)(this[this.tablespStores_GetActiveCustByDueDate.AmtDueColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetActiveCustByDueDate.AmtDueColumn] = value;
                }
            }
            
            public int PassDueDays {
                get {
                    try {
                        return ((int)(this[this.tablespStores_GetActiveCustByDueDate.PassDueDaysColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetActiveCustByDueDate.PassDueDaysColumn] = value;
                }
            }
            
            public System.DateTime PayDate {
                get {
                    return ((System.DateTime)(this[this.tablespStores_GetActiveCustByDueDate.PayDateColumn]));
                }
                set {
                    this[this.tablespStores_GetActiveCustByDueDate.PayDateColumn] = value;
                }
            }
            
            public string AccountStatus {
                get {
                    try {
                        return ((string)(this[this.tablespStores_GetActiveCustByDueDate.AccountStatusColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetActiveCustByDueDate.AccountStatusColumn] = value;
                }
            }
            
            public System.DateTime ActivDate {
                get {
                    try {
                        return ((System.DateTime)(this[this.tablespStores_GetActiveCustByDueDate.ActivDateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetActiveCustByDueDate.ActivDateColumn] = value;
                }
            }
            
            public System.DateTime Due_Date {
                get {
                    try {
                        return ((System.DateTime)(this[this.tablespStores_GetActiveCustByDueDate.Due_DateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetActiveCustByDueDate.Due_DateColumn] = value;
                }
            }
            
            public System.DateTime SDiscoDate {
                get {
                    try {
                        return ((System.DateTime)(this[this.tablespStores_GetActiveCustByDueDate.SDiscoDateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetActiveCustByDueDate.SDiscoDateColumn] = value;
                }
            }
            
            public bool IsStoreCodeNull() {
                return this.IsNull(this.tablespStores_GetActiveCustByDueDate.StoreCodeColumn);
            }
            
            public void SetStoreCodeNull() {
                this[this.tablespStores_GetActiveCustByDueDate.StoreCodeColumn] = System.Convert.DBNull;
            }
            
            public bool IsDisplayNameNull() {
                return this.IsNull(this.tablespStores_GetActiveCustByDueDate.DisplayNameColumn);
            }
            
            public void SetDisplayNameNull() {
                this[this.tablespStores_GetActiveCustByDueDate.DisplayNameColumn] = System.Convert.DBNull;
            }
            
            public bool IsReportPeriodNull() {
                return this.IsNull(this.tablespStores_GetActiveCustByDueDate.ReportPeriodColumn);
            }
            
            public void SetReportPeriodNull() {
                this[this.tablespStores_GetActiveCustByDueDate.ReportPeriodColumn] = System.Convert.DBNull;
            }
            
            public bool IsCustomerNameNull() {
                return this.IsNull(this.tablespStores_GetActiveCustByDueDate.CustomerNameColumn);
            }
            
            public void SetCustomerNameNull() {
                this[this.tablespStores_GetActiveCustByDueDate.CustomerNameColumn] = System.Convert.DBNull;
            }
            
            public bool IsPhNumberNull() {
                return this.IsNull(this.tablespStores_GetActiveCustByDueDate.PhNumberColumn);
            }
            
            public void SetPhNumberNull() {
                this[this.tablespStores_GetActiveCustByDueDate.PhNumberColumn] = System.Convert.DBNull;
            }
            
            public bool IslifeMonthsNull() {
                return this.IsNull(this.tablespStores_GetActiveCustByDueDate.lifeMonthsColumn);
            }
            
            public void SetlifeMonthsNull() {
                this[this.tablespStores_GetActiveCustByDueDate.lifeMonthsColumn] = System.Convert.DBNull;
            }
            
            public bool IsAmtDueNull() {
                return this.IsNull(this.tablespStores_GetActiveCustByDueDate.AmtDueColumn);
            }
            
            public void SetAmtDueNull() {
                this[this.tablespStores_GetActiveCustByDueDate.AmtDueColumn] = System.Convert.DBNull;
            }
            
            public bool IsPassDueDaysNull() {
                return this.IsNull(this.tablespStores_GetActiveCustByDueDate.PassDueDaysColumn);
            }
            
            public void SetPassDueDaysNull() {
                this[this.tablespStores_GetActiveCustByDueDate.PassDueDaysColumn] = System.Convert.DBNull;
            }
            
            public bool IsAccountStatusNull() {
                return this.IsNull(this.tablespStores_GetActiveCustByDueDate.AccountStatusColumn);
            }
            
            public void SetAccountStatusNull() {
                this[this.tablespStores_GetActiveCustByDueDate.AccountStatusColumn] = System.Convert.DBNull;
            }
            
            public bool IsActivDateNull() {
                return this.IsNull(this.tablespStores_GetActiveCustByDueDate.ActivDateColumn);
            }
            
            public void SetActivDateNull() {
                this[this.tablespStores_GetActiveCustByDueDate.ActivDateColumn] = System.Convert.DBNull;
            }
            
            public bool IsDue_DateNull() {
                return this.IsNull(this.tablespStores_GetActiveCustByDueDate.Due_DateColumn);
            }
            
            public void SetDue_DateNull() {
                this[this.tablespStores_GetActiveCustByDueDate.Due_DateColumn] = System.Convert.DBNull;
            }
            
            public bool IsSDiscoDateNull() {
                return this.IsNull(this.tablespStores_GetActiveCustByDueDate.SDiscoDateColumn);
            }
            
            public void SetSDiscoDateNull() {
                this[this.tablespStores_GetActiveCustByDueDate.SDiscoDateColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class spStores_GetActiveCustByDueDateRowChangeEvent : EventArgs {
            
            private spStores_GetActiveCustByDueDateRow eventRow;
            
            private DataRowAction eventAction;
            
            public spStores_GetActiveCustByDueDateRowChangeEvent(spStores_GetActiveCustByDueDateRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public spStores_GetActiveCustByDueDateRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
