//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DPI.Reports {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class dsStore_WirelessCommission : DataSet {
        
        private spStores_GetWirelessCommissionDataTable tablespStores_GetWirelessCommission;
        
        public dsStore_WirelessCommission() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected dsStore_WirelessCommission(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["spStores_GetWirelessCommission"] != null)) {
                    this.Tables.Add(new spStores_GetWirelessCommissionDataTable(ds.Tables["spStores_GetWirelessCommission"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public spStores_GetWirelessCommissionDataTable spStores_GetWirelessCommission {
            get {
                return this.tablespStores_GetWirelessCommission;
            }
        }
        
        public override DataSet Clone() {
            dsStore_WirelessCommission cln = ((dsStore_WirelessCommission)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["spStores_GetWirelessCommission"] != null)) {
                this.Tables.Add(new spStores_GetWirelessCommissionDataTable(ds.Tables["spStores_GetWirelessCommission"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tablespStores_GetWirelessCommission = ((spStores_GetWirelessCommissionDataTable)(this.Tables["spStores_GetWirelessCommission"]));
            if ((this.tablespStores_GetWirelessCommission != null)) {
                this.tablespStores_GetWirelessCommission.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "dsStore_WirelessCommission";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsStore_WirelessCommission.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tablespStores_GetWirelessCommission = new spStores_GetWirelessCommissionDataTable();
            this.Tables.Add(this.tablespStores_GetWirelessCommission);
        }
        
        private bool ShouldSerializespStores_GetWirelessCommission() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void spStores_GetWirelessCommissionRowChangeEventHandler(object sender, spStores_GetWirelessCommissionRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class spStores_GetWirelessCommissionDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnStoreCode;
            
            private DataColumn columnDisplayName;
            
            private DataColumn columnReportPeriod;
            
            private DataColumn columnProdName;
            
            private DataColumn columnCommissionRate;
            
            private DataColumn columnTranAmount;
            
            private DataColumn columnLastPayDate;
            
            private DataColumn columnCommissionEared;
            
            private DataColumn columnCommissionSum;
            
            internal spStores_GetWirelessCommissionDataTable() : 
                    base("spStores_GetWirelessCommission") {
                this.InitClass();
            }
            
            internal spStores_GetWirelessCommissionDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn StoreCodeColumn {
                get {
                    return this.columnStoreCode;
                }
            }
            
            internal DataColumn DisplayNameColumn {
                get {
                    return this.columnDisplayName;
                }
            }
            
            internal DataColumn ReportPeriodColumn {
                get {
                    return this.columnReportPeriod;
                }
            }
            
            internal DataColumn ProdNameColumn {
                get {
                    return this.columnProdName;
                }
            }
            
            internal DataColumn CommissionRateColumn {
                get {
                    return this.columnCommissionRate;
                }
            }
            
            internal DataColumn TranAmountColumn {
                get {
                    return this.columnTranAmount;
                }
            }
            
            internal DataColumn LastPayDateColumn {
                get {
                    return this.columnLastPayDate;
                }
            }
            
            internal DataColumn CommissionEaredColumn {
                get {
                    return this.columnCommissionEared;
                }
            }
            
            internal DataColumn CommissionSumColumn {
                get {
                    return this.columnCommissionSum;
                }
            }
            
            public spStores_GetWirelessCommissionRow this[int index] {
                get {
                    return ((spStores_GetWirelessCommissionRow)(this.Rows[index]));
                }
            }
            
            public event spStores_GetWirelessCommissionRowChangeEventHandler spStores_GetWirelessCommissionRowChanged;
            
            public event spStores_GetWirelessCommissionRowChangeEventHandler spStores_GetWirelessCommissionRowChanging;
            
            public event spStores_GetWirelessCommissionRowChangeEventHandler spStores_GetWirelessCommissionRowDeleted;
            
            public event spStores_GetWirelessCommissionRowChangeEventHandler spStores_GetWirelessCommissionRowDeleting;
            
            public void AddspStores_GetWirelessCommissionRow(spStores_GetWirelessCommissionRow row) {
                this.Rows.Add(row);
            }
            
            public spStores_GetWirelessCommissionRow AddspStores_GetWirelessCommissionRow(string StoreCode, string DisplayName, string ReportPeriod, string ProdName, System.Decimal CommissionRate, System.Decimal TranAmount, System.DateTime LastPayDate, System.Decimal CommissionEared, System.Decimal CommissionSum) {
                spStores_GetWirelessCommissionRow rowspStores_GetWirelessCommissionRow = ((spStores_GetWirelessCommissionRow)(this.NewRow()));
                rowspStores_GetWirelessCommissionRow.ItemArray = new object[] {
                        StoreCode,
                        DisplayName,
                        ReportPeriod,
                        ProdName,
                        CommissionRate,
                        TranAmount,
                        LastPayDate,
                        CommissionEared,
                        CommissionSum};
                this.Rows.Add(rowspStores_GetWirelessCommissionRow);
                return rowspStores_GetWirelessCommissionRow;
            }
            
            public spStores_GetWirelessCommissionRow FindByProdName(string ProdName) {
                return ((spStores_GetWirelessCommissionRow)(this.Rows.Find(new object[] {
                            ProdName})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                spStores_GetWirelessCommissionDataTable cln = ((spStores_GetWirelessCommissionDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new spStores_GetWirelessCommissionDataTable();
            }
            
            internal void InitVars() {
                this.columnStoreCode = this.Columns["StoreCode"];
                this.columnDisplayName = this.Columns["DisplayName"];
                this.columnReportPeriod = this.Columns["ReportPeriod"];
                this.columnProdName = this.Columns["ProdName"];
                this.columnCommissionRate = this.Columns["CommissionRate"];
                this.columnTranAmount = this.Columns["TranAmount"];
                this.columnLastPayDate = this.Columns["LastPayDate"];
                this.columnCommissionEared = this.Columns["CommissionEared"];
                this.columnCommissionSum = this.Columns["CommissionSum"];
            }
            
            private void InitClass() {
                this.columnStoreCode = new DataColumn("StoreCode", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnStoreCode);
                this.columnDisplayName = new DataColumn("DisplayName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDisplayName);
                this.columnReportPeriod = new DataColumn("ReportPeriod", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnReportPeriod);
                this.columnProdName = new DataColumn("ProdName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnProdName);
                this.columnCommissionRate = new DataColumn("CommissionRate", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCommissionRate);
                this.columnTranAmount = new DataColumn("TranAmount", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnTranAmount);
                this.columnLastPayDate = new DataColumn("LastPayDate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnLastPayDate);
                this.columnCommissionEared = new DataColumn("CommissionEared", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCommissionEared);
                this.columnCommissionSum = new DataColumn("CommissionSum", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCommissionSum);
                this.Constraints.Add(new UniqueConstraint("dsStore_WirelessCommissionKey1", new DataColumn[] {
                                this.columnProdName}, true));
                this.columnStoreCode.ReadOnly = true;
                this.columnDisplayName.ReadOnly = true;
                this.columnReportPeriod.ReadOnly = true;
                this.columnProdName.AllowDBNull = false;
                this.columnProdName.ReadOnly = true;
                this.columnProdName.Unique = true;
                this.columnCommissionRate.ReadOnly = true;
                this.columnTranAmount.AllowDBNull = false;
                this.columnTranAmount.ReadOnly = true;
                this.columnLastPayDate.ReadOnly = true;
                this.columnCommissionEared.ReadOnly = true;
                this.columnCommissionSum.ReadOnly = true;
            }
            
            public spStores_GetWirelessCommissionRow NewspStores_GetWirelessCommissionRow() {
                return ((spStores_GetWirelessCommissionRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new spStores_GetWirelessCommissionRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(spStores_GetWirelessCommissionRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.spStores_GetWirelessCommissionRowChanged != null)) {
                    this.spStores_GetWirelessCommissionRowChanged(this, new spStores_GetWirelessCommissionRowChangeEvent(((spStores_GetWirelessCommissionRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.spStores_GetWirelessCommissionRowChanging != null)) {
                    this.spStores_GetWirelessCommissionRowChanging(this, new spStores_GetWirelessCommissionRowChangeEvent(((spStores_GetWirelessCommissionRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.spStores_GetWirelessCommissionRowDeleted != null)) {
                    this.spStores_GetWirelessCommissionRowDeleted(this, new spStores_GetWirelessCommissionRowChangeEvent(((spStores_GetWirelessCommissionRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.spStores_GetWirelessCommissionRowDeleting != null)) {
                    this.spStores_GetWirelessCommissionRowDeleting(this, new spStores_GetWirelessCommissionRowChangeEvent(((spStores_GetWirelessCommissionRow)(e.Row)), e.Action));
                }
            }
            
            public void RemovespStores_GetWirelessCommissionRow(spStores_GetWirelessCommissionRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class spStores_GetWirelessCommissionRow : DataRow {
            
            private spStores_GetWirelessCommissionDataTable tablespStores_GetWirelessCommission;
            
            internal spStores_GetWirelessCommissionRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tablespStores_GetWirelessCommission = ((spStores_GetWirelessCommissionDataTable)(this.Table));
            }
            
            public string StoreCode {
                get {
                    try {
                        return ((string)(this[this.tablespStores_GetWirelessCommission.StoreCodeColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetWirelessCommission.StoreCodeColumn] = value;
                }
            }
            
            public string DisplayName {
                get {
                    try {
                        return ((string)(this[this.tablespStores_GetWirelessCommission.DisplayNameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetWirelessCommission.DisplayNameColumn] = value;
                }
            }
            
            public string ReportPeriod {
                get {
                    try {
                        return ((string)(this[this.tablespStores_GetWirelessCommission.ReportPeriodColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetWirelessCommission.ReportPeriodColumn] = value;
                }
            }
            
            public string ProdName {
                get {
                    return ((string)(this[this.tablespStores_GetWirelessCommission.ProdNameColumn]));
                }
                set {
                    this[this.tablespStores_GetWirelessCommission.ProdNameColumn] = value;
                }
            }
            
            public System.Decimal CommissionRate {
                get {
                    try {
                        return ((System.Decimal)(this[this.tablespStores_GetWirelessCommission.CommissionRateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetWirelessCommission.CommissionRateColumn] = value;
                }
            }
            
            public System.Decimal TranAmount {
                get {
                    return ((System.Decimal)(this[this.tablespStores_GetWirelessCommission.TranAmountColumn]));
                }
                set {
                    this[this.tablespStores_GetWirelessCommission.TranAmountColumn] = value;
                }
            }
            
            public System.DateTime LastPayDate {
                get {
                    try {
                        return ((System.DateTime)(this[this.tablespStores_GetWirelessCommission.LastPayDateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetWirelessCommission.LastPayDateColumn] = value;
                }
            }
            
            public System.Decimal CommissionEared {
                get {
                    try {
                        return ((System.Decimal)(this[this.tablespStores_GetWirelessCommission.CommissionEaredColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetWirelessCommission.CommissionEaredColumn] = value;
                }
            }
            
            public System.Decimal CommissionSum {
                get {
                    try {
                        return ((System.Decimal)(this[this.tablespStores_GetWirelessCommission.CommissionSumColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetWirelessCommission.CommissionSumColumn] = value;
                }
            }
            
            public bool IsStoreCodeNull() {
                return this.IsNull(this.tablespStores_GetWirelessCommission.StoreCodeColumn);
            }
            
            public void SetStoreCodeNull() {
                this[this.tablespStores_GetWirelessCommission.StoreCodeColumn] = System.Convert.DBNull;
            }
            
            public bool IsDisplayNameNull() {
                return this.IsNull(this.tablespStores_GetWirelessCommission.DisplayNameColumn);
            }
            
            public void SetDisplayNameNull() {
                this[this.tablespStores_GetWirelessCommission.DisplayNameColumn] = System.Convert.DBNull;
            }
            
            public bool IsReportPeriodNull() {
                return this.IsNull(this.tablespStores_GetWirelessCommission.ReportPeriodColumn);
            }
            
            public void SetReportPeriodNull() {
                this[this.tablespStores_GetWirelessCommission.ReportPeriodColumn] = System.Convert.DBNull;
            }
            
            public bool IsCommissionRateNull() {
                return this.IsNull(this.tablespStores_GetWirelessCommission.CommissionRateColumn);
            }
            
            public void SetCommissionRateNull() {
                this[this.tablespStores_GetWirelessCommission.CommissionRateColumn] = System.Convert.DBNull;
            }
            
            public bool IsLastPayDateNull() {
                return this.IsNull(this.tablespStores_GetWirelessCommission.LastPayDateColumn);
            }
            
            public void SetLastPayDateNull() {
                this[this.tablespStores_GetWirelessCommission.LastPayDateColumn] = System.Convert.DBNull;
            }
            
            public bool IsCommissionEaredNull() {
                return this.IsNull(this.tablespStores_GetWirelessCommission.CommissionEaredColumn);
            }
            
            public void SetCommissionEaredNull() {
                this[this.tablespStores_GetWirelessCommission.CommissionEaredColumn] = System.Convert.DBNull;
            }
            
            public bool IsCommissionSumNull() {
                return this.IsNull(this.tablespStores_GetWirelessCommission.CommissionSumColumn);
            }
            
            public void SetCommissionSumNull() {
                this[this.tablespStores_GetWirelessCommission.CommissionSumColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class spStores_GetWirelessCommissionRowChangeEvent : EventArgs {
            
            private spStores_GetWirelessCommissionRow eventRow;
            
            private DataRowAction eventAction;
            
            public spStores_GetWirelessCommissionRowChangeEvent(spStores_GetWirelessCommissionRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public spStores_GetWirelessCommissionRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
