//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace DPI.Reports {
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class dsStore_Commission : DataSet {
        
        private spStores_GetCommissionDataTable tablespStores_GetCommission;
        
        public dsStore_Commission() {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected dsStore_Commission(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["spStores_GetCommission"] != null)) {
                    this.Tables.Add(new spStores_GetCommissionDataTable(ds.Tables["spStores_GetCommission"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public spStores_GetCommissionDataTable spStores_GetCommission {
            get {
                return this.tablespStores_GetCommission;
            }
        }
        
        public override DataSet Clone() {
            dsStore_Commission cln = ((dsStore_Commission)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["spStores_GetCommission"] != null)) {
                this.Tables.Add(new spStores_GetCommissionDataTable(ds.Tables["spStores_GetCommission"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tablespStores_GetCommission = ((spStores_GetCommissionDataTable)(this.Tables["spStores_GetCommission"]));
            if ((this.tablespStores_GetCommission != null)) {
                this.tablespStores_GetCommission.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "dsStore_Commission";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsStore_Commission.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tablespStores_GetCommission = new spStores_GetCommissionDataTable();
            this.Tables.Add(this.tablespStores_GetCommission);
        }
        
        private bool ShouldSerializespStores_GetCommission() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void spStores_GetCommissionRowChangeEventHandler(object sender, spStores_GetCommissionRowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class spStores_GetCommissionDataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnStoreCode;
            
            private DataColumn columnDisplayName;
            
            private DataColumn columnReportPeriod;
            
            private DataColumn columnCustomerName;
            
            private DataColumn columnAccNumber;
            
            private DataColumn columnPhNumber;
            
            private DataColumn columnPayDate;
            
            private DataColumn columnLastPayDate;
            
            private DataColumn columnLocalAmount;
            
            private DataColumn columnLDAmount;
            
            private DataColumn columnCommission;
            
            private DataColumn columnCommissionSum;
            
            internal spStores_GetCommissionDataTable() : 
                    base("spStores_GetCommission") {
                this.InitClass();
            }
            
            internal spStores_GetCommissionDataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn StoreCodeColumn {
                get {
                    return this.columnStoreCode;
                }
            }
            
            internal DataColumn DisplayNameColumn {
                get {
                    return this.columnDisplayName;
                }
            }
            
            internal DataColumn ReportPeriodColumn {
                get {
                    return this.columnReportPeriod;
                }
            }
            
            internal DataColumn CustomerNameColumn {
                get {
                    return this.columnCustomerName;
                }
            }
            
            internal DataColumn AccNumberColumn {
                get {
                    return this.columnAccNumber;
                }
            }
            
            internal DataColumn PhNumberColumn {
                get {
                    return this.columnPhNumber;
                }
            }
            
            internal DataColumn PayDateColumn {
                get {
                    return this.columnPayDate;
                }
            }
            
            internal DataColumn LastPayDateColumn {
                get {
                    return this.columnLastPayDate;
                }
            }
            
            internal DataColumn LocalAmountColumn {
                get {
                    return this.columnLocalAmount;
                }
            }
            
            internal DataColumn LDAmountColumn {
                get {
                    return this.columnLDAmount;
                }
            }
            
            internal DataColumn CommissionColumn {
                get {
                    return this.columnCommission;
                }
            }
            
            internal DataColumn CommissionSumColumn {
                get {
                    return this.columnCommissionSum;
                }
            }
            
            public spStores_GetCommissionRow this[int index] {
                get {
                    return ((spStores_GetCommissionRow)(this.Rows[index]));
                }
            }
            
            public event spStores_GetCommissionRowChangeEventHandler spStores_GetCommissionRowChanged;
            
            public event spStores_GetCommissionRowChangeEventHandler spStores_GetCommissionRowChanging;
            
            public event spStores_GetCommissionRowChangeEventHandler spStores_GetCommissionRowDeleted;
            
            public event spStores_GetCommissionRowChangeEventHandler spStores_GetCommissionRowDeleting;
            
            public void AddspStores_GetCommissionRow(spStores_GetCommissionRow row) {
                this.Rows.Add(row);
            }
            
            public spStores_GetCommissionRow AddspStores_GetCommissionRow(string StoreCode, string DisplayName, string ReportPeriod, string CustomerName, int AccNumber, string PhNumber, System.DateTime PayDate, System.DateTime LastPayDate, System.Decimal LocalAmount, System.Decimal LDAmount, System.Decimal Commission, System.Decimal CommissionSum) {
                spStores_GetCommissionRow rowspStores_GetCommissionRow = ((spStores_GetCommissionRow)(this.NewRow()));
                rowspStores_GetCommissionRow.ItemArray = new object[] {
                        StoreCode,
                        DisplayName,
                        ReportPeriod,
                        CustomerName,
                        AccNumber,
                        PhNumber,
                        PayDate,
                        LastPayDate,
                        LocalAmount,
                        LDAmount,
                        Commission,
                        CommissionSum};
                this.Rows.Add(rowspStores_GetCommissionRow);
                return rowspStores_GetCommissionRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                spStores_GetCommissionDataTable cln = ((spStores_GetCommissionDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new spStores_GetCommissionDataTable();
            }
            
            internal void InitVars() {
                this.columnStoreCode = this.Columns["StoreCode"];
                this.columnDisplayName = this.Columns["DisplayName"];
                this.columnReportPeriod = this.Columns["ReportPeriod"];
                this.columnCustomerName = this.Columns["CustomerName"];
                this.columnAccNumber = this.Columns["AccNumber"];
                this.columnPhNumber = this.Columns["PhNumber"];
                this.columnPayDate = this.Columns["PayDate"];
                this.columnLastPayDate = this.Columns["LastPayDate"];
                this.columnLocalAmount = this.Columns["LocalAmount"];
                this.columnLDAmount = this.Columns["LDAmount"];
                this.columnCommission = this.Columns["Commission"];
                this.columnCommissionSum = this.Columns["CommissionSum"];
            }
            
            private void InitClass() {
                this.columnStoreCode = new DataColumn("StoreCode", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnStoreCode);
                this.columnDisplayName = new DataColumn("DisplayName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnDisplayName);
                this.columnReportPeriod = new DataColumn("ReportPeriod", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnReportPeriod);
                this.columnCustomerName = new DataColumn("CustomerName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCustomerName);
                this.columnAccNumber = new DataColumn("AccNumber", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnAccNumber);
                this.columnPhNumber = new DataColumn("PhNumber", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPhNumber);
                this.columnPayDate = new DataColumn("PayDate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPayDate);
                this.columnLastPayDate = new DataColumn("LastPayDate", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnLastPayDate);
                this.columnLocalAmount = new DataColumn("LocalAmount", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnLocalAmount);
                this.columnLDAmount = new DataColumn("LDAmount", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnLDAmount);
                this.columnCommission = new DataColumn("Commission", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCommission);
                this.columnCommissionSum = new DataColumn("CommissionSum", typeof(System.Decimal), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnCommissionSum);
                this.columnStoreCode.ReadOnly = true;
                this.columnDisplayName.ReadOnly = true;
                this.columnReportPeriod.ReadOnly = true;
                this.columnCustomerName.ReadOnly = true;
                this.columnAccNumber.AllowDBNull = false;
                this.columnAccNumber.ReadOnly = true;
                this.columnPhNumber.ReadOnly = true;
                this.columnPayDate.AllowDBNull = false;
                this.columnPayDate.ReadOnly = true;
                this.columnLastPayDate.ReadOnly = true;
                this.columnLocalAmount.ReadOnly = true;
                this.columnLDAmount.ReadOnly = true;
                this.columnCommission.ReadOnly = true;
                this.columnCommissionSum.ReadOnly = true;
            }
            
            public spStores_GetCommissionRow NewspStores_GetCommissionRow() {
                return ((spStores_GetCommissionRow)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new spStores_GetCommissionRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(spStores_GetCommissionRow);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.spStores_GetCommissionRowChanged != null)) {
                    this.spStores_GetCommissionRowChanged(this, new spStores_GetCommissionRowChangeEvent(((spStores_GetCommissionRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.spStores_GetCommissionRowChanging != null)) {
                    this.spStores_GetCommissionRowChanging(this, new spStores_GetCommissionRowChangeEvent(((spStores_GetCommissionRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.spStores_GetCommissionRowDeleted != null)) {
                    this.spStores_GetCommissionRowDeleted(this, new spStores_GetCommissionRowChangeEvent(((spStores_GetCommissionRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.spStores_GetCommissionRowDeleting != null)) {
                    this.spStores_GetCommissionRowDeleting(this, new spStores_GetCommissionRowChangeEvent(((spStores_GetCommissionRow)(e.Row)), e.Action));
                }
            }
            
            public void RemovespStores_GetCommissionRow(spStores_GetCommissionRow row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class spStores_GetCommissionRow : DataRow {
            
            private spStores_GetCommissionDataTable tablespStores_GetCommission;
            
            internal spStores_GetCommissionRow(DataRowBuilder rb) : 
                    base(rb) {
                this.tablespStores_GetCommission = ((spStores_GetCommissionDataTable)(this.Table));
            }
            
            public string StoreCode {
                get {
                    try {
                        return ((string)(this[this.tablespStores_GetCommission.StoreCodeColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetCommission.StoreCodeColumn] = value;
                }
            }
            
            public string DisplayName {
                get {
                    try {
                        return ((string)(this[this.tablespStores_GetCommission.DisplayNameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetCommission.DisplayNameColumn] = value;
                }
            }
            
            public string ReportPeriod {
                get {
                    try {
                        return ((string)(this[this.tablespStores_GetCommission.ReportPeriodColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetCommission.ReportPeriodColumn] = value;
                }
            }
            
            public string CustomerName {
                get {
                    try {
                        return ((string)(this[this.tablespStores_GetCommission.CustomerNameColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetCommission.CustomerNameColumn] = value;
                }
            }
            
            public int AccNumber {
                get {
                    return ((int)(this[this.tablespStores_GetCommission.AccNumberColumn]));
                }
                set {
                    this[this.tablespStores_GetCommission.AccNumberColumn] = value;
                }
            }
            
            public string PhNumber {
                get {
                    try {
                        return ((string)(this[this.tablespStores_GetCommission.PhNumberColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetCommission.PhNumberColumn] = value;
                }
            }
            
            public System.DateTime PayDate {
                get {
                    return ((System.DateTime)(this[this.tablespStores_GetCommission.PayDateColumn]));
                }
                set {
                    this[this.tablespStores_GetCommission.PayDateColumn] = value;
                }
            }
            
            public System.DateTime LastPayDate {
                get {
                    try {
                        return ((System.DateTime)(this[this.tablespStores_GetCommission.LastPayDateColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetCommission.LastPayDateColumn] = value;
                }
            }
            
            public System.Decimal LocalAmount {
                get {
                    try {
                        return ((System.Decimal)(this[this.tablespStores_GetCommission.LocalAmountColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetCommission.LocalAmountColumn] = value;
                }
            }
            
            public System.Decimal LDAmount {
                get {
                    try {
                        return ((System.Decimal)(this[this.tablespStores_GetCommission.LDAmountColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetCommission.LDAmountColumn] = value;
                }
            }
            
            public System.Decimal Commission {
                get {
                    try {
                        return ((System.Decimal)(this[this.tablespStores_GetCommission.CommissionColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetCommission.CommissionColumn] = value;
                }
            }
            
            public System.Decimal CommissionSum {
                get {
                    try {
                        return ((System.Decimal)(this[this.tablespStores_GetCommission.CommissionSumColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tablespStores_GetCommission.CommissionSumColumn] = value;
                }
            }
            
            public bool IsStoreCodeNull() {
                return this.IsNull(this.tablespStores_GetCommission.StoreCodeColumn);
            }
            
            public void SetStoreCodeNull() {
                this[this.tablespStores_GetCommission.StoreCodeColumn] = System.Convert.DBNull;
            }
            
            public bool IsDisplayNameNull() {
                return this.IsNull(this.tablespStores_GetCommission.DisplayNameColumn);
            }
            
            public void SetDisplayNameNull() {
                this[this.tablespStores_GetCommission.DisplayNameColumn] = System.Convert.DBNull;
            }
            
            public bool IsReportPeriodNull() {
                return this.IsNull(this.tablespStores_GetCommission.ReportPeriodColumn);
            }
            
            public void SetReportPeriodNull() {
                this[this.tablespStores_GetCommission.ReportPeriodColumn] = System.Convert.DBNull;
            }
            
            public bool IsCustomerNameNull() {
                return this.IsNull(this.tablespStores_GetCommission.CustomerNameColumn);
            }
            
            public void SetCustomerNameNull() {
                this[this.tablespStores_GetCommission.CustomerNameColumn] = System.Convert.DBNull;
            }
            
            public bool IsPhNumberNull() {
                return this.IsNull(this.tablespStores_GetCommission.PhNumberColumn);
            }
            
            public void SetPhNumberNull() {
                this[this.tablespStores_GetCommission.PhNumberColumn] = System.Convert.DBNull;
            }
            
            public bool IsLastPayDateNull() {
                return this.IsNull(this.tablespStores_GetCommission.LastPayDateColumn);
            }
            
            public void SetLastPayDateNull() {
                this[this.tablespStores_GetCommission.LastPayDateColumn] = System.Convert.DBNull;
            }
            
            public bool IsLocalAmountNull() {
                return this.IsNull(this.tablespStores_GetCommission.LocalAmountColumn);
            }
            
            public void SetLocalAmountNull() {
                this[this.tablespStores_GetCommission.LocalAmountColumn] = System.Convert.DBNull;
            }
            
            public bool IsLDAmountNull() {
                return this.IsNull(this.tablespStores_GetCommission.LDAmountColumn);
            }
            
            public void SetLDAmountNull() {
                this[this.tablespStores_GetCommission.LDAmountColumn] = System.Convert.DBNull;
            }
            
            public bool IsCommissionNull() {
                return this.IsNull(this.tablespStores_GetCommission.CommissionColumn);
            }
            
            public void SetCommissionNull() {
                this[this.tablespStores_GetCommission.CommissionColumn] = System.Convert.DBNull;
            }
            
            public bool IsCommissionSumNull() {
                return this.IsNull(this.tablespStores_GetCommission.CommissionSumColumn);
            }
            
            public void SetCommissionSumNull() {
                this[this.tablespStores_GetCommission.CommissionSumColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class spStores_GetCommissionRowChangeEvent : EventArgs {
            
            private spStores_GetCommissionRow eventRow;
            
            private DataRowAction eventAction;
            
            public spStores_GetCommissionRowChangeEvent(spStores_GetCommissionRow row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public spStores_GetCommissionRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
