package com.ebs.eroof.control
{
	public class TestReport
	{
		public static function getTestReport():String
		{
var result:String = "";			
result += "<fo:root xmlns:fo=\"http://www.w3.org/1999/XSL/Format\" font-size=\"12pt\" font-weight=\"bold\" font-family=\"sans-serif\"> ";
result += " <fo:layout-master-set> ";
result += " <fo:simple-page-master margin-right=\"9.75mm\" margin-left=\"9.75mm\" margin-bottom=\"11.2mm\" margin-top=\"11.2mm\" page-height=\"279.4mm\" page-width=\"215.5mm\" master-name=\"title\"> ";
result += " <fo:region-body /> ";
result += " </fo:simple-page-master> ";
result += " <fo:simple-page-master margin-right=\"9.75mm\" margin-left=\"9.75mm\" margin-bottom=\"8.2mm\" margin-top=\"8.2mm\" page-height=\"279.4mm\" page-width=\"215.5mm\" master-name=\"main\"> ";
result += " <fo:region-body margin-bottom=\"20mm\" margin-top=\"20mm\"/> ";
result += " <fo:region-before extent=\"10mm\"/> ";
result += " <fo:region-after extent=\"16mm\"/> ";
result += " </fo:simple-page-master> ";
result += " </fo:layout-master-set> ";
result += " <fo:page-sequence master-reference=\"title\" force-page-count=\"no-force\"> ";
result += " <fo:flow flow-name=\"xsl-region-body\"> ";
result += " <fo:block border=\"2pt solid #0000ff\" padding=\"2pt\"> ";
result += " <fo:block border=\"1pt solid #0000ff\"> ";
result += " <fo:block space-before=\"5mm\" text-align=\"center\"> ";
result += " <fo:external-graphic height=\"28mm\" width=\"160mm\" ";
result += " content-height=\"28mm\" ";
result += " content-width=\"160mm\" ";
result += " padding=\"0mm\" scaling=\"non-uniform\" ";
result += " src=\"images/logo.jpg\"/> ";
result += " </fo:block> ";
result += " <fo:block space-before=\"20mm\" text-align=\"center\" font-size=\"36pt\" color=\"#0000ff\"> ";
result += " Roof Condition Report ";
result += " </fo:block> ";
result += " <fo:block space-before=\"15mm\" font-size=\"16pt\" margin-left=\"65mm\"> ";
result += " <fo:block font-size=\"24pt\" color=\"#0000ff\"> ";
result += " Prepared for: ";
result += " </fo:block> ";
result += " <fo:block space-before=\"8mm\"> ";
result += " Robert Young ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " Vaughan Distribution Centre ";
result += " </fo:block> ";
result += " <fo:block font-weight=\"normal\"> ";
result += " <fo:block> ";
result += " Highway 50 ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " Vaughan, Ontario ";
result += " </fo:block> ";
result += " </fo:block> ";
result += " </fo:block> ";
result += " <fo:block space-before=\"30mm\"/> ";
result += " <fo:table table-layout=\"fixed\" width=\"100%\"> ";
result += " <fo:table-column column-width=\"proportional-column-width(1)\" /> ";
result += " <fo:table-column column-width=\"10mm\" /> ";
result += " <fo:table-column column-width=\"proportional-column-width(1)\" /> ";
result += " <fo:table-body> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " <fo:external-graphic height=\"70mm\" width=\"80mm\" ";
result += " content-height=\"70mm\" ";
result += " content-width=\"80mm\" ";
result += " scaling=\"non-uniform\" ";
result += " src=\"images/satview.jpg\"/> ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " <fo:external-graphic height=\"70mm\" width=\"80mm\" ";
result += " content-height=\"70mm\" ";
result += " content-width=\"80mm\" ";
result += " scaling=\"non-uniform\" ";
result += " src=\"images/plan1.jpg\"/> ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " </fo:table-body> ";
result += " </fo:table> ";
result += " <fo:block space-before=\"5mm\" text-align=\"right\" font-size=\"14pt\" margin-right=\"8mm\"> ";
result += " Date: September 15, 2009 ";
result += " </fo:block> ";
result += " <fo:block space-before=\"9mm\"/> ";
result += " </fo:block> ";
result += " </fo:block> ";
result += " </fo:flow> ";
result += " </fo:page-sequence> ";
result += " <fo:page-sequence master-reference=\"main\" initial-page-number=\"1\"> ";
result += " <fo:static-content flow-name=\"xsl-region-before\"> ";
result += " <fo:block padding-bottom=\"1pt\" border-bottom=\"1pt solid #0000ff\"> ";
result += " <fo:table table-layout=\"fixed\" width=\"100%\" border-bottom=\"2pt solid #0000ff\"> ";
result += " <fo:table-column column-width=\"proportional-column-width(1)\" /> ";
result += " <fo:table-column column-width=\"proportional-column-width(1)\" /> ";
result += " <fo:table-column column-width=\"proportional-column-width(1)\" /> ";
result += " <fo:table-body start-indent=\"0mm\" end-indent=\"0mm\" font-size=\"10pt\" font-weight=\"normal\"> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block> ";
result += " <fo:retrieve-marker retrieve-class-name=\"resultTopLeft\" ";
result += " retrieve-boundary=\"page-sequence\" ";
result += " retrieve-position=\"first-including-carryover\"/> ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"center\"> ";
result += " Facility: Vaughan Distribution Centre ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " <fo:retrieve-marker retrieve-class-name=\"resultTopRight\" ";
result += " retrieve-boundary=\"page-sequence\" ";
result += " retrieve-position=\"first-including-carryover\"/> ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " </fo:table-body> ";
result += " </fo:table> ";
result += " </fo:block> ";
result += " </fo:static-content> ";
result += " <fo:static-content flow-name=\"xsl-region-after\"> ";
result += " <fo:block padding-top=\"1pt\" border-top=\"1pt solid #0000ff\"> ";
result += " <fo:table table-layout=\"fixed\" width=\"100%\" border-top=\"2pt solid #0000ff\"> ";
result += " <fo:table-column column-width=\"proportional-column-width(1)\" /> ";
result += " <fo:table-column column-width=\"30mm\" /> ";
result += " <fo:table-column column-width=\"proportional-column-width(1)\" /> ";
result += " <fo:table-body start-indent=\"0mm\" end-indent=\"0mm\" font-size=\"10pt\" font-weight=\"normal\" vertical-align=\"middle\"> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block> ";
result += " <fo:external-graphic height=\"9mm\" width=\"50mm\" ";
result += " content-height=\"9mm\" ";
result += " content-width=\"50mm\" ";
result += " padding=\"0mm\" scaling=\"non-uniform\" ";
result += " src=\"images/logo.jpg\"/> ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"center\" vertical-align=\"middle\"> ";
result += " Page <fo:page-number/> ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\" vertical-align=\"middle\"> ";
result += " Printed: September 15, 2009 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " </fo:table-body> ";
result += " </fo:table> ";
result += " </fo:block> ";
result += " </fo:static-content> ";
result += " <fo:flow flow-name=\"xsl-region-body\"> ";
result += "<!-- Main description --> ";
result += " <!--fo:block--> ";
result += " <fo:marker marker-class-name=\"resultTopLeft\"> ";
result += " <fo:block font-size=\"10pt\" font-weight=\"normal\"> ";
result += " Moisture Survey Report ";
result += " </fo:block> ";
result += " </fo:marker> ";
result += " <fo:marker marker-class-name=\"resultTopRight\"> ";
result += " <fo:block text-align=\"right\" font-size=\"10pt\" font-weight=\"normal\"> ";
result += " Facility Summary ";
result += " </fo:block> ";
result += " </fo:marker> ";
result += " <!--/fo:block--> ";
result += " ";
result += " <fo:table table-layout=\"fixed\" width=\"100%\"> ";
result += " <fo:table-column column-width=\"40mm\"/> ";
result += " <fo:table-column column-width=\"5mm\"/> ";
result += " <fo:table-column column-width=\"75mm\"/> ";
result += " <fo:table-column column-width=\"5mm\"/> ";
result += " <fo:table-column column-width=\"70mm\"/> ";
result += " <fo:table-body> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Facility: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell> ";
result += " <fo:block> ";
result += " Vaughan Distribution Centre ";
result += " Highway 50 ";
result += " Vaughan, Ontario ";
result += " </fo:block> ";
result += " <fo:block space-before=\"10mm\" /> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell number-rows-spanned=\"6\"> ";
result += " <fo:block> ";
result += " <fo:external-graphic height=\"52mm\" width=\"60mm\" ";
result += " content-height=\"52mm\" ";
result += " content-width=\"60mm\" ";
result += " src=\"images/satview.jpg\"/> ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " <fo:external-graphic height=\"52mm\" width=\"60mm\" ";
result += " content-height=\"52mm\" ";
result += " content-width=\"60mm\" ";
result += " src=\"images/plan1.jpg\"/> ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Contact Name: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " Robert Young ";
result += " </fo:block> ";
result += " <fo:block space-before=\"10mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Contact Telephone: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " </fo:block> ";
result += " <fo:block space-before=\"10mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Date of Last Inspection: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " Sep, 2009 ";
result += " </fo:block> ";
result += " <fo:block space-before=\"10mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Type of Building: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " Distribution Centre ";
result += " </fo:block> ";
result += " <fo:block space-before=\"10mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Type of Neighborhood: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " Industrial ";
result += " </fo:block> ";
result += " <fo:block space-before=\"10mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " </fo:table-body> ";
result += " </fo:table> ";
result += " ";
result += " <fo:table table-layout=\"fixed\" width=\"195mm\" ";
result += " border-collapse=\"separate\"> ";
result += " <fo:table-column column-width=\"25mm\"/> ";
result += " <fo:table-column column-width=\"33mm\"/> ";
result += " <fo:table-column column-width=\"20mm\"/> ";
result += " <fo:table-column column-width=\"18mm\"/> ";
result += " <fo:table-column column-width=\"45mm\"/> ";
result += " <fo:table-column column-width=\"24mm\"/> ";
result += " <fo:table-column column-width=\"30mm\"/> ";
result += " <fo:table-header text-align=\"center\" vertical-align=\"top\" line-height=\"1.6em\"> ";
result += " <fo:table-row background-color=\"#000080\"> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\" number-columns-spanned=\"7\"> ";
result += " <fo:block> ";
result += " List of Roof Sections ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row background-color=\"#c0c0c0\"> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Photo ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Section/ Name/Year installed ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Sq. Ft. ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Height ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " System Type ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Condition Index ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Estimated Replacement Value ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " </fo:table-header> ";
result += " <fo:table-body text-align=\"center\" line-height=\"1.6em\"> ";
result += " <fo:table-row> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block margin=\"3mm\"> ";
result += " <fo:external-graphic height=\"18mm\" width=\"18mm\" ";
result += " content-height=\"18mm\" ";
result += " content-width=\"18mm\" ";
result += " src=\"images/photo1.jpg\"/> ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " 1.1-1.3 ";
result += " </fo:block> ";
result += " <fo:block space-before=\"6mm\"> ";
result += " Lower 2000 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block text-align=\"right\"> ";
result += " 547,500 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block text-align=\"right\"> ";
result += " 35 ft. ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Conventional BUR - Hot applied ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " fair ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block text-align=\"right\"> ";
result += " $6,570,000 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block margin=\"3mm\"> ";
result += " <fo:external-graphic height=\"18mm\" width=\"18mm\" ";
result += " content-height=\"18mm\" ";
result += " content-width=\"18mm\" ";
result += " src=\"images/photo2.jpg\"/> ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " 2.1-2.2 ";
result += " </fo:block> ";
result += " <fo:block space-before=\"6mm\"> ";
result += " Upper Roof 2000 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block text-align=\"right\"> ";
result += " 328,000 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block text-align=\"right\"> ";
result += " 45 ft. ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Conventional BUR - Hot applied ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " fair ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block text-align=\"right\"> ";
result += " $3,936,000 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row background-color=\"#c0c0c0\"> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block text-align=\"right\"> ";
result += " 875,50 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block text-align=\"right\"> ";
result += " $10,506,000 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " </fo:table-body> ";
result += " </fo:table> ";
result += "<!-- Detail description 1 --> ";
result += " <fo:block break-before=\"page\" font-size=\"10pt\" font-weight=\"normal\"> ";
result += " <fo:marker marker-class-name=\"resultTopLeft\"> ";
result += " <fo:block> ";
result += " Condition Report ";
result += " </fo:block> ";
result += " </fo:marker> ";
result += " <fo:marker marker-class-name=\"resultTopRight\"> ";
result += " <fo:block text-align=\"right\"> ";
result += " Roof Area 1.1-1.3 ";
result += " </fo:block> ";
result += " </fo:marker> ";
result += " </fo:block> ";
result += " ";
result += " <fo:table table-layout=\"fixed\" width=\"100%\"> ";
result += " <fo:table-column column-width=\"45mm\"/> ";
result += " <fo:table-column column-width=\"5mm\"/> ";
result += " <fo:table-column column-width=\"65mm\"/> ";
result += " <fo:table-column column-width=\"5mm\"/> ";
result += " <fo:table-column column-width=\"75mm\"/> ";
result += " <fo:table-body> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Designation: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell> ";
result += " <fo:block> ";
result += " 1.1-1.3 ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell number-rows-spanned=\"14\"> ";
result += " <fo:block> ";
result += " <fo:external-graphic height=\"52mm\" width=\"60mm\" ";
result += " content-height=\"52mm\" ";
result += " content-width=\"60mm\" ";
result += " src=\"images/photo3.jpg\"/> ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " <fo:external-graphic height=\"52mm\" width=\"60mm\" ";
result += " content-height=\"52mm\" ";
result += " content-width=\"60mm\" ";
result += " src=\"images/plan2.jpg\"/> ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Roof Name: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " Lower ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Roof Size: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " 547,500 sq. ft. ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Est. Replacement Cost: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " $6,570,000 ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Existing System Type: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " Conventional BUR - Hot applied ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Year Installed: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " 2000 ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Height: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " 35 feet ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Slope: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " slope to valley ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Interior Sensitivity: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " normal ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Condition Index: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " fair ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Drainage: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " Adequate ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Currently Leaking? ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " No ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " History of Leaking? ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " No ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Roof Condition Summary: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " Sept 2009 ";
result += " </fo:block> ";
result += " <fo:block space-before=\"7mm\" number-columns-spanned=\"3\"> ";
result += " areas of wind scour - bare felts ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " no indications of failure such as ridges or blister ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " no results of membrane leaks ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " loose membrane flashings at firewall ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " debris on roof ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " pest bird population ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " </fo:table-body> ";
result += " </fo:table> ";
result += " ";
result += " <fo:block space-before=\"5mm\"/> ";
result += " ";
result += " <fo:table table-layout=\"fixed\" width=\"100%\"> ";
result += " <fo:table-column column-width=\"proportional-column-width(1)\" /> ";
result += " <fo:table-column column-width=\"180mm\" /> ";
result += " <fo:table-column column-width=\"proportional-column-width(1)\" /> ";
result += " <fo:table-body> ";
result += " <fo:table-row> ";
result += " <fo:table-cell column-number=\"2\"> ";
result += " <fo:block border=\"0.01mm solid #000080\"> ";
result += " <fo:block text-align=\"center\" background-color=\"#000080\"> ";
result += " <fo:block padding=\"1mm\"> ";
result += " Overall Core Condition ";
result += " </fo:block> ";
result += " </fo:block> ";
result += " <fo:block padding=\"1mm\"> ";
result += " Roof membrane constructed to industry standards. Solid interply mopping ";
result += " </fo:block> ";
result += " <fo:block padding=\"1mm\" space-before=\"1.2em\"> ";
result += " The ballast material is slag gravel. Slag gravel erodes and puts dirt in the rain water leaders ";
result += " </fo:block> ";
result += " </fo:block> ";
result += " ";
result += " <fo:block space-before=\"10mm\"/> ";
result += " ";
result += " <fo:table table-layout=\"fixed\" width=\"180mm\" border-collapse=\"separate\"> ";
result += " <fo:table-column column-width=\"30mm\"/> ";
result += " <fo:table-column column-width=\"50mm\"/> ";
result += " <fo:table-column column-width=\"100mm\"/> ";
result += " <fo:table-header text-align=\"center\" vertical-align=\"top\" line-height=\"1.6em\"> ";
result += " <fo:table-row background-color=\"#000080\"> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\" number-columns-spanned=\"3\"> ";
result += " <fo:block> ";
result += " Core photos ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row background-color=\"#c0c0c0\"> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Photo ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Date ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Description ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " </fo:table-header> ";
result += " <fo:table-body text-align=\"center\" vertical-align=\"middle\"> ";
result += " <fo:table-row> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block margin=\"3mm\"> ";
result += " <fo:external-graphic height=\"18mm\" width=\"18mm\" ";
result += " content-height=\"18mm\" ";
result += " content-width=\"18mm\" ";
result += " padding=\"0mm\" scaling=\"non-uniform\" ";
result += " src=\"images/photo4.jpg\"/> ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Sep 11, 2009 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Core cut #1 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " </fo:table-body> ";
result += " </fo:table> ";
result += " ";
result += " <fo:block space-before=\"10mm\"/> ";
result += " ";
result += " <fo:table table-layout=\"fixed\" width=\"180mm\" border-collapse=\"separate\"> ";
result += " <fo:table-column column-width=\"60mm\"/> ";
result += " <fo:table-column column-width=\"60mm\"/> ";
result += " <fo:table-column column-width=\"60mm\"/> ";
result += " <fo:table-header text-align=\"center\" vertical-align=\"top\" line-height=\"1.6em\"> ";
result += " <fo:table-row background-color=\"#000080\"> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\" number-columns-spanned=\"3\"> ";
result += " <fo:block> ";
result += " Existing Roof System Construction ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row background-color=\"#c0c0c0\"> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Layer Type ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Description ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Method of Attachment ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " </fo:table-header> ";
result += " <fo:table-body line-height=\"1.6em\"> ";
result += " <fo:table-row> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Deck ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Metal ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Vapor retarder ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Kraft paper ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Cold adhesive ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Insulation ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " 1.5 isocyanurate R 10 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Hot asphalt ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Cover Board ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " 1/2 Fibreboard ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Hot asphalt ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Membrane ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " BUR - 4 ply ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Hot asphalt ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Surfacing ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " slag gravel ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " </fo:table-body> ";
result += " </fo:table> ";
result += " ";
result += " <fo:block space-before=\"52mm\"/> ";
result += " ";
result += " <fo:table table-layout=\"fixed\" width=\"180mm\" border-collapse=\"separate\"> ";
result += " <fo:table-column column-width=\"25mm\"/> ";
result += " <fo:table-column column-width=\"40mm\"/> ";
result += " <fo:table-column column-width=\"60mm\"/> ";
result += " <fo:table-column column-width=\"55mm\"/> ";
result += " <fo:table-header text-align=\"center\" vertical-align=\"top\" line-height=\"1.6em\"> ";
result += " <fo:table-row background-color=\"#000080\"> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\" number-columns-spanned=\"4\"> ";
result += " <fo:block> ";
result += " Overall Roof Inspection Assessments ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row background-color=\"#c0c0c0\"> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Date ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Inspection Type ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Inspecting Company ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Inspector Name ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " </fo:table-header> ";
result += " <fo:table-body> ";
result += " <fo:table-row background-color=\"#c0c0c0\" line-height=\"1.6em\"> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Sep, 2009 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Roof Survey ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Aegis Building Sciences ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Alistair Wilson B.Sc. ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\" number-columns-spanned=\"4\"> ";
result += " <fo:block> ";
result += " Introduction ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " A roof survey of this roof system was performed during the week of Sept 11, 2009 The purpose of this survey was to determine the present condition of the roof systems on this facility. The following diagnostic procedures were employed to determine the condition of the roof system: ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " <fo:block> ";
result += " 1) Visual inspection of the interior of the facility to determine areas of leakage ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " 2) Visual inspection of the roof surface to ascertain membrane anomalies ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " 3) Core cut testing to determine roof system composition ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " 4) Electrical capacitance testing of the roof system to determine areas of wet roof system ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " 5) Probe tests of roof system to determine moisture content of roof system. ";
result += " </fo:block> ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " The roof system is a conventional asphalt built up roof system (BUR) that has been in service for approximately ten years. It was resulted that the roof system has leakage at the time of inspection . The roof area has a slight slope to valley where the drains are located. Ponding on the roof membrane was not observed at the time of inspection. There was no result of roof membrane leakage at the time of inspection. ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " The results of the core cut test, it was observed that the roof system consists of: ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " <fo:block> ";
result += " - metal deck ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " - vapour barrier- kraft ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " - 1.5 isocyanurate insulation R 10 ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " - 4 ply asphalt BUR utilizing #15 organic felts. ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " - pea gravel ballast 400 -600lbs/square slag gravel ";
result += " </fo:block> ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " The roof membrane consists of a convention built up roof membrane utilizing 4 plies of #15 organic felt. The built up roof membrane was constructed to industry standards with a solid interply mopping of asphalt. There is a substanatial pour coat on the roof membrane surface indicating a good membrane application. ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " Slag gravel was used to ballast the roof. This material is very porous and erodes quickly, as it does so, the debris washes down into the drains and can plug the rainwater leaders. This facility drains to a nearby lake and therefore it is unlikely that the gravel ballast will contribute to blocked rain water leaders. ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " The results of the visual inspection, it was observed that the roof membrane does not contain indications of failure such as ridges or blisters in any area of the roof. There are several areas of wind scour on the roof. The exposed bitumen in these two areas, if left unattended will quickly fail resulting in leakage. These areas are will require repour and repair. ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " The roof area uses overflow scuppers which are located along the north wall. These scuppers have exposed bitumen and will eventually fail. These scupper details require the installation of modified bitumen flashings. ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " The furnace stacks were inspected and all sealants are observed to be sound at the time of inspection. The sealants used on the furnace stacks will require replacement in the future. ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " Inspection of the flashing membrane used at the firewall between roof areas 1.1 and 1.2, it was observed that the modified bitumen flashings have become separated from the substrate. Left unattended these will be blown off during an extreme weather event. These membrane flashings will require repairs. ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " The roof system was scanned using electrical capacitance results of the scan did not reveal the presence of any areas of wet insulation in any area of the roof ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " Conclusions: ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " The built up roof membrane system at the the on roof areas 1.1, 1.2 and 1.3 of the Vaughan Distribution Centre are in a sound condition and will provide several years of addtional years of reliable service. The roof system will require the implementation of maintenance procedures and membrane repairs and the locations noted in the result. The roof system is to be inspected in three years time for indications of premature failure such as ridges or blisters.";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " </fo:table-body> ";
result += " </fo:table> ";
result += " ";
result += " <fo:block space-before=\"15mm\"/> ";
result += " ";
result += " <fo:table table-layout=\"fixed\" width=\"180mm\" border-collapse=\"separate\"> ";
result += " <fo:table-column column-width=\"25mm\"/> ";
result += " <fo:table-column column-width=\"40mm\"/> ";
result += " <fo:table-column column-width=\"25mm\"/> ";
result += " <fo:table-column column-width=\"30mm\"/> ";
result += " <fo:table-column column-width=\"30mm\"/> ";
result += " <fo:table-column column-width=\"30mm\"/> ";
result += " <fo:table-header text-align=\"center\" vertical-align=\"top\" line-height=\"1.6em\"> ";
result += " <fo:table-row background-color=\"#000080\"> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\" number-columns-spanned=\"6\"> ";
result += " <fo:block> ";
result += " Recommendations - Details ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row background-color=\"#c0c0c0\"> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Budget Year ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Type of Activity ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Action Item? ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Allocation ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Urgency ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block>Budget $</fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row background-color=\"#c0c0c0\"> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\" number-columns-spanned=\"6\"> ";
result += " <fo:block text-align=\"left\"> ";
result += " Details ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " </fo:table-header> ";
result += " <fo:table-body line-height=\"1.6em\"> ";
result += " <fo:table-row> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " 2009 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block text-align=\"left\"> ";
result += " Repair ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block text-align=\"right\"> ";
result += " $5,000 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\" number-columns-spanned=\"6\"> ";
result += " <fo:block> ";
result += " Scope of Work ";
result += " </fo:block> ";
result += " <fo:block space-before=\"7mm\"> ";
result += " 1) Clean drain screens ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " 2) remove debris from roof area ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " 3) repour wind scoured areas of roof ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " 4) repair loose membrane flashings at firewall between 1.1 and 1.2 ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " 5) install modified bitumen membrane at all overflow scupper locations. ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " 2012 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block text-align=\"left\"> ";
result += " Inspection ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block text-align=\"right\"> ";
result += " $1,000 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\" number-columns-spanned=\"6\"> ";
result += " <fo:block> ";
result += " Scope of Work ";
result += " </fo:block> ";
result += " <fo:block space-before=\"7mm\"> ";
result += " 1) Maintenance inspection. ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row background-color=\"#c0c0c0\"> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block text-align=\"right\"> ";
result += " $6,000 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " </fo:table-body> ";
result += " </fo:table> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " </fo:table-body> ";
result += " </fo:table> ";
result += "<!-- Detail description 2 --> ";
result += " <fo:block break-before=\"page\" font-size=\"10pt\" font-weight=\"normal\"> ";
result += " <fo:marker marker-class-name=\"resultTopLeft\"> ";
result += " <fo:block> ";
result += " Condition Report ";
result += " </fo:block> ";
result += " </fo:marker> ";
result += " <fo:marker marker-class-name=\"resultTopRight\"> ";
result += " <fo:block text-align=\"right\"> ";
result += " Roof Area 2.1-2.2 ";
result += " </fo:block> ";
result += " </fo:marker> ";
result += " </fo:block> ";
result += " ";
result += " <fo:table table-layout=\"fixed\" width=\"100%\"> ";
result += " <fo:table-column column-width=\"45mm\"/> ";
result += " <fo:table-column column-width=\"5mm\"/> ";
result += " <fo:table-column column-width=\"65mm\"/> ";
result += " <fo:table-column column-width=\"5mm\"/> ";
result += " <fo:table-column column-width=\"75mm\"/> ";
result += " <fo:table-body> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Designation: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell> ";
result += " <fo:block> ";
result += " 2.1-2.2 ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell number-rows-spanned=\"14\"> ";
result += " <fo:block> ";
result += " <fo:external-graphic height=\"52mm\" width=\"60mm\" ";
result += " content-height=\"52mm\" ";
result += " content-width=\"60mm\" ";
result += " src=\"images/photo5.jpg\"/> ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " <fo:external-graphic height=\"52mm\" width=\"60mm\" ";
result += " content-height=\"52mm\" ";
result += " content-width=\"60mm\" ";
result += " src=\"images/plan3.jpg\"/> ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Roof Name: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " Upper Roof ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Roof Size: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " 328,000 sq. ft. ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Est. Replacement Cost: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " $3,936,000 ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Existing System Type: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " Conventional BUR - Hot applied ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Year Installed: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " 2000 ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Height: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " 45 feet ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Slope: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " slope to valley ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Interior Sensitivity: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " normal ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Condition Index: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " fair ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Drainage: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " Adequate ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Currently Leaking? ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " No ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " History of Leaking? ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " No ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell> ";
result += " <fo:block text-align=\"right\"> ";
result += " Roof Condition Summary: ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell column-number=\"3\"> ";
result += " <fo:block> ";
result += " Sept 2009 ";
result += " </fo:block> ";
result += " <fo:block space-before=\"7mm\" number-columns-spanned=\"3\"> ";
result += " areas of wind scour - bare felts ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " no results of membrane leaks ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " no areas of wet insulation ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\" /> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " </fo:table-body> ";
result += " </fo:table> ";
result += " ";
result += " <fo:block space-before=\"20mm\"/> ";
result += " ";
result += " <fo:table table-layout=\"fixed\" width=\"100%\"> ";
result += " <fo:table-column column-width=\"proportional-column-width(1)\" /> ";
result += " <fo:table-column column-width=\"180mm\" /> ";
result += " <fo:table-column column-width=\"proportional-column-width(1)\" /> ";
result += " <fo:table-body> ";
result += " <fo:table-row> ";
result += " <fo:table-cell column-number=\"2\"> ";
result += " ";
result += " <fo:block border=\"0.01mm solid #000080\"> ";
result += " <fo:block text-align=\"center\" background-color=\"#000080\"> ";
result += " <fo:block padding=\"1mm\"> ";
result += " Overall Core Condition ";
result += " </fo:block> ";
result += " </fo:block> ";
result += " <fo:block padding=\"1mm\"> ";
result += " Roof membrane constructed to industry standards. Solid interply mopping ";
result += " </fo:block> ";
result += " <fo:block padding=\"1mm\" space-before=\"1.2em\"> ";
result += " The ballast material is slag gravel. Slag gravel erodes and puts dirt in the rain water leaders ";
result += " </fo:block> ";
result += " </fo:block> ";
result += " ";
result += " <fo:block space-before=\"20mm\"/> ";
result += " ";
result += " <fo:table table-layout=\"fixed\" width=\"180mm\" border-collapse=\"separate\"> ";
result += " <fo:table-column column-width=\"30mm\"/> ";
result += " <fo:table-column column-width=\"50mm\"/> ";
result += " <fo:table-column column-width=\"100mm\"/> ";
result += " <fo:table-header text-align=\"center\" vertical-align=\"top\" line-height=\"1.6em\"> ";
result += " <fo:table-row background-color=\"#000080\"> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\" number-columns-spanned=\"3\"> ";
result += " <fo:block> ";
result += " Core photos ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row background-color=\"#c0c0c0\"> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Photo ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Date ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Description ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " </fo:table-header> ";
result += " <fo:table-body text-align=\"center\" vertical-align=\"middle\"> ";
result += " <fo:table-row> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block margin=\"3mm\"> ";
result += " <fo:external-graphic height=\"18mm\" width=\"18mm\" ";
result += " content-height=\"18mm\" ";
result += " content-width=\"18mm\" ";
result += " padding=\"0mm\" scaling=\"non-uniform\" ";
result += " src=\"images/photo6.jpg\"/> ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Sep 11, 2009 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Core cut #1 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " </fo:table-body> ";
result += " </fo:table> ";
result += " ";
result += " <fo:block space-before=\"10mm\"/> ";
result += " ";
result += " <fo:table table-layout=\"fixed\" width=\"180mm\" border-collapse=\"separate\"> ";
result += " <fo:table-column column-width=\"60mm\"/> ";
result += " <fo:table-column column-width=\"60mm\"/> ";
result += " <fo:table-column column-width=\"60mm\"/> ";
result += " <fo:table-header text-align=\"center\" vertical-align=\"top\" line-height=\"1.6em\"> ";
result += " <fo:table-row background-color=\"#000080\"> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\" number-columns-spanned=\"3\"> ";
result += " <fo:block> ";
result += " Existing Roof System Construction ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row background-color=\"#c0c0c0\"> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Layer Type ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Description ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Method of Attachment ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " </fo:table-header> ";
result += " <fo:table-body line-height=\"1.6em\"> ";
result += " <fo:table-row> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Deck ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Metal ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Vapor retarder ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Kraft paper ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Cold adhesive ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Insulation ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " 1.5 isocyanurate R 10 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Hot asphalt ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Cover Board ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " 1/2 Fibreboard ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Hot asphalt ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Membrane ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " BUR - 4 ply ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Hot asphalt ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Surfacing ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " slag gravel ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " </fo:table-body> ";
result += " </fo:table> ";
result += " ";
result += " <fo:block space-before=\"52mm\"/> ";
result += " ";
result += " <fo:table table-layout=\"fixed\" width=\"180mm\" border-collapse=\"separate\"> ";
result += " <fo:table-column column-width=\"25mm\"/> ";
result += " <fo:table-column column-width=\"40mm\"/> ";
result += " <fo:table-column column-width=\"60mm\"/> ";
result += " <fo:table-column column-width=\"55mm\"/> ";
result += " <fo:table-header text-align=\"center\" vertical-align=\"top\" line-height=\"1.6em\"> ";
result += " <fo:table-row background-color=\"#000080\"> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\" number-columns-spanned=\"4\"> ";
result += " <fo:block> ";
result += " Overall Roof Inspection Assessments ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row background-color=\"#c0c0c0\"> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Date ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Inspection Type ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Inspecting Company ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Inspector Name ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " </fo:table-header> ";
result += " <fo:table-body> ";
result += " <fo:table-row background-color=\"#c0c0c0\" line-height=\"1.6em\"> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Sep, 2009 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Roof Survey ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Aegis Building Sciences ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Alistair Wilson B.Sc. ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\" number-columns-spanned=\"4\"> ";
result += " <fo:block> ";
result += " Introduction ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " A roof survey of this roof system was performed during the week of Sept 11, 2009 The purpose of this survey was to determine the present condition of the roof systems on this facility. The following diagnostic procedures were employed to determine the condition of the roof system: ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " <fo:block> ";
result += " 1) Visual inspection of the interior of the facility to determine areas of leakage ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " 2) Visual inspection of the roof surface to ascertain membrane anomalies ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " 3) Core cut testing to determine roof system composition ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " 4) Electrical capacitance testing of the roof system to determine areas of wet roof system ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " 5) Probe tests of roof system to determine moisture content of roof system. ";
result += " </fo:block> ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " The roof system is a conventional asphalt built up roof system (BUR) that has been in service for approximately ten years. It was resulted that the roof system has leakage at the time of inspection . The roof area has a slight slope to valley where the drains are located. Ponding on the roof membrane was not observed at the time of inspection. There was no result of roof membrane leakage at the time of inspection. ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " The results of the core cut test, it was observed that the roof system consists of: ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " <fo:block> ";
result += " - metal deck ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " - vapour barrier- kraft ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " - 1.5 isocyanurate insulation R 10 ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " - 4 ply asphalt BUR utilizing #15 organic felts. ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " - pea gravel ballast 400 -600lbs/square slag gravel ";
result += " </fo:block> ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " The roof membrane consists of a convention built up roof membrane utilizing 4 plies of #15 organic felt. The built up roof membrane was constructed to industry standards with a solid interply mopping of asphalt. There is a substanatial pour coat on the roof membrane surface indicating a good membrane application. ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " Slag gravel was used to ballast the roof. This material is very porous and erodes quickly, as it does so, the debris washes down into the drains and can plug the rainwater leaders. This facility drains to a nearby lake and therefore it is unlikely that the gravel ballast will contribute to blocked rain water leaders. ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " The results of the visual inspection, it was observed that the roof membrane does not contain indications of failure such as ridges or blisters in any area of the roof. There are several areas of wind scour on the roof. The exposed bitumen in these two areas, if left unattended will quickly fail resulting in leakage. These areas are will require repour and repair. ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " The roof area uses overflow scuppers which are located along the north wall. These scuppers have exposed bitumen and will eventually fail. These scupper details require the installation of modified bitumen flashings. ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " The furnace stacks were inspected and all sealants are observed to be sound at the time of inspection. The sealants used on the furnace stacks will require replacement in the future. ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " Inspection of the flashing membrane used at the firewall between roof areas 1.1 and 1.2, it was observed that the modified bitumen flashings have become separated from the substrate. Left unattended these will be blown off during an extreme weather event. These membrane flashings will require repairs. ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " The roof system was scanned using electrical capacitance results of the scan did not reveal the presence of any areas of wet insulation in any area of the roof ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " Conclusions: ";
result += " </fo:block> ";
result += " <fo:block space-before=\"5mm\"> ";
result += " The built up roof membrane system at the the on roof areas 1.1, 1.2 and 1.3 of the Vaughan Distribution Centre are in a sound condition and will provide several years of addtional years of reliable service. The roof system will require the implementation of maintenance procedures and membrane repairs and the locations noted in the result. The roof system is to be inspected in three years time for indications of premature failure such as ridges or blisters.";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " </fo:table-body> ";
result += " </fo:table> ";
result += " <fo:block space-before=\"15mm\"/> ";
result += " <fo:table table-layout=\"fixed\" width=\"180mm\" border-collapse=\"separate\"> ";
result += " <fo:table-column column-width=\"25mm\"/> ";
result += " <fo:table-column column-width=\"40mm\"/> ";
result += " <fo:table-column column-width=\"25mm\"/> ";
result += " <fo:table-column column-width=\"30mm\"/> ";
result += " <fo:table-column column-width=\"30mm\"/> ";
result += " <fo:table-column column-width=\"30mm\"/> ";
result += " <fo:table-header text-align=\"center\" vertical-align=\"top\" line-height=\"1.6em\"> ";
result += " <fo:table-row background-color=\"#000080\"> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\" number-columns-spanned=\"6\"> ";
result += " <fo:block> ";
result += " Recommendations - Details ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row background-color=\"#c0c0c0\"> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Budget Year ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Type of Activity ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Action Item? ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Allocation ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " Urgency ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block>Budget $</fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row background-color=\"#c0c0c0\"> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\" number-columns-spanned=\"6\"> ";
result += " <fo:block text-align=\"left\"> ";
result += " Details ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " </fo:table-header> ";
result += " <fo:table-body line-height=\"1.6em\"> ";
result += " <fo:table-row> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " 2009 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block text-align=\"left\"> ";
result += " Repair ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block text-align=\"right\"> ";
result += " $15,000 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\" number-columns-spanned=\"6\"> ";
result += " <fo:block> ";
result += " Scope of Work ";
result += " </fo:block> ";
result += " <fo:block space-before=\"7mm\"> ";
result += " 1) Clean drain screens ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " 2) remove debris from roof area ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " 3) repour wind scoured areas of roof ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " 4) repair loose membrane flashings at firewall between 1.1 and 1.2 ";
result += " </fo:block> ";
result += " <fo:block> ";
result += " 5) install modified bitumen membrane at all overflow scupper locations. ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block> ";
result += " 2012 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block text-align=\"left\"> ";
result += " Inspection ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block text-align=\"right\"> ";
result += " $1,000 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\" number-columns-spanned=\"6\"> ";
result += " <fo:block> ";
result += " Scope of Work ";
result += " </fo:block> ";
result += " <fo:block space-before=\"7mm\"> ";
result += " 1) Maintenance inspection. ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " <fo:table-row background-color=\"#c0c0c0\"> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block/> ";
result += " </fo:table-cell> ";
result += " <fo:table-cell border=\"0.01mm solid #000080\"> ";
result += " <fo:block text-align=\"right\"> ";
result += " $16,000 ";
result += " </fo:block> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " </fo:table-body> ";
result += " </fo:table> ";
result += " </fo:table-cell> ";
result += " </fo:table-row> ";
result += " </fo:table-body> ";
result += " </fo:table> ";
result += " </fo:flow> ";
result += " </fo:page-sequence> ";
result += "</fo:root> ";

return result;
		}

	}
}