//*******************************************************************
//  <auto-generated>
//       FleXtense : www.flextense.net
//       Version:1.0 Beta Release
//
//
//       Changes to this file may cause incorrect behavior and will be lost if
//       the code is regenerated.
//  <auto-generated>
//*******************************************************************

 package AerSysCo.Server
{

  public class Brand
  {
    private var brandIdField:int = 0;
    private var codeField:String="";
    private var brandNameField:String="";
    private var imageURLprefixField:String="";

    public function Brand()
    {

    }

    public function get brandId():int
    {
        return this.brandIdField;
    }
    public function set brandId(value:int):void
    {
       this.brandIdField = value;
    }
    public function get code():String
    {
        return this.codeField;
    }
    public function set code(value:String):void
    {
       this.codeField = value;
    }
    public function get brandName():String
    {
        return this.brandNameField;
    }
    public function set brandName(value:String):void
    {
       this.brandNameField = value;
    }
    public function get imageURLprefix():String
    {
        return this.imageURLprefixField;
    }
    public function set imageURLprefix(value:String):void
    {
       this.imageURLprefixField = value;
    }

  }
}