//*******************************************************************
//  <auto-generated>
//       FleXtense : www.flextense.net
//       Version:1.0 Beta Release
//
//
//       Changes to this file may cause incorrect behavior and will be lost if
//       the code is regenerated.
//  <auto-generated>
//*******************************************************************

 package AerSysCo.Server
{
  import mx.collections.ArrayCollection;
  import mx.collections.IList;
  import AerSysCo.Server.*;

  public class CatalogItemCollection
  {
    private var _list:ArrayCollection;
    public function CatalogItemCollection():void
    {
        this._list = new ArrayCollection();
    }
    public function get count():int
    {
        return this._list.length;
    }
    public function get bindableData():IList
    {
        return this._list.list;
    }
    public function get itemType():CatalogItem
    {
       return new CatalogItem();
    }
    public function addItem(item:CatalogItem):void
    {
       this._list.addItem(item);
    }
    public function addItemAt(item:CatalogItem,index:int):void
    {
       this._list.addItemAt(item,index);
    }
    public function contains(item:CatalogItem):Boolean
    {
       return this._list.contains(item);
    }
    public function getItemAt(index:int, prefetch:int = 0):CatalogItem
    {
       return CatalogItem(this._list.getItemAt(index,prefetch));
    }
    public function setItemAt(item:CatalogItem,index:int):CatalogItem
    {
        return CatalogItem(this._list.setItemAt(item,index));
    }
    public function getItemIndex(item:CatalogItem):int
    {
        return this._list.getItemIndex(item);
    }
    public function removeItemAt(index:int):CatalogItem
    {
       return CatalogItem(this._list.removeItemAt(index));
    }
    public function removeAll():void
    {
        return this._list.removeAll();
    }
    public function toArray():Array
    {
      return this._list.toArray();
    }

  }

}
