//*******************************************************************
//  <auto-generated>
//       FleXtense : www.flextense.net
//       Version:1.0 Beta Release
//
//
//       Changes to this file may cause incorrect behavior and will be lost if
//       the code is regenerated.
//  <auto-generated>
//*******************************************************************

 package AerSysCo.Server
{

  public class CheckInResult
  {
    private var resultField:AerSysCo.Server.RequestResult;
    private var acknowURLField:String="";
    private var cartField:AerSysCo.Server.ShoppingCart;
    private var errorsField:Array;

    public function CheckInResult()
    {
      this.resultField = new AerSysCo.Server.RequestResult();
      this.cartField = new AerSysCo.Server.ShoppingCart();
      this.errorsField = new Array();

    }

    public function get result():AerSysCo.Server.RequestResult
    {
        return this.resultField;
    }
    public function set result(value:AerSysCo.Server.RequestResult):void
    {
       this.resultField = value;
    }
    public function get acknowURL():String
    {
        return this.acknowURLField;
    }
    public function set acknowURL(value:String):void
    {
       this.acknowURLField = value;
    }
    public function get cart():AerSysCo.Server.ShoppingCart
    {
        return this.cartField;
    }
    public function set cart(value:AerSysCo.Server.ShoppingCart):void
    {
       this.cartField = value;
    }
    [ArrayElementType("String")]
    public function get errors():Array
    {
        return this.errorsField;
    }
    [ArrayElementType("String")]
    public function set errors(value:Array):void
    {
       this.errorsField = value;
    }

  }
}