//*******************************************************************
//  <auto-generated>
//       FleXtense : www.flextense.net
//       Version:1.0 Beta Release
//
//
//       Changes to this file may cause incorrect behavior and will be lost if
//       the code is regenerated.
//  <auto-generated>
//*******************************************************************

 package AerSysCo.Server
{

  public class CustomerListResult
  {
    private var resultField:AerSysCo.Server.RequestResult;
    private var customersField:AerSysCo.Server.CustomerCollection;

    public function CustomerListResult()
    {
      this.resultField = new AerSysCo.Server.RequestResult();
      this.customersField = new AerSysCo.Server.CustomerCollection();

    }

    public function get result():AerSysCo.Server.RequestResult
    {
        return this.resultField;
    }
    public function set result(value:AerSysCo.Server.RequestResult):void
    {
       this.resultField = value;
    }
    public function get customers():AerSysCo.Server.CustomerCollection
    {
        return this.customersField;
    }
    public function set customers(value:AerSysCo.Server.CustomerCollection):void
    {
       this.customersField = value;
    }

  }
}