//*******************************************************************
//  <auto-generated>
//       FleXtense : www.flextense.net
//       Version:1.0 Beta Release
//
//
//       Changes to this file may cause incorrect behavior and will be lost if
//       the code is regenerated.
//  <auto-generated>
//*******************************************************************

 package AerSysCo.Server
{

  public class CustomerResult
  {
    private var resultField:AerSysCo.Server.RequestResult;
    private var customerField:AerSysCo.Server.Customer;

    public function CustomerResult()
    {
      this.resultField = new AerSysCo.Server.RequestResult();
      this.customerField = new AerSysCo.Server.Customer();

    }

    public function get result():AerSysCo.Server.RequestResult
    {
        return this.resultField;
    }
    public function set result(value:AerSysCo.Server.RequestResult):void
    {
       this.resultField = value;
    }
    public function get customer():AerSysCo.Server.Customer
    {
        return this.customerField;
    }
    public function set customer(value:AerSysCo.Server.Customer):void
    {
       this.customerField = value;
    }

  }
}