//*******************************************************************
//  <auto-generated>
//       FleXtense : www.flextense.net
//       Version:1.0 Beta Release
//
//
//       Changes to this file may cause incorrect behavior and will be lost if
//       the code is regenerated.
//  <auto-generated>
//*******************************************************************

 package AerSysCo.Server
{

  public class OrderFilter
  {
    private var createdByField:String="";
    private var statusIdField:int = 0;
    private var poNumberField:String="";
    private var poNumberStrongField:String="";
    private var confirmNumberField:String="";
    private var quantityField:int = 0;
    private var fromDateField:Date;
    private var toDateField:Date;
    private var customerIdField:int = 0;

    public function OrderFilter()
    {

    }

    public function get createdBy():String
    {
        return this.createdByField;
    }
    public function set createdBy(value:String):void
    {
       this.createdByField = value;
    }
    public function get statusId():int
    {
        return this.statusIdField;
    }
    public function set statusId(value:int):void
    {
       this.statusIdField = value;
    }
    public function get poNumber():String
    {
        return this.poNumberField;
    }
    public function set poNumber(value:String):void
    {
       this.poNumberField = value;
    }
    public function get poNumberStrong():String
    {
        return this.poNumberStrongField;
    }
    public function set poNumberStrong(value:String):void
    {
       this.poNumberStrongField = value;
    }
    public function get confirmNumber():String
    {
        return this.confirmNumberField;
    }
    public function set confirmNumber(value:String):void
    {
       this.confirmNumberField = value;
    }
    public function get quantity():int
    {
        return this.quantityField;
    }
    public function set quantity(value:int):void
    {
       this.quantityField = value;
    }
    public function get fromDate():Date
    {
        return this.fromDateField;
    }
    public function set fromDate(value:Date):void
    {
       this.fromDateField = value;
    }
    public function get toDate():Date
    {
        return this.toDateField;
    }
    public function set toDate(value:Date):void
    {
       this.toDateField = value;
    }
    public function get customerId():int
    {
        return this.customerIdField;
    }
    public function set customerId(value:int):void
    {
       this.customerIdField = value;
    }

  }
}