//*******************************************************************
//  <auto-generated>
//       FleXtense : www.flextense.net
//       Version:1.0 Beta Release
//
//
//       Changes to this file may cause incorrect behavior and will be lost if
//       the code is regenerated.
//  <auto-generated>
//*******************************************************************

 package AerSysCo.Server
{

  public class OrderListResult
  {
    private var resultField:AerSysCo.Server.RequestResult;
    private var ordersField:AerSysCo.Server.OrderCollection;

    public function OrderListResult()
    {
      this.resultField = new AerSysCo.Server.RequestResult();
      this.ordersField = new AerSysCo.Server.OrderCollection();

    }

    public function get result():AerSysCo.Server.RequestResult
    {
        return this.resultField;
    }
    public function set result(value:AerSysCo.Server.RequestResult):void
    {
       this.resultField = value;
    }
    public function get orders():AerSysCo.Server.OrderCollection
    {
        return this.ordersField;
    }
    public function set orders(value:AerSysCo.Server.OrderCollection):void
    {
       this.ordersField = value;
    }

  }
}