//*******************************************************************
//  <auto-generated>
//       FleXtense : www.flextense.net
//       Version:1.0 Beta Release
//
//
//       Changes to this file may cause incorrect behavior and will be lost if
//       the code is regenerated.
//  <auto-generated>
//*******************************************************************

 package AerSysCo.Server
{

  public class ShippingOption
  {
    private var shippingTypeIdField:int = 0;
    private var shippigTypeField:AerSysCo.Server.ShippingType;
    private var isApplicableField:Boolean;
    private var costField:Number = 0;

    public function ShippingOption()
    {
      this.shippigTypeField = new AerSysCo.Server.ShippingType();

    }

    public function get shippingTypeId():int
    {
        return this.shippingTypeIdField;
    }
    public function set shippingTypeId(value:int):void
    {
       this.shippingTypeIdField = value;
    }
    public function get shippigType():AerSysCo.Server.ShippingType
    {
        return this.shippigTypeField;
    }
    public function set shippigType(value:AerSysCo.Server.ShippingType):void
    {
       this.shippigTypeField = value;
    }
    public function get isApplicable():Boolean
    {
        return this.isApplicableField;
    }
    public function set isApplicable(value:Boolean):void
    {
       this.isApplicableField = value;
    }
    public function get cost():Number
    {
        return this.costField;
    }
    public function set cost(value:Number):void
    {
       this.costField = value;
    }

  }
}