//*******************************************************************
//  <auto-generated>
//       FleXtense : www.flextense.net
//       Version:1.0 Beta Release
//
//
//       Changes to this file may cause incorrect behavior and will be lost if
//       the code is regenerated.
//  <auto-generated>
//*******************************************************************

 package AerSysCo.Server
{

  public class ShippingAddress
  {
    private var addressIdField:int = 0;
    private var customerIdField:int = 0;
    private var createdByUserField:String="";
    private var lastUpdateDateField:Date;
    private var dateCreatedField:Date;
    private var nameField:String="";
    private var address1Field:String="";
    private var address2Field:String="";
    private var cityField:String="";
    private var stateField:String="";
    private var zipField:String="";
    private var countryField:String="";

    public function ShippingAddress()
    {

    }

    public function get addressId():int
    {
        return this.addressIdField;
    }
    public function set addressId(value:int):void
    {
       this.addressIdField = value;
    }
    public function get customerId():int
    {
        return this.customerIdField;
    }
    public function set customerId(value:int):void
    {
       this.customerIdField = value;
    }
    public function get createdByUser():String
    {
        return this.createdByUserField;
    }
    public function set createdByUser(value:String):void
    {
       this.createdByUserField = value;
    }
    public function get lastUpdateDate():Date
    {
        return this.lastUpdateDateField;
    }
    public function set lastUpdateDate(value:Date):void
    {
       this.lastUpdateDateField = value;
    }
    public function get dateCreated():Date
    {
        return this.dateCreatedField;
    }
    public function set dateCreated(value:Date):void
    {
       this.dateCreatedField = value;
    }
    public function get name():String
    {
        return this.nameField;
    }
    public function set name(value:String):void
    {
       this.nameField = value;
    }
    public function get address1():String
    {
        return this.address1Field;
    }
    public function set address1(value:String):void
    {
       this.address1Field = value;
    }
    public function get address2():String
    {
        return this.address2Field;
    }
    public function set address2(value:String):void
    {
       this.address2Field = value;
    }
    public function get city():String
    {
        return this.cityField;
    }
    public function set city(value:String):void
    {
       this.cityField = value;
    }
    public function get state():String
    {
        return this.stateField;
    }
    public function set state(value:String):void
    {
       this.stateField = value;
    }
    public function get zip():String
    {
        return this.zipField;
    }
    public function set zip(value:String):void
    {
       this.zipField = value;
    }
    public function get country():String
    {
        return this.countryField;
    }
    public function set country(value:String):void
    {
       this.countryField = value;
    }

  }
}